# generated by datamodel-codegen:
#   filename:  material/builders/multi_material/interfaces/slab_grain_boundary_builder_parameters.json
#   version:   0.28.5

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field, conint


class ZSLStrainMatchingParametersSchema(BaseModel):
    max_area: Optional[float] = 50
    """
    Maximum area for strain matching
    """
    max_area_ratio_tol: Optional[float] = 0.09
    """
    Maximum area ratio tolerance
    """
    max_length_tol: Optional[float] = 0.03
    """
    Maximum length tolerance
    """
    max_angle_tol: Optional[float] = 0.01
    """
    Maximum angle tolerance
    """


class SlabGrainBoundaryBuilderParametersSchema(BaseModel):
    strain_matching_parameters: Optional[ZSLStrainMatchingParametersSchema] = Field(
        None, title="ZSL Strain Matching Parameters Schema"
    )
    """
    Parameters for ZSL strain matching
    """
    default_index: Optional[conint(ge=0)] = 0
    """
    Default index for the selector
    """
