# generated by datamodel-codegen:
#   filename:  instrument/instrument_properties.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel, Field


class SlugifiedEntry(BaseModel):
    name: str
    """
    descriptive human-readable name of entry
    """
    slug: str
    """
    machine-readable identifier
    """


class SlugifiedEntryOrSlug(Enum):
    characterization = "characterization"


class SlugifiedEntryOrSlug175(Enum):
    microscopy = "microscopy"
    spectroscopy = "spectroscopy"
    diffraction = "diffraction"
    electrical = "electrical"
    optical = "optical"


class SlugifiedEntryOrSlug176(Enum):
    scanning_probe_microscopy = "scanning_probe_microscopy"
    electron_microscopy = "electron_microscopy"
    x_ray = "x_ray"
    transport = "transport"
    dielectric = "dielectric"
    ultraviolet_visible_near_infrared = "ultraviolet_visible_near_infrared"


class SlugifiedEntryOrSlug177(Enum):
    atomic_force_microscopy = "atomic_force_microscopy"
    scanning_tunneling_microscopy = "scanning_tunneling_microscopy"
    scanning_tunneling_spectroscopy = "scanning_tunneling_spectroscopy"
    piezoresponse_force_microscopy = "piezoresponse_force_microscopy"
    kelvin_probe_force_microscopy = "kelvin_probe_force_microscopy"
    conductive_atomic_force_microscopy = "conductive_atomic_force_microscopy"
    magnetic_force_microscopy = "magnetic_force_microscopy"


class SlugifiedEntryOrSlug178(Enum):
    experimental = "experimental"


class CharacterizationTechniqueCategorySchema(BaseModel):
    tier2: Optional[Union[SlugifiedEntry, SlugifiedEntryOrSlug]] = Field(None, title="slugified entry or slug")
    """
    contains either object with slugified entry or slug only as a string
    """
    tier3: Optional[Union[SlugifiedEntry, SlugifiedEntryOrSlug175]] = Field(None, title="slugified entry or slug")
    """
    contains either object with slugified entry or slug only as a string
    """
    type: Optional[Union[SlugifiedEntry, SlugifiedEntryOrSlug176]] = Field(None, title="slugified entry or slug")
    """
    contains either object with slugified entry or slug only as a string
    """
    subtype: Optional[Union[SlugifiedEntry, SlugifiedEntryOrSlug177]] = Field(None, title="slugified entry or slug")
    """
    contains either object with slugified entry or slug only as a string
    """
    tier1: Optional[Union[SlugifiedEntry, SlugifiedEntryOrSlug178]] = Field(None, title="slugified entry or slug")
    """
    contains either object with slugified entry or slug only as a string
    """


class SlugifiedEntryOrSlug179(Enum):
    synthesis = "synthesis"


class SlugifiedEntryOrSlug180(Enum):
    vapor_deposition = "vapor_deposition"
    solution_processing = "solution_processing"
    bulk_growth = "bulk_growth"
    post_processing = "post_processing"


class SlugifiedEntryOrSlug181(Enum):
    physical_vapor_deposition = "physical_vapor_deposition"
    chemical_vapor_deposition = "chemical_vapor_deposition"
    annealing = "annealing"


class SlugifiedEntryOrSlug182(Enum):
    pulsed_laser_deposition = "pulsed_laser_deposition"
    sputtering = "sputtering"
    molecular_beam_epitaxy = "molecular_beam_epitaxy"
    thermal_evaporation = "thermal_evaporation"
    electron_beam_evaporation = "electron_beam_evaporation"
    atomic_layer_deposition = "atomic_layer_deposition"
    plasma_enhanced_atomic_layer_deposition = "plasma_enhanced_atomic_layer_deposition"
    thermal_chemical_vapor_deposition = "thermal_chemical_vapor_deposition"
    metalorganic_chemical_vapor_deposition = "metalorganic_chemical_vapor_deposition"
    plasma_enhanced_chemical_vapor_deposition = "plasma_enhanced_chemical_vapor_deposition"


class SlugifiedEntryOrSlug183(Enum):
    experimental = "experimental"


class SynthesisTechniqueCategorySchema(BaseModel):
    tier2: Optional[Union[SlugifiedEntry, SlugifiedEntryOrSlug179]] = Field(None, title="slugified entry or slug")
    """
    contains either object with slugified entry or slug only as a string
    """
    tier3: Optional[Union[SlugifiedEntry, SlugifiedEntryOrSlug180]] = Field(None, title="slugified entry or slug")
    """
    contains either object with slugified entry or slug only as a string
    """
    type: Optional[Union[SlugifiedEntry, SlugifiedEntryOrSlug181]] = Field(None, title="slugified entry or slug")
    """
    contains either object with slugified entry or slug only as a string
    """
    subtype: Optional[Union[SlugifiedEntry, SlugifiedEntryOrSlug182]] = Field(None, title="slugified entry or slug")
    """
    contains either object with slugified entry or slug only as a string
    """
    tier1: Optional[Union[SlugifiedEntry, SlugifiedEntryOrSlug183]] = Field(None, title="slugified entry or slug")
    """
    contains either object with slugified entry or slug only as a string
    """


class Kind(Enum):
    probe = "probe"
    cantilever = "cantilever"
    scanner = "scanner"
    laser = "laser"
    detector = "detector"
    lock_in_amplifier = "lock_in_amplifier"
    controller = "controller"
    heater = "heater"
    cryostat = "cryostat"
    chamber = "chamber"
    stage = "stage"
    evaporation_source = "evaporation_source"
    target_holder = "target_holder"
    gas_line = "gas_line"
    mass_flow_controller = "mass_flow_controller"
    pump = "pump"
    gauge = "gauge"
    other = "other"


class InstrumentComponentSchema(BaseModel):
    kind: Kind
    name: str
    vendor: Optional[str] = None
    model: Optional[str] = None
    serialNumber: Optional[str] = None
    parameters: Optional[Dict[str, Any]] = None
    """
    Component-specific parameters, e.g. springConstant and resonanceFrequency for a cantilever.
    """


class RunConfig(BaseModel):
    commandTemplate: str
    """
    The command template of the application
    """
    outFileName: str
    """
    The output file name of the application
    """


class ApplicationSchema(BaseModel):
    id: Optional[str] = Field(None, alias="_id")
    """
    entity identity
    """
    slug: Optional[str] = None
    """
    entity slug
    """
    systemName: Optional[str] = None
    schemaVersion: Optional[str] = "2022.8.16"
    """
    entity's schema version. Used to distinct between different schemas.
    """
    name: str
    """
    entity name
    """
    isDefault: Optional[bool] = False
    """
    Identifies that entity is defaultable
    """
    shortName: str
    """
    The short name of the application. e.g. qe
    """
    summary: str
    """
    Application's short description.
    """
    version: str
    """
    Application version. e.g. 5.3.5
    """
    build: str
    """
    Application build. e.g. VTST
    """
    isDefaultVersion: Optional[bool] = None
    """
    Whether the version is the default version
    """
    hasAdvancedComputeOptions: Optional[bool] = None
    """
    Whether advanced compute options are present
    """
    isLicensed: Optional[bool] = None
    """
    Whether licensing is present
    """
    isUsingMaterial: Optional[bool] = None
    """
    Whether the application is using (being passed during a downstream processing routine) a material structure.
    """
    runConfig: Optional[RunConfig] = None
    """
    The run configuration of the application
    """


class Location(BaseModel):
    facility: Optional[str] = None
    laboratory: Optional[str] = None
    room: Optional[str] = None


class InstrumentPropertiesSchema(BaseModel):
    shortName: Optional[str] = None
    """
    The short name of the instrument, e.g. jupiter, pdac_com5
    """
    summary: Optional[str] = None
    """
    Instrument's short description.
    """
    vendor: Optional[str] = None
    """
    Manufacturer of the instrument, e.g. Asylum Research
    """
    model: Optional[str] = None
    """
    Model name, e.g. Jupiter
    """
    serialNumber: Optional[str] = None
    """
    Vendor serial number identifying this particular unit.
    """
    firmware: Optional[str] = None
    """
    Controller or acquisition-software version, the analogue of an application version, e.g. 19.34.88
    """
    techniques: Optional[List[Union[CharacterizationTechniqueCategorySchema, SynthesisTechniqueCategorySchema]]] = None
    """
    Techniques this instrument can perform.
    """
    components: Optional[List[InstrumentComponentSchema]] = None
    """
    Parts of the instrument that matter to a result, e.g. the probe a scan was taken with or the source a film was grown from.
    """
    controlSoftware: Optional[List[ApplicationSchema]] = None
    """
    Software driving the instrument, reusing the application entity rather than restating a name and a version.
    """
    location: Optional[Location] = None
    """
    Where the instrument is, which for a multi-institution project is part of the provenance.
    """
