repos:
  - repo: https://github.com/Exabyte-io/pre-commit-hooks
    rev: 2023.6.13
    hooks:
      - id: ruff
        exclude: ^src/py/mat3ra/esse/data
      - id: black
        exclude: ^src/py/mat3ra/esse/data
  - repo: local
    hooks:
      - id: generate-python-modules
        name: Regenerate data modules classes from static assets
        # yamllint disable rule:line-length
        entry: |
          bash -c 'datamodel-codegen --input ./dist/js/schema/ --input-file-type jsonschema --output ./dist/py --class-name ESSE --output-model-type pydantic_v2.BaseModel --use-field-description --use-double-quotes --enable-version-header --disable-timestamp --use-title-as-nam'
        language: system
        pass_filenames: false
        verbose: true
