# generated by datamodel-codegen:
#   filename:  sample/metadata.json
#   version:   0.28.5

from __future__ import annotations

from typing import Any, Dict, Optional

from pydantic import BaseModel


class SampleMetadataSchema(BaseModel):
    metadata: Optional[Dict[str, Any]] = {}
