# generated by datamodel-codegen:
#   filename:  context_providers_directory/boundary_conditions_data_provider.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


class Type(Enum):
    pbc = "pbc"
    bc1 = "bc1"
    bc2 = "bc2"
    bc3 = "bc3"


class BoundaryConditionsProviderSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Optional[Type] = "pbc"
    """
    If assume_isolated = 'esm', determines the boundary conditions used for either side of the slab.
    """
    offset: Optional[float] = None
    electric_field: Optional[float] = Field(None, alias="electricField", title="Electric Field (eV/A)")
    target_fermi_energy: Optional[float] = Field(None, alias="targetFermiEnergy", title="Target Fermi Energy (eV)")
