# generated by datamodel-codegen:
#   filename:  context_providers_directory/hubbard_v_context_provider.json
#   version:   0.28.5

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, ConfigDict, Field, RootModel


class HubbardVProviderSchemaItem(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    atomic_species: Optional[str] = Field(None, alias="atomicSpecies", title="Species 1")
    site_index: Optional[int] = Field(None, alias="siteIndex", title="Site no 1")
    atomic_orbital: Optional[str] = Field(None, alias="atomicOrbital", title="Orbital 1")
    atomic_species2: Optional[str] = Field(None, alias="atomicSpecies2", title="Species 2")
    site_index2: Optional[int] = Field(None, alias="siteIndex2", title="Site no 2")
    atomic_orbital2: Optional[str] = Field(None, alias="atomicOrbital2", title="Orbital 2")
    hubbard_v_value: Optional[float] = Field(None, alias="hubbardVValue", title="V (eV)")


class HubbardVProviderSchema(RootModel[List[HubbardVProviderSchemaItem]]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: List[HubbardVProviderSchemaItem] = Field(..., min_length=1, title="Hubbard V Provider Schema")
    """
    Hubbard V parameters for DFT+U+V calculation.
    """
