# generated by datamodel-codegen:
#   filename:  context_providers_directory/points_path_data_provider_rendering.json
#   version:   0.28.5

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field, RootModel


class PointsPathDataProviderRenderingSchemaItem(BaseModel):
    point: str
    steps: float
    coordinates: List[float]


class PointsPathDataProviderRenderingSchema(RootModel[List[PointsPathDataProviderRenderingSchemaItem]]):
    root: List[PointsPathDataProviderRenderingSchemaItem] = Field(
        ..., min_length=1, title="Points Path Data Provider Rendering Schema"
    )
    """
    Path in reciprocal space including derived Cartesian/fractional coordinates for template rendering. Not persisted on the context item.
    """
