# generated by datamodel-codegen:
#   filename:  workflow/unit/input/_map_input.json
#   version:   0.28.5

from __future__ import annotations

from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel, ConfigDict, Field


class UnitMapInputSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    target: Optional[str] = None
    values: Optional[List[Union[float, str, Dict[str, Any]]]] = None
    use_values: Optional[bool] = Field(None, alias="useValues")
    scope: Optional[str] = None
    name: Optional[str] = None
