# generated by datamodel-codegen:
#   filename:  workflow/unit/input/_map_input/values.json
#   version:   0.28.5

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict


class UnitValuesSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    values: Optional[str] = None
