# generated by datamodel-codegen:
#   filename:  compute/nodes/base.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class Type(Enum):
    cluster = "cluster"
    gold = "gold"
    login = "login"


class DiskSpaceItem(BaseModel):
    name: Optional[str] = None
    size: Optional[float] = None
    avail: Optional[float] = None


class CloudNode(BaseModel):
    hostname: str = Field(..., title="Hostname")
    """
    Fully qualified domain name of the node
    """
    alias: Optional[str] = Field(None, title="Alias")
    """
    Human-readable display name for the node
    """
    timestamp: Optional[float] = None
    """
    Unix timestamp of last heartbeat from the node
    """
    type: Optional[Type] = None
    """
    Type of cloud node: cluster (compute), gold (billing), or login (SSH access)
    """
    isDefault: Optional[bool] = None
    """
    Whether this is the default node for its type
    """
    diskSpace: Optional[List[DiskSpaceItem]] = None
    """
    Disk space information for mounted filesystems
    """
