# generated by datamodel-codegen:
#   filename:  job/base.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, ConfigDict, Field, conint


class Status(Enum):
    pre_submission = "pre-submission"
    queued = "queued"
    submitted = "submitted"
    active = "active"
    finished = "finished"
    terminate_queued = "terminate-queued"
    terminated = "terminated"
    error = "error"
    deleted = "deleted"
    timeout = "timeout"


class Queue(Enum):
    d = "D"
    or_ = "OR"
    of = "OF"
    o_fplus = "OFplus"
    sr = "SR"
    sf = "SF"
    s_fplus = "SFplus"
    gpof = "GPOF"
    gp2_of = "GP2OF"
    gp4_of = "GP4OF"
    gpsf = "GPSF"
    gp2_sf = "GP2SF"
    gp4_sf = "GP4SF"
    or4 = "OR4"
    or8 = "OR8"
    or16 = "OR16"
    sr4 = "SR4"
    sr8 = "SR8"
    sr16 = "SR16"
    gof = "GOF"
    g4_of = "G4OF"
    g8_of = "G8OF"
    gsf = "GSF"
    g4_sf = "G4SF"
    g8_sf = "G8SF"


class TimeLimitType(Enum):
    per_single_attempt = "per single attempt"
    compound = "compound"


class QuantumEspressoArgumentsSchema(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    nimage: Optional[conint(ge=1, le=100)] = 1
    """
    Processors can be divided into different `images`, each corresponding to a different self-consistent or linear-response calculation, loosely coupled to others.
    """
    npools: Optional[conint(ge=1, le=100)] = 1
    """
    Each image can be subpartitioned into `pools`, each taking care of a group of k-points.
    """
    nband: Optional[conint(ge=1, le=100)] = 1
    """
    Each pool is subpartitioned into `band groups`, each taking care of a group of Kohn-Sham orbitals (also called bands, or wavefunctions).
    """
    ntg: Optional[conint(ge=1, le=100)] = 1
    """
    In order to allow good parallelization of the 3D FFT when the number of processors exceeds the number of FFT planes, FFTs on Kohn-Sham states are redistributed to `task` groups so that each group can process several wavefunctions at the same time.
    """
    ndiag: Optional[conint(ge=1, le=100)] = 1
    """
    A further level of parallelization, independent on PW or k-point parallelization, is the parallelization of subspace diagonalization / iterative orthonormalization. Both operations required the diagonalization of arrays whose dimension is the number of Kohn-Sham states (or a small multiple of it). All such arrays are distributed block-like across the `linear-algebra group`, a subgroup of the pool of processors, organized in a square 2D grid. As a consequence the number of processors in the linear-algebra group is given by n2, where n is an integer; n2 must be smaller than the number of processors in the PW group. The diagonalization is then performed in parallel using standard linear algebra operations.
    """


class Cluster(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    fqdn: Optional[str] = None
    """
    FQDN of the cluster. e.g. master-1-staging.exabyte.io
    """
    jid: Optional[str] = None
    """
    Job's identity in RMS. e.g. 1234.master-1-staging.exabyte.io
    """


class Domain(Enum):
    rupy = "rupy"
    alfred = "alfred"
    celim = "celim"
    webapp = "webapp"


class Error(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    domain: Optional[Domain] = None
    """
    Domain of the error appearance (internal).
    """
    reason: Optional[str] = None
    """
    Should be a short, unique, machine-readable error code string. e.g. FileNotFound
    """
    message: Optional[str] = None
    """
    Human-readable error message. e.g. 'File Not Found: /home/demo/data/project1/job-123/job-config.json'
    """
    traceback: Optional[str] = None
    """
    Full machine-readable error traceback. e.g. FileNotFound
    """


class ComputeArgumentsSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    queue: Queue
    """
    Name of the submission queues: https://docs.mat3ra.com/infrastructure/resource/queues/. Below enums are for Azure, then AWS circa 2022-08, hence the duplication.
    """
    nodes: int
    """
    number of nodes used for the job inside the RMS.
    """
    ppn: int
    """
    number of CPUs used for the job inside the RMS.
    """
    time_limit: str = Field(..., alias="timeLimit")
    """
    Wallclock time limit for computing a job. Clock format: 'hh:mm:ss'
    """
    time_limit_type: Optional[TimeLimitType] = Field("per single attempt", alias="timeLimitType")
    """
    Convention to use when reasoning about time limits
    """
    is_restartable: Optional[bool] = Field(True, alias="isRestartable")
    """
    Job is allowed to restart on termination.
    """
    notify: Optional[str] = None
    """
    Email notification for the job: n - never, a - job aborted, b - job begins, e - job ends. Last three could be combined.
    """
    email: Optional[str] = None
    """
    Email address to notify about job execution.
    """
    max_cpu: Optional[int] = Field(None, alias="maxCPU")
    """
    Maximum CPU count per node. This parameter is used to let backend job submission infrastructure know that this job is to be charged for the maximum CPU per node instead of the actual ppn. For premium/fast queues where resources are provisioned on-demand and exclusively per user.
    """
    arguments: Optional[QuantumEspressoArgumentsSchema] = Field({}, title="quantum espresso arguments schema")
    """
    Optional arguments specific to using application - VASP, Quantum Espresso, etc. Specified elsewhere
    """
    cluster: Optional[Cluster] = None
    """
    Cluster where the job is executed. Optional on create. Required on job submission.
    """
    errors: Optional[List[Error]] = None
    """
    Computation error. Optional. Appears only if something happens on jobs execution.
    """
    exclude_files_pattern: Optional[str] = Field(None, alias="excludeFilesPattern")
    """
    A Python compatible regex to exclude files from upload. e.g. ^.*.txt& excludes all files with .txt suffix
    """


class EntityReferenceSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    field_id: str = Field(..., alias="_id")
    """
    entity identity
    """
    cls: Optional[str] = None
    """
    entity class
    """
    slug: Optional[str] = None
    """
    entity slug
    """


class WorkflowScopeSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    global_: Dict[str, Any] = Field(..., alias="global")
    local: Dict[str, Any]


class ScopeTrackItem(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    repetition: Optional[float] = None
    scope: Optional[WorkflowScopeSchema] = Field(None, title="workflow scope schema")


class JobBaseSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    rms_id: Optional[str] = Field(None, alias="rmsId")
    """
    Identity used to track jobs originated from command-line
    """
    status: Status
    """
    job status
    """
    start_time: Optional[str] = Field(None, alias="startTime")
    """
    Approximate start time of the job. e.g. within 10 min
    """
    work_dir: Optional[str] = Field(None, alias="workDir")
    """
    The path to the working directory of this job, when the job originates from command-line
    """
    compute: ComputeArgumentsSchema = Field(..., title="compute arguments schema")
    """
    Custom keywords prefixed with validate correspond to custom validation methods implemented downstream
    """
    field_project: EntityReferenceSchema = Field(..., alias="_project", title="entity reference schema")
    field_material: Optional[EntityReferenceSchema] = Field(None, alias="_material", title="entity reference schema")
    parent: Optional[EntityReferenceSchema] = Field(None, title="entity reference schema")
    runtime_context: Optional[Dict[str, Any]] = Field(None, alias="runtimeContext")
    """
    Context variables that the job will have access to at runtime
    """
    scope_track: Optional[List[ScopeTrackItem]] = Field(None, alias="scopeTrack")
    """
    history of the workflow scope on each update
    """
    field_id: Optional[str] = Field(None, alias="_id")
    """
    entity identity
    """
    slug: Optional[str] = None
    """
    entity slug
    """
    system_name: Optional[str] = Field(None, alias="systemName")
    schema_version: Optional[str] = Field("2022.8.16", alias="schemaVersion")
    """
    entity's schema version. Used to distinct between different schemas.
    """
    name: Optional[str] = None
    """
    entity name
    """
    is_default: Optional[bool] = Field(False, alias="isDefault")
    """
    Identifies that entity is defaultable
    """
    metadata: Optional[Dict[str, Any]] = None
