# generated by datamodel-codegen:
#   filename:  properties_directory/structural/atomic_forces.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import List

from pydantic import BaseModel, ConfigDict, Field


class Name(Enum):
    atomic_forces = "atomic_forces"


class AtomicVectorSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: List[float] = Field(..., max_length=3, min_length=3, title="vector 3d schema")
    """
    value of this entry
    """
    id: int
    """
    integer id of this entry
    """


class Units(Enum):
    e_v_bohr = "eV/bohr"
    e_v_angstrom = "eV/angstrom"
    ry_a_u_ = "Ry/a.u."
    newton = "newton"
    kg_m_s_2 = "kg*m/s^2"
    e_v_a_u_ = "eV/a.u."


class AtomicForcesPropertySchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: Name
    values: List[AtomicVectorSchema] = Field(..., title="atomic vectors schema")
    units: Units
