# generated by datamodel-codegen:
#   filename:  properties_directory/structural/density.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, ConfigDict


class Name(Enum):
    density = "density"


class Units(Enum):
    g_cm_3 = "g/cm^3"


class DensitySchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: Optional[Name] = None
    units: Optional[Units] = None
    value: float
