# generated by datamodel-codegen:
#   filename:  properties_directory/structural/inchi_key.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, ConfigDict


class Name(Enum):
    inchi_key = "inchi_key"


class InChIKeyRepresentationSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: Optional[Name] = None
    value: str
