# generated by datamodel-codegen:
#   filename:  properties_directory/structural/molecular_pattern.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import List, Optional, Union

from pydantic import BaseModel, Field, RootModel


class Name(Enum):
    functional_group = "functional_group"


class ObjectWithId(BaseModel):
    isConnector: Optional[bool] = None
    """
    whether atom connects to atoms outside of functional group.
    """
    id: int
    """
    integer id of this entry
    """


class FunctionalGroupPatternSchema(BaseModel):
    name: Name
    atoms: Optional[List[ObjectWithId]] = Field(None, title="array of ids")
    """
    array of objects containing integer id each
    """
    SMARTS: Optional[str] = None
    """
    SMARTS string for classification of FG; https://en.wikipedia.org/wiki/SMILES_arbitrary_target_specification
    """


<<<<<<< HEAD
class Name601(Enum):
=======
class Name517(Enum):
>>>>>>> 8664c20e94ca9d52fce78f266358a60c7d88fb37
    ring = "ring"


class RingPatternSchema(BaseModel):
<<<<<<< HEAD
    name: Name601
=======
    name: Optional[Name517] = None
>>>>>>> 8664c20e94ca9d52fce78f266358a60c7d88fb37
    atoms: Optional[List[ObjectWithId]] = Field(None, title="array of ids")
    """
    array of objects containing integer id each
    """
    isAromatic: Optional[bool] = None


<<<<<<< HEAD
class Name602(Enum):
=======
class Name518(Enum):
>>>>>>> 8664c20e94ca9d52fce78f266358a60c7d88fb37
    special_bond = "special_bond"


class SpecialBondPatternSchema(BaseModel):
<<<<<<< HEAD
    name: Name602
=======
    name: Optional[Name518] = None
>>>>>>> 8664c20e94ca9d52fce78f266358a60c7d88fb37
    atoms: Optional[List[ObjectWithId]] = Field(None, title="array of ids")
    """
    array of objects containing integer id each
    """


class MolecularPatternSchema(
    RootModel[List[Union[FunctionalGroupPatternSchema, RingPatternSchema, SpecialBondPatternSchema]]]
):
    root: List[Union[FunctionalGroupPatternSchema, RingPatternSchema, SpecialBondPatternSchema]] = Field(
        ..., title="molecular pattern schema"
    )
