# generated by datamodel-codegen:
#   filename:  element.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import List, Optional, Union

from pydantic import BaseModel, ConfigDict


class Symbol(Enum):
    h = "H"
    he = "He"
    li = "Li"
    be = "Be"
    b = "B"
    c = "C"
    n = "N"
    o = "O"
    f = "F"
    ne = "Ne"
    na = "Na"
    mg = "Mg"
    al = "Al"
    si = "Si"
    p = "P"
    s = "S"
    cl = "Cl"
    ar = "Ar"
    k = "K"
    ca = "Ca"
    sc = "Sc"
    ti = "Ti"
    v = "V"
    cr = "Cr"
    mn = "Mn"
    fe = "Fe"
    co = "Co"
    ni = "Ni"
    cu = "Cu"
    zn = "Zn"
    ga = "Ga"
    ge = "Ge"
    as_ = "As"
    se = "Se"
    br = "Br"
    kr = "Kr"
    rb = "Rb"
    sr = "Sr"
    y = "Y"
    zr = "Zr"
    nb = "Nb"
    mo = "Mo"
    tc = "Tc"
    ru = "Ru"
    rh = "Rh"
    pd = "Pd"
    ag = "Ag"
    cd = "Cd"
    in_ = "In"
    sn = "Sn"
    sb = "Sb"
    te = "Te"
    i = "I"
    xe = "Xe"
    cs = "Cs"
    ba = "Ba"
    la = "La"
    ce = "Ce"
    pr = "Pr"
    nd = "Nd"
    pm = "Pm"
    sm = "Sm"
    eu = "Eu"
    gd = "Gd"
    tb = "Tb"
    dy = "Dy"
    ho = "Ho"
    er = "Er"
    tm = "Tm"
    yb = "Yb"
    lu = "Lu"
    hf = "Hf"
    ta = "Ta"
    w = "W"
    re = "Re"
    os = "Os"
    ir = "Ir"
    pt = "Pt"
    au = "Au"
    hg = "Hg"
    tl = "Tl"
    pb = "Pb"
    bi = "Bi"
    po = "Po"
    at = "At"
    rn = "Rn"
    fr = "Fr"
    ra = "Ra"
    ac = "Ac"
    th = "Th"
    pa = "Pa"
    u = "U"
    np = "Np"
    pu = "Pu"
    am = "Am"
    cm = "Cm"
    bk = "Bk"
    cf = "Cf"
    es = "Es"
    fm = "Fm"
    md = "Md"
    no = "No"
    lr = "Lr"
    rf = "Rf"
    db = "Db"
    sg = "Sg"
    bh = "Bh"
    hs = "Hs"
    mt = "Mt"
    ds = "Ds"
    rg = "Rg"
    cn = "Cn"
    nh = "Nh"
    fl = "Fl"
    mc = "Mc"
    lv = "Lv"
    ts = "Ts"
    og = "Og"


class Name(Enum):
    atomic_radius = "atomic_radius"


class Units(Enum):
    km = "km"
    m = "m"
    cm = "cm"
    mm = "mm"
    um = "um"
    nm = "nm"
    angstrom = "angstrom"
    a_u_ = "a.u."
    bohr = "bohr"
    pm = "pm"


class AtomicRadius(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: Name
    units: Optional[Units] = None
    value: float


class Name465(Enum):
    electronegativity = "electronegativity"


class Electronegativity(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: Name465
    value: float


class Name466(Enum):
    ionization_potential = "ionization_potential"


class Units184(Enum):
    k_j_mol = "kJ/mol"
    e_v = "eV"
    j_mol = "J/mol"
    hartree = "hartree"
    cm_1 = "cm-1"
    ry = "Ry"
    e_v_atom = "eV/atom"


class IonizationPotentialElementalPropertySchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: Name466
    units: Units184
    value: float


class ElementSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    symbol: Optional[Symbol] = None
    properties: Optional[List[Union[AtomicRadius, Electronegativity, IonizationPotentialElementalPropertySchema]]] = (
        None
    )
    """
    list of elemental properties
    """
