# generated by datamodel-codegen:
#   filename:  project.json
#   version:   0.28.5

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, ConfigDict, Field


class ClusterBasedChargeRate(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    rate: Optional[float] = None
    timestamp: Optional[float] = None
    hostname: Optional[str] = None


class ProjectSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    gid: Optional[float] = None
    """
    project GID
    """
    cluster_based_charge_rates: Optional[List[ClusterBasedChargeRate]] = Field(None, alias="clusterBasedChargeRates")
    """
    charge rates info for project
    """
    is_external: Optional[bool] = Field(False, alias="isExternal")
    field_id: Optional[str] = Field(None, alias="_id")
    """
    entity identity
    """
    slug: Optional[str] = None
    """
    entity slug
    """
    system_name: Optional[str] = Field(None, alias="systemName")
    schema_version: Optional[str] = Field("2022.8.16", alias="schemaVersion")
    """
    entity's schema version. Used to distinct between different schemas.
    """
    name: Optional[str] = None
    """
    entity name
    """
    is_default: Optional[bool] = Field(False, alias="isDefault")
    """
    Identifies that entity is defaultable
    """
    metadata: Optional[Dict[str, Any]] = None
