# generated by datamodel-codegen:
#   filename:  workflow/unit/mixins/error.json
#   version:   0.28.5

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel


class ErrorUnitMixinSchema(BaseModel):
    type: Literal["error"] = "error"
    reason: str
    """
    JSON string with validation/hydration details: { error, json, schema }
    """
