# generated by datamodel-codegen:
#   filename:  workflow/unit/mixins/error.json
#   version:   0.28.5

from __future__ import annotations

from typing import Any, Dict, Literal

from pydantic import BaseModel


class ErrorUnitMixinSchema(BaseModel):
    type: Literal["error"] = "error"
    originalUnit: Dict[str, Any]
    """
    Full pre-conversion unit payload preserved for debugging
    """
    reason: str
    """
    Why conversion happened (validation/hydration message)
    """
