# generated by datamodel-codegen:
#   filename:  workflow/unit/mixins/subworkflow.json
#   version:   0.28.5

from __future__ import annotations

from typing import Literal, Optional

from pydantic import BaseModel


class SubworkflowUnitMixinSchema(BaseModel):
    type: Literal["subworkflow"] = "subworkflow"
    name: Optional[str] = "New Subworkflow"
