# generated by datamodel-codegen:
#   filename:  workflow/unit/context/item/grid.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import List, Optional, Union

from pydantic import BaseModel, Field


class Name(Enum):
    kgrid = "kgrid"
    qgrid = "qgrid"
    igrid = "igrid"


class GridMetricType(Enum):
    KPPRA = "KPPRA"
    spacing = "spacing"


class PointsGridDataProviderSchema(BaseModel):
    dimensions: Union[List[float], List[str]]
    shifts: Optional[List[float]] = Field(None, max_length=3, min_length=3)
    reciprocalVectorRatios: Optional[List[float]] = Field(None, max_length=3, min_length=3)
    gridMetricType: GridMetricType
    gridMetricValue: float
    preferGridMetric: Optional[bool] = None


class ExtraDataWithMaterialHashSchema(BaseModel):
    materialHash: Optional[str] = None
    """
    UI only property used to track material change for re-render
    """


class GridContextItemSchema(BaseModel):
    name: Name
    data: PointsGridDataProviderSchema = Field(..., title="Points Grid Data Provider Schema")
    """
    3D grid with shifts for k-point or q-point sampling.
    """
    extraData: ExtraDataWithMaterialHashSchema = Field(..., title="extraData with materialHash schema")
    isEdited: bool
