# generated by datamodel-codegen:
#   filename:  workflow/unit/context/item/nonCollinearMagnetization.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import List, Literal, Optional

from pydantic import BaseModel, Field


class StartingMagnetizationItem(BaseModel):
    index: Optional[int] = Field(None, title="Index")
    atomicSpecies: Optional[str] = Field(None, title="Atomic species")
    value: Optional[float] = Field(None, title="Starting magnetization")


class SpinAngle(BaseModel):
    index: Optional[int] = Field(None, title="Index")
    atomicSpecies: Optional[str] = Field(None, title="Atomic species")
    angle1: Optional[float] = Field(None, title="Angle1 (deg)")
    angle2: Optional[float] = Field(None, title="Angle2 (deg)")


class ConstrainType(Enum):
    none = "none"
    total = "total"
    atomic = "atomic"
    total_direction = "total direction"
    atomic_direction = "atomic direction"


class ConstrainedMagnetization(BaseModel):
    constrainType: Optional[ConstrainType] = Field(None, title="Constrain type")
    lambda_: Optional[float] = Field(None, alias="lambda", title="lambda")


class FixedMagnetization(BaseModel):
    x: Optional[float] = Field(None, title="X-component")
    y: Optional[float] = Field(None, title="Y-component")
    z: Optional[float] = Field(None, title="Z-component")


class NonCollinearMagnetizationContextProviderSchema(BaseModel):
    isExistingChargeDensity: Optional[bool] = Field(None, title="Use existing charge density")
    isStartingMagnetization: Optional[bool] = Field(None, title="Set starting magnetization")
    startingMagnetization: Optional[List[StartingMagnetizationItem]] = None
    isArbitrarySpinAngle: Optional[bool] = Field(None, title="Set arbitrary spin angle")
    isArbitrarySpinDirection: Optional[bool] = Field(None, title="Set arbitrary spin direction")
    lforcet: Optional[bool] = None
    spinAngles: Optional[List[SpinAngle]] = None
    isConstrainedMagnetization: Optional[bool] = Field(None, title="Set constrained magnetization")
    constrainedMagnetization: Optional[ConstrainedMagnetization] = None
    isFixedMagnetization: Optional[bool] = Field(
        None, title="Set Fixed magnetization (only applicable to constrained magnetization of 'total' type)"
    )
    fixedMagnetization: Optional[FixedMagnetization] = None


class ExtraDataWithMaterialHashSchema(BaseModel):
    materialHash: str


class NonCollinearMagnetizationContextItemSchema(BaseModel):
    name: Literal["nonCollinearMagnetization"]
    data: NonCollinearMagnetizationContextProviderSchema = Field(
        ..., title="Non Collinear Magnetization Context Provider Schema"
    )
    """
    Non-collinear magnetization parameters including starting magnetization, spin angles, and constraints.
    """
    extraData: ExtraDataWithMaterialHashSchema = Field(..., title="extraData with materialHash schema")
    isEdited: bool
