# generated by datamodel-codegen:
#   filename:  context_providers_directory/by_application/nwchem_total_energy_context_provider.json
#   version:   0.28.5

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class NWChemTotalEnergyContextProviderSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    charge: int = Field(..., alias="CHARGE")
    """
    Total charge of the system.
    """
    mult: int = Field(..., alias="MULT")
    """
    Spin multiplicity of the system.
    """
    basis: str = Field(..., alias="BASIS")
    """
    Basis set label used in the calculation (e.g., '6-31G').
    """
    nat: int = Field(..., alias="NAT")
    """
    Number of atoms in the system.
    """
    ntyp: int = Field(..., alias="NTYP")
    """
    Number of unique atomic species in the system.
    """
    atomic_positions: str = Field(..., alias="ATOMIC_POSITIONS")
    """
    Formatted text block with atomic positions including constraints.
    """
    atomic_positions_without_constraints: str = Field(..., alias="ATOMIC_POSITIONS_WITHOUT_CONSTRAINTS")
    """
    Formatted text block with atomic positions without constraints.
    """
    atomic_species: str = Field(..., alias="ATOMIC_SPECIES")
    """
    Formatted text block for atomic species, including element symbols and masses.
    """
    functional: str = Field(..., alias="FUNCTIONAL")
    """
    Exchange-correlation functional identifier (e.g., 'B3LYP').
    """
    cartesian: bool = Field(..., alias="CARTESIAN")
    """
    Whether atomic positions are expressed in cartesian coordinates.
    """
