# generated by datamodel-codegen:
#   filename:  methods_directory/legacy/regression.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import Any, List, Optional, Union

from pydantic import BaseModel, ConfigDict, Field


class Type(Enum):
    linear = "linear"
    kernel_ridge = "kernel_ridge"


class Subtype(Enum):
    least_squares = "least_squares"
    ridge = "ridge"


class RegressionPrecisionPerPropertySchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: Optional[str] = None
    """
    property name in 'flattened' format
    """
    training_error: float = Field(..., alias="trainingError")
    """
    training error of the estimator
    """
    score: Optional[float] = None
    """
    prediction score of the estimator. Eg: r2_score
    """


class RegressionPrecision(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    per_property: Optional[List[RegressionPrecisionPerPropertySchema]] = Field(None, alias="perProperty")


class PerFeaturePropertyUsedForTrainingTheMLMethodModelParametersSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    coefficient: Optional[float] = None
    """
    coefficient in linear regression
    """
    name: str
    """
    feature name
    """
    importance: Optional[float] = None
    """
    pvalue: https://en.wikipedia.org/wiki/P-value
    """


class LinearRegressionParametersSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    intercept: float
    """
    intercept (shift) from the linear or non-linear fit of data points
    """
    per_feature: List[PerFeaturePropertyUsedForTrainingTheMLMethodModelParametersSchema] = Field(
        ..., alias="perFeature"
    )
    """
    per-feature (property used for training the ML method/model) parameters
    """


class KernelRidgeRegressionParametersSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    x_fit: List = Field(..., alias="xFit")
    """
    training data
    """
    dual_coefficients: List = Field(..., alias="dualCoefficients")
    """
    dual coefficients
    """
    per_feature: List[PerFeaturePropertyUsedForTrainingTheMLMethodModelParametersSchema] = Field(
        ..., alias="perFeature"
    )
    """
    per-feature (property used for training the ML method/model) parameters
    """


class DataSet(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    exabyte_ids: List[str] = Field(..., alias="exabyteIds")
    """
    array of exabyteIds for materials in dataset
    """
    extra: Optional[Any] = None
    """
    holder for any extra information, eg. coming from user-uploaded CSV file
    """


class RegressionData(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    per_property: Optional[List[Union[LinearRegressionParametersSchema, KernelRidgeRegressionParametersSchema]]] = (
        Field(None, alias="perProperty")
    )
    data_set: Optional[DataSet] = Field(None, alias="dataSet")
    """
    dataset for ml
    """


class LegacyMethodRegression(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Type
    """
    general type of this method, eg. `pseudopotential`
    """
    subtype: Subtype
    """
    general subtype of this method, eg. `ultra-soft`
    """
    precision: RegressionPrecision = Field(..., title="regression precision")
    """
    Object showing the actual possible precision based on theory and implementation
    """
    data: RegressionData = Field(..., title="regression data")
    """
    additional data specific to method, eg. array of pseudopotentials
    """
