# generated by datamodel-codegen:
#   filename:  techniques_category/experimental/characterization.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import Optional, Union

from pydantic import BaseModel, Field


class SlugifiedEntry(BaseModel):
    name: str
    """
    descriptive human-readable name of entry
    """
    slug: str
    """
    machine-readable identifier
    """


class SlugifiedEntryOrSlug(Enum):
    characterization = "characterization"


class SlugifiedEntryOrSlug75(Enum):
    microscopy = "microscopy"
    spectroscopy = "spectroscopy"
    diffraction = "diffraction"
    electrical = "electrical"
    optical = "optical"


class SlugifiedEntryOrSlug76(Enum):
    scanning_probe_microscopy = "scanning_probe_microscopy"
    electron_microscopy = "electron_microscopy"
    x_ray = "x_ray"
    transport = "transport"
    dielectric = "dielectric"
    ultraviolet_visible_near_infrared = "ultraviolet_visible_near_infrared"


class SlugifiedEntryOrSlug77(Enum):
    atomic_force_microscopy = "atomic_force_microscopy"
    scanning_tunneling_microscopy = "scanning_tunneling_microscopy"
    scanning_tunneling_spectroscopy = "scanning_tunneling_spectroscopy"
    piezoresponse_force_microscopy = "piezoresponse_force_microscopy"
    kelvin_probe_force_microscopy = "kelvin_probe_force_microscopy"
    conductive_atomic_force_microscopy = "conductive_atomic_force_microscopy"
    magnetic_force_microscopy = "magnetic_force_microscopy"


class SlugifiedEntryOrSlug78(Enum):
    experimental = "experimental"


class CharacterizationTechniqueCategorySchema(BaseModel):
    tier2: Optional[Union[SlugifiedEntry, SlugifiedEntryOrSlug]] = Field(None, title="slugified entry or slug")
    """
    contains either object with slugified entry or slug only as a string
    """
    tier3: Optional[Union[SlugifiedEntry, SlugifiedEntryOrSlug75]] = Field(None, title="slugified entry or slug")
    """
    contains either object with slugified entry or slug only as a string
    """
    type: Optional[Union[SlugifiedEntry, SlugifiedEntryOrSlug76]] = Field(None, title="slugified entry or slug")
    """
    contains either object with slugified entry or slug only as a string
    """
    subtype: Optional[Union[SlugifiedEntry, SlugifiedEntryOrSlug77]] = Field(None, title="slugified entry or slug")
    """
    contains either object with slugified entry or slug only as a string
    """
    tier1: Optional[Union[SlugifiedEntry, SlugifiedEntryOrSlug78]] = Field(None, title="slugified entry or slug")
    """
    contains either object with slugified entry or slug only as a string
    """
