# generated by datamodel-codegen:
#   filename:  techniques_category/experimental/synthesis.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import Optional, Union

from pydantic import BaseModel, Field


class SlugifiedEntry(BaseModel):
    name: str
    """
    descriptive human-readable name of entry
    """
    slug: str
    """
    machine-readable identifier
    """


class SlugifiedEntryOrSlug(Enum):
    synthesis = "synthesis"


class SlugifiedEntryOrSlug407(Enum):
    vapor_deposition = "vapor_deposition"
    solution_processing = "solution_processing"
    bulk_growth = "bulk_growth"
    post_processing = "post_processing"


class SlugifiedEntryOrSlug408(Enum):
    physical_vapor_deposition = "physical_vapor_deposition"
    chemical_vapor_deposition = "chemical_vapor_deposition"
    annealing = "annealing"


class SlugifiedEntryOrSlug409(Enum):
    pulsed_laser_deposition = "pulsed_laser_deposition"
    sputtering = "sputtering"
    molecular_beam_epitaxy = "molecular_beam_epitaxy"
    thermal_evaporation = "thermal_evaporation"
    electron_beam_evaporation = "electron_beam_evaporation"
    atomic_layer_deposition = "atomic_layer_deposition"
    plasma_enhanced_atomic_layer_deposition = "plasma_enhanced_atomic_layer_deposition"
    thermal_chemical_vapor_deposition = "thermal_chemical_vapor_deposition"
    metalorganic_chemical_vapor_deposition = "metalorganic_chemical_vapor_deposition"
    plasma_enhanced_chemical_vapor_deposition = "plasma_enhanced_chemical_vapor_deposition"


class SlugifiedEntryOrSlug410(Enum):
    experimental = "experimental"


class SynthesisTechniqueCategorySchema(BaseModel):
    tier2: Optional[Union[SlugifiedEntry, SlugifiedEntryOrSlug]] = Field(None, title="slugified entry or slug")
    """
    contains either object with slugified entry or slug only as a string
    """
    tier3: Optional[Union[SlugifiedEntry, SlugifiedEntryOrSlug407]] = Field(None, title="slugified entry or slug")
    """
    contains either object with slugified entry or slug only as a string
    """
    type: Optional[Union[SlugifiedEntry, SlugifiedEntryOrSlug408]] = Field(None, title="slugified entry or slug")
    """
    contains either object with slugified entry or slug only as a string
    """
    subtype: Optional[Union[SlugifiedEntry, SlugifiedEntryOrSlug409]] = Field(None, title="slugified entry or slug")
    """
    contains either object with slugified entry or slug only as a string
    """
    tier1: Optional[Union[SlugifiedEntry, SlugifiedEntryOrSlug410]] = Field(None, title="slugified entry or slug")
    """
    contains either object with slugified entry or slug only as a string
    """
