# generated by datamodel-codegen:
#   filename:  methods_directory/mathematical/regression/data.json
#   version:   0.28.5

from __future__ import annotations

from typing import Any, List, Optional, Union

from pydantic import BaseModel, ConfigDict, Field


class PerFeaturePropertyUsedForTrainingTheMLMethodModelParametersSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    coefficient: Optional[float] = None
    """
    coefficient in linear regression
    """
    name: str
    """
    feature name
    """
    importance: Optional[float] = None
    """
    pvalue: https://en.wikipedia.org/wiki/P-value
    """


class LinearRegressionParametersSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    intercept: float
    """
    intercept (shift) from the linear or non-linear fit of data points
    """
    per_feature: List[PerFeaturePropertyUsedForTrainingTheMLMethodModelParametersSchema] = Field(
        ..., alias="perFeature"
    )
    """
    per-feature (property used for training the ML method/model) parameters
    """


class KernelRidgeRegressionParametersSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    x_fit: List = Field(..., alias="xFit")
    """
    training data
    """
    dual_coefficients: List = Field(..., alias="dualCoefficients")
    """
    dual coefficients
    """
    per_feature: List[PerFeaturePropertyUsedForTrainingTheMLMethodModelParametersSchema] = Field(
        ..., alias="perFeature"
    )
    """
    per-feature (property used for training the ML method/model) parameters
    """


class DataSet(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    exabyte_ids: List[str] = Field(..., alias="exabyteIds")
    """
    array of exabyteIds for materials in dataset
    """
    extra: Optional[Any] = None
    """
    holder for any extra information, eg. coming from user-uploaded CSV file
    """


class RegressionData(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    per_property: Optional[List[Union[LinearRegressionParametersSchema, KernelRidgeRegressionParametersSchema]]] = (
        Field(None, alias="perProperty")
    )
    data_set: Optional[DataSet] = Field(None, alias="dataSet")
    """
    dataset for ml
    """
