# generated by datamodel-codegen:
#   filename:  workflow/unit/runtime/_runtime_item_full_object.json
#   version:   0.28.5

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class FullResultSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: str
    """
    The name of this item. e.g. 'my_custom_property. <OTHER FIELDS TO BE ADDED>'
    """
