# generated by datamodel-codegen:
#   filename:  models_directory/lda.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel, ConfigDict, Field


class SlugifiedEntry(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: str
    """
    descriptive human-readable name of entry
    """
    slug: str
    """
    machine-readable identifier
    """


class SlugifiedEntryOrSlug(Enum):
    lda = "lda"


class SlugifiedEntryOrSlug129(Enum):
    ksdft = "ksdft"


class SlugifiedEntryOrSlug130(Enum):
    dft = "dft"


class SlugifiedEntryOrSlug131(Enum):
    qm = "qm"


class SlugifiedEntryOrSlug132(Enum):
    pb = "pb"


class DFTLDAFunctionalCategorySchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    subtype: Optional[Union[SlugifiedEntry, SlugifiedEntryOrSlug]] = Field(None, title="slugified entry or slug")
    """
    contains either object with slugified entry or slug only as a string
    """
    type: Optional[Union[SlugifiedEntry, SlugifiedEntryOrSlug129]] = Field(None, title="slugified entry or slug")
    """
    contains either object with slugified entry or slug only as a string
    """
    tier3: Optional[Union[SlugifiedEntry, SlugifiedEntryOrSlug130]] = Field(None, title="slugified entry or slug")
    """
    contains either object with slugified entry or slug only as a string
    """
    tier2: Optional[Union[SlugifiedEntry, SlugifiedEntryOrSlug131]] = Field(None, title="slugified entry or slug")
    """
    contains either object with slugified entry or slug only as a string
    """
    tier1: Optional[Union[SlugifiedEntry, SlugifiedEntryOrSlug132]] = Field(None, title="slugified entry or slug")
    """
    contains either object with slugified entry or slug only as a string
    """


class Functional(Enum):
    pz = "pz"


class SpinOrbitCouplingMixin(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    functional: Optional[Functional] = None
    spin_orbit_coupling: Optional[bool] = Field(None, alias="spinOrbitCoupling")


class DispersionCorrection(Enum):
    dft_d2 = "dft-d2"
    dft_d3 = "dft-d3"
    xdm = "xdm"
    ts = "ts"


class DispersionCorrectionMixin(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    functional: Optional[Functional] = None
    dispersion_correction: Optional[DispersionCorrection] = Field(None, alias="dispersionCorrection")


class SpinPolarization(Enum):
    collinear = "collinear"
    non_collinear = "non-collinear"


class SpinPolarizationMixin(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    functional: Optional[Functional] = None
    spin_polarization: Optional[SpinPolarization] = Field(None, alias="spinPolarization")


class HubbardType(Enum):
    u = "u"


class HubbardModelMixin(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    functional: Optional[Functional] = None
    hubbard_type: Optional[HubbardType] = Field(None, alias="hubbardType")


class Type(Enum):
    literature = "literature"


class PagesSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    start: str
    end: Optional[str] = None


class ExperimentAuthorSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    first: str
    middle: Optional[str] = None
    last: str
    affiliation: Optional[str] = None


class LiteratureReferenceSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Optional[Type] = None
    doi: Optional[str] = None
    """
    Digital Object Identifier of the reference.
    """
    isbn: Optional[str] = None
    """
    International Standard Book Number of the reference.
    """
    issn: Optional[str] = None
    """
    International Standard Serial Number of the reference.
    """
    url: Optional[str] = None
    """
    Internet address of the reference.
    """
    title: Optional[str] = None
    """
    Title of the work.
    """
    publisher: Optional[str] = None
    """
    Publisher of the work.
    """
    journal: Optional[str] = None
    """
    Journal in which the work appeared.
    """
    volume: Optional[str] = None
    """
    Volume of the series in which the work appeared.
    """
    year: Optional[str] = None
    """
    Year in which the reference was published.
    """
    issue: Optional[str] = None
    """
    Issue of the collection in which the work appeared.
    """
    pages: Optional[PagesSchema] = Field(None, title="pages schema")
    """
    Start and end pages of the work.
    """
    authors: Optional[List[ExperimentAuthorSchema]] = None
    """
    List of authors of the work.
    """
    editors: Optional[List[ExperimentAuthorSchema]] = None
    """
    List of editors of the work.
    """
    reference: Optional[List[Dict[str, Any]]] = None
    """
    References cited by the work. Reference objects can nest as deeply as needed. This is useful, for example, when tracking the history of a value referenced in a scholarly article; the top level reference would contain information about where the data was accessed while the nested reference would contain information about where it was originally published.
    """


class ModelLocalDensityApproximation(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    categories: DFTLDAFunctionalCategorySchema = Field(..., title="DFT LDA functional category schema")
    """
    Used to categorize entities such as models and methods
    """
    parameters: Union[SpinOrbitCouplingMixin, DispersionCorrectionMixin, SpinPolarizationMixin, HubbardModelMixin] = (
        Field(..., title="LDA functional mixin")
    )
    """
    Model parameters defined in-place or via model mixins
    """
    reference: Optional[LiteratureReferenceSchema] = Field(None, title="literature reference schema")
    name: Optional[str] = None
    """
    entity name
    """
    path: Optional[str] = Field(None, title="category path schema")
    """
    TODO: Use regex once schema draft version has been updated
    """
    tags: Optional[List[str]] = None
    """
    entity tags
    """
