# generated by datamodel-codegen:
#   filename:  properties_directory/non_scalar/band_gaps.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, ConfigDict, Field


class Name(Enum):
    band_gaps = "band_gaps"


class Type(Enum):
    direct = "direct"
    indirect = "indirect"


class Units(Enum):
    k_j_mol = "kJ/mol"
    e_v = "eV"
    j_mol = "J/mol"
    hartree = "hartree"
    cm_1 = "cm-1"
    ry = "Ry"
    e_v_atom = "eV/atom"


class BandGapSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    kpoint_conduction: Optional[List[float]] = Field(
        None, alias="kpointConduction", max_length=3, min_length=3, title="kpoint schema"
    )
    """
    A k-point is a point in reciprocal space of a crystal.
    """
    kpoint_valence: Optional[List[float]] = Field(
        None, alias="kpointValence", max_length=3, min_length=3, title="kpoint schema"
    )
    """
    A k-point is a point in reciprocal space of a crystal.
    """
    eigenvalue_conduction: Optional[float] = Field(None, alias="eigenvalueConduction")
    """
    eigenvalue at k-point in conduction band
    """
    eigenvalue_valence: Optional[float] = Field(None, alias="eigenvalueValence")
    """
    eigenvalue at k-point in valence band
    """
    spin: Optional[float] = None
    type: Type
    units: Optional[Units] = None
    value: float


class Eigenvalue1(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    spin: Optional[float] = None
    energies: Optional[List] = None
    occupations: Optional[List] = None


class Eigenvalue(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    kpoint: Optional[List[float]] = Field(None, max_length=3, min_length=3, title="kpoint schema")
    """
    A k-point is a point in reciprocal space of a crystal.
    """
    weight: Optional[float] = None
    eigenvalues: Optional[List[Eigenvalue1]] = None


class BandGapsPropertySchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: Name
    values: List[BandGapSchema]
    eigenvalues: Optional[List[Eigenvalue]] = None
