# generated by datamodel-codegen:
#   filename:  properties_directory/non_scalar/file_content.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


class Name(Enum):
    file_content = "file_content"


class Filetype(Enum):
    image = "image"
    text = "text"
    csv = "csv"


class ObjectStorageContainerData(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    container: Optional[str] = Field(None, alias="CONTAINER")
    """
    Object storage container for the file
    """
    name: Optional[str] = Field(None, alias="NAME")
    """
    Name of the file inside the object storage bucket
    """
    provider: Optional[str] = Field(None, alias="PROVIDER")
    """
    Object storage provider
    """
    region: Optional[str] = Field(None, alias="REGION")
    """
    Region for the object container specified in Container
    """
    size: Optional[int] = Field(None, alias="SIZE")
    """
    Size of the file in bytes
    """
    timestamp: Optional[str] = Field(None, alias="TIMESTAMP")
    """
    Unix timestamp showing when the file was last modified
    """


class FileContentPropertySchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: Name
    filetype: Filetype
    """
    What kind of file this is, e.g. image / text
    """
    object_data: ObjectStorageContainerData = Field(..., alias="objectData", title="Object Storage Container Data")
    pathname: Optional[str] = None
    """
    Relative path to the directory that contains the file.
    """
    basename: Optional[str] = None
    """
    Basename of the file
    """
