# generated by datamodel-codegen:
#   filename:  properties_directory/non_scalar/is_relaxed.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field


class Name(Enum):
    is_relaxed = "is_relaxed"


class IsRelaxedPropertySchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: Name
    value: bool
    material_id: str = Field(..., alias="materialId")
    """
    Material's identity
    """
