# generated by datamodel-codegen:
#   filename:  properties_directory/non_scalar/phonon_dispersions.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import List, Optional, Union

from pydantic import BaseModel, ConfigDict, Field


class Label(Enum):
    qpoints = "qpoints"


class Units(Enum):
    crystal = "crystal"
    cartesian = "cartesian"


class AxisSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    label: Label
    """
    label of an axis object
    """
    units: Optional[Units] = "crystal"
    """
    units for an axis
    """


class Label25(Enum):
    frequency = "frequency"


class Units272(Enum):
    cm_1 = "cm-1"
    t_hz = "THz"
    me_v = "meV"


class AxisSchema28(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    label: Label25
    """
    label of an axis object
    """
    units: Optional[Units272] = None
    """
    units for an axis
    """


class Name(Enum):
    phonon_dispersions = "phonon_dispersions"


class PhononBandStructurePropertySchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    x_axis: AxisSchema = Field(..., alias="xAxis", title="axis schema")
    y_axis: AxisSchema28 = Field(..., alias="yAxis", title="axis schema")
    name: Name
    x_data_array: List[Union[float, List[float]]] = Field(..., alias="xDataArray")
    """
    array containing values of x Axis
    """
    y_data_series: List[List[float]] = Field(..., alias="yDataSeries", title="1 dimension data series schema")
