# generated by datamodel-codegen:
#   filename:  properties_directory/non_scalar/total_energy_contributions.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class Name(Enum):
    temperature_entropy = "temperature_entropy"


class ScalarSchema(BaseModel):
    name: Optional[Name] = None
    value: float


class Name791(Enum):
    harris_foulkes = "harris_foulkes"


class ScalarSchema98(BaseModel):
    name: Optional[Name791] = None
    value: float


class Name792(Enum):
    smearing = "smearing"


class ScalarSchema99(BaseModel):
    name: Optional[Name792] = None
    value: float


class Name793(Enum):
    one_electron = "one_electron"


class ScalarSchema100(BaseModel):
    name: Optional[Name793] = None
    value: float


class Name794(Enum):
    hartree = "hartree"


class ScalarSchema101(BaseModel):
    name: Optional[Name794] = None
    value: float


class Name795(Enum):
    exchange = "exchange"


class ScalarSchema102(BaseModel):
    name: Optional[Name795] = None
    value: float


class Name796(Enum):
    exchange_correlation = "exchange_correlation"


class ScalarSchema103(BaseModel):
    name: Optional[Name796] = None
    value: float


class Name797(Enum):
    ewald = "ewald"


class ScalarSchema104(BaseModel):
    name: Optional[Name797] = None
    value: float


class Name798(Enum):
    alphaZ = "alphaZ"


class ScalarSchema105(BaseModel):
    name: Optional[Name798] = None
    value: float


class Name799(Enum):
    atomic_energy = "atomic_energy"


class ScalarSchema106(BaseModel):
    name: Optional[Name799] = None
    value: float


class Name800(Enum):
    eigenvalues = "eigenvalues"


class ScalarSchema107(BaseModel):
    name: Optional[Name800] = None
    value: float


class Name801(Enum):
    PAW_double_counting_correction_2 = "PAW_double-counting_correction_2"


class ScalarSchema108(BaseModel):
    name: Optional[Name801] = None
    value: float


class Name802(Enum):
    PAW_double_counting_correction_3 = "PAW_double-counting_correction_3"


class ScalarSchema109(BaseModel):
    name: Optional[Name802] = None
    value: float


class Name803(Enum):
    hartree_fock = "hartree_fock"


class ScalarSchema110(BaseModel):
    name: Optional[Name803] = None
    value: float


class Name804(Enum):
    total_energy_contributions = "total_energy_contributions"


class Units(Enum):
    kcal_mol = "kcal/mol"
    kJ_mol = "kJ/mol"
    eV = "eV"
    J_mol = "J/mol"
    hartree = "hartree"
    cm_1 = "cm-1"
    Ry = "Ry"
    eV_atom = "eV/atom"


class TotalEnergyContributionsPropertySchema(BaseModel):
    temperatureEntropy: Optional[ScalarSchema] = Field(None, title="scalar schema")
    """
    product of temperature and configurational entropy
    """
    harris_foulkes: Optional[ScalarSchema98] = Field(None, title="scalar schema")
    """
    non self-consitent energy based on an input charge density
    """
    smearing: Optional[ScalarSchema99] = Field(None, title="scalar schema")
    """
    smearing energy
    """
    one_electron: Optional[ScalarSchema100] = Field(None, title="scalar schema")
    """
    kinetic + pseudopotential energy
    """
    hartree: Optional[ScalarSchema101] = Field(None, title="scalar schema")
    """
    energy due to coulomb potential
    """
    exchange: Optional[ScalarSchema102] = Field(None, title="scalar schema")
    """
    exchange energy
    """
    exchange_correlation: Optional[ScalarSchema103] = Field(None, title="scalar schema")
    """
    exchange and correlation energy per particle
    """
    ewald: Optional[ScalarSchema104] = Field(None, title="scalar schema")
    """
    summation of interaction energies at long length scales due to coloumbic interactions
    """
    alphaZ: Optional[ScalarSchema105] = Field(None, title="scalar schema")
    """
    divergent electrostatic ion interaction in compensating electron gas
    """
    atomicEnergy: Optional[ScalarSchema106] = Field(None, title="scalar schema")
    """
    kinetic energy of wavefunctions in the atomic limit
    """
    eigenvalues: Optional[ScalarSchema107] = Field(None, title="scalar schema")
    """
    sum of one electron energies of kinetic, electrostatic, and exchange correlation
    """
    PAWDoubleCounting2: Optional[ScalarSchema108] = Field(None, title="scalar schema")
    """
    double counting correction 2
    """
    PAWDoubleCounting3: Optional[ScalarSchema109] = Field(None, title="scalar schema")
    """
    double counting correction 3
    """
    hartreeFock: Optional[ScalarSchema110] = Field(None, title="scalar schema")
    """
    hartree-fock contribution
    """
    name: Name804
    units: Optional[Units] = None
