# generated by datamodel-codegen:
#   filename:  properties_directory/non_scalar/total_energy_contributions.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class Name(Enum):
    temperature_entropy = "temperature_entropy"


class ScalarSchema(BaseModel):
    name: Optional[Name] = None
    value: float


class Name530(Enum):
    harris_foulkes = "harris_foulkes"


class ScalarSchema63(BaseModel):
    name: Optional[Name530] = None
    value: float


class Name531(Enum):
    one_electron = "one_electron"


class ScalarSchema64(BaseModel):
    name: Optional[Name531] = None
    value: float


class Name532(Enum):
    hartree = "hartree"


class ScalarSchema65(BaseModel):
    name: Optional[Name532] = None
    value: float


class Name533(Enum):
    exchange = "exchange"


class ScalarSchema66(BaseModel):
    name: Optional[Name533] = None
    value: float


class Name534(Enum):
    exchange_correlation = "exchange_correlation"


class ScalarSchema67(BaseModel):
    name: Optional[Name534] = None
    value: float


class Name535(Enum):
    ewald = "ewald"


class ScalarSchema68(BaseModel):
    name: Optional[Name535] = None
    value: float


class Name536(Enum):
    alphaZ = "alphaZ"


class ScalarSchema69(BaseModel):
    name: Optional[Name536] = None
    value: float


class Name537(Enum):
    atomic_energy = "atomic_energy"


class ScalarSchema70(BaseModel):
    name: Optional[Name537] = None
    value: float


class Name538(Enum):
    eigenvalues = "eigenvalues"


class ScalarSchema71(BaseModel):
    name: Optional[Name538] = None
    value: float


class Name539(Enum):
    PAW_double_counting_correction_2 = "PAW_double-counting_correction_2"


class ScalarSchema72(BaseModel):
    name: Optional[Name539] = None
    value: float


class Name540(Enum):
    PAW_double_counting_correction_3 = "PAW_double-counting_correction_3"


class ScalarSchema73(BaseModel):
    name: Optional[Name540] = None
    value: float


class Name541(Enum):
    hartree_fock = "hartree_fock"


class ScalarSchema74(BaseModel):
    name: Optional[Name541] = None
    value: float


class Name542(Enum):
    total_energy_contributions = "total_energy_contributions"


class Units(Enum):
    kJ_mol = "kJ/mol"
    eV = "eV"
    J_mol = "J/mol"
    hartree = "hartree"
    cm_1 = "cm-1"
    Ry = "Ry"
    eV_atom = "eV/atom"


class TotalEnergyContributionsSchema(BaseModel):
    temperatureEntropy: Optional[ScalarSchema] = Field(None, title="scalar schema")
    """
    product of temperature and configurational entropy
    """
    harrisFoulkes: Optional[ScalarSchema63] = Field(None, title="scalar schema")
    """
    non self-consitent energy based on an input charge density
    """
    oneElectron: Optional[ScalarSchema64] = Field(None, title="scalar schema")
    """
    kinetic + pseudopotential energy
    """
    hartree: Optional[ScalarSchema65] = Field(None, title="scalar schema")
    """
    energy due to coulomb potential
    """
    exchange: Optional[ScalarSchema66] = Field(None, title="scalar schema")
    """
    exchange energy
    """
    exchangeCorrelation: Optional[ScalarSchema67] = Field(None, title="scalar schema")
    """
    exchange and correlation energy per particle
    """
    ewald: Optional[ScalarSchema68] = Field(None, title="scalar schema")
    """
    summation of interaction energies at long length scales due to coloumbic interactions
    """
    alphaZ: Optional[ScalarSchema69] = Field(None, title="scalar schema")
    """
    divergent electrostatic ion interaction in compensating electron gas
    """
    atomicEnergy: Optional[ScalarSchema70] = Field(None, title="scalar schema")
    """
    kinetic energy of wavefunctions in the atomic limit
    """
    eigenvalues: Optional[ScalarSchema71] = Field(None, title="scalar schema")
    """
    sum of one electron energies of kinetic, electrostatic, and exchange correlation
    """
    PAWDoubleCounting2: Optional[ScalarSchema72] = Field(None, title="scalar schema")
    """
    double counting correction 2
    """
    PAWDoubleCounting3: Optional[ScalarSchema73] = Field(None, title="scalar schema")
    """
    double counting correction 3
    """
    hartreeFock: Optional[ScalarSchema74] = Field(None, title="scalar schema")
    """
    hartree-fock contribution
    """
    name: Optional[Name542] = None
    units: Optional[Units] = None
