# generated by datamodel-codegen:
#   filename:  properties_directory/non_scalar/total_entropy_contributions.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class Name(Enum):
    translational = "translational"


class ScalarSchema(BaseModel):
    name: Optional[Name] = None
    value: float


class Name789(Enum):
    rotational = "rotational"


class ScalarSchema124(BaseModel):
    name: Optional[Name789] = None
    value: float


class Name790(Enum):
    vibrational = "vibrational"


class ScalarSchema125(BaseModel):
    name: Optional[Name790] = None
    value: float


class Name791(Enum):
    total_entropy_contributions = "total_entropy_contributions"


class Units(Enum):
    cal_mol_K = "cal/mol-K"


class TotalEntropyContributionsPropertySchema(BaseModel):
    translational: Optional[ScalarSchema] = Field(None, title="scalar schema")
    """
    translational contribution to entropy
    """
    rotational: Optional[ScalarSchema124] = Field(None, title="scalar schema")
    """
    rotational contribution to entropy
    """
    vibrational: Optional[ScalarSchema125] = Field(None, title="scalar schema")
    """
    vibrational contribution to entropy
    """
    name: Name791
    units: Optional[Units] = None
