# generated by datamodel-codegen:
#   filename:  properties_directory/non_scalar/total_energy_contributions.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class Name(Enum):
    temperature_entropy = "temperature_entropy"


class ScalarSchema(BaseModel):
    name: Optional[Name] = None
    value: float


class Name817(Enum):
    harris_foulkes = "harris_foulkes"


class ScalarSchema101(BaseModel):
    name: Optional[Name817] = None
    value: float


class Name818(Enum):
    smearing = "smearing"


class ScalarSchema102(BaseModel):
    name: Optional[Name818] = None
    value: float


class Name819(Enum):
    one_electron = "one_electron"


class ScalarSchema103(BaseModel):
    name: Optional[Name819] = None
    value: float


class Name820(Enum):
    hartree = "hartree"


class ScalarSchema104(BaseModel):
    name: Optional[Name820] = None
    value: float


class Name821(Enum):
    exchange = "exchange"


class ScalarSchema105(BaseModel):
    name: Optional[Name821] = None
    value: float


class Name822(Enum):
    exchange_correlation = "exchange_correlation"


class ScalarSchema106(BaseModel):
    name: Optional[Name822] = None
    value: float


class Name823(Enum):
    ewald = "ewald"


class ScalarSchema107(BaseModel):
    name: Optional[Name823] = None
    value: float


class Name824(Enum):
    alphaZ = "alphaZ"


class ScalarSchema108(BaseModel):
    name: Optional[Name824] = None
    value: float


class Name825(Enum):
    atomic_energy = "atomic_energy"


class ScalarSchema109(BaseModel):
    name: Optional[Name825] = None
    value: float


class Name826(Enum):
    eigenvalues = "eigenvalues"


class ScalarSchema110(BaseModel):
    name: Optional[Name826] = None
    value: float


class Name827(Enum):
    PAW_double_counting_correction_2 = "PAW_double-counting_correction_2"


class ScalarSchema111(BaseModel):
    name: Optional[Name827] = None
    value: float


class Name828(Enum):
    PAW_double_counting_correction_3 = "PAW_double-counting_correction_3"


class ScalarSchema112(BaseModel):
    name: Optional[Name828] = None
    value: float


class Name829(Enum):
    hartree_fock = "hartree_fock"


class ScalarSchema113(BaseModel):
    name: Optional[Name829] = None
    value: float


class Name830(Enum):
    total_energy_contributions = "total_energy_contributions"


class Units(Enum):
    kcal_mol = "kcal/mol"
    kJ_mol = "kJ/mol"
    eV = "eV"
    J_mol = "J/mol"
    hartree = "hartree"
    cm_1 = "cm-1"
    Ry = "Ry"
    eV_atom = "eV/atom"


class TotalEnergyContributionsPropertySchema(BaseModel):
    temperatureEntropy: Optional[ScalarSchema] = Field(None, title="scalar schema")
    """
    product of temperature and configurational entropy
    """
    harris_foulkes: Optional[ScalarSchema101] = Field(None, title="scalar schema")
    """
    non self-consitent energy based on an input charge density
    """
    smearing: Optional[ScalarSchema102] = Field(None, title="scalar schema")
    """
    smearing energy
    """
    one_electron: Optional[ScalarSchema103] = Field(None, title="scalar schema")
    """
    kinetic + pseudopotential energy
    """
    hartree: Optional[ScalarSchema104] = Field(None, title="scalar schema")
    """
    energy due to coulomb potential
    """
    exchange: Optional[ScalarSchema105] = Field(None, title="scalar schema")
    """
    exchange energy
    """
    exchange_correlation: Optional[ScalarSchema106] = Field(None, title="scalar schema")
    """
    exchange and correlation energy per particle
    """
    ewald: Optional[ScalarSchema107] = Field(None, title="scalar schema")
    """
    summation of interaction energies at long length scales due to coloumbic interactions
    """
    alphaZ: Optional[ScalarSchema108] = Field(None, title="scalar schema")
    """
    divergent electrostatic ion interaction in compensating electron gas
    """
    atomicEnergy: Optional[ScalarSchema109] = Field(None, title="scalar schema")
    """
    kinetic energy of wavefunctions in the atomic limit
    """
    eigenvalues: Optional[ScalarSchema110] = Field(None, title="scalar schema")
    """
    sum of one electron energies of kinetic, electrostatic, and exchange correlation
    """
    PAWDoubleCounting2: Optional[ScalarSchema111] = Field(None, title="scalar schema")
    """
    double counting correction 2
    """
    PAWDoubleCounting3: Optional[ScalarSchema112] = Field(None, title="scalar schema")
    """
    double counting correction 3
    """
    hartreeFock: Optional[ScalarSchema113] = Field(None, title="scalar schema")
    """
    hartree-fock contribution
    """
    name: Name830
    units: Optional[Units] = None
