# generated by datamodel-codegen:
#   filename:  core/reusable/atomic_data_per_orbital_numeric.json
#   version:   0.28.5

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field, constr


class AtomicDataPerOrbitalNumeric(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Optional[int] = None
    """
    Site number or index in the lattice
    """
    atomic_species: Optional[constr(pattern=r"^[a-zA-Z]{1,2}[\d+]?$")] = Field(None, alias="atomicSpecies")
    """
    Example: Co1, Mn
    """
    orbital_name: Optional[constr(pattern=r"^[1-7][sSpPdDfF]$")] = Field(None, alias="orbitalName")
    value: Optional[float] = None
    """
    Value related to a specific property, e.g., Hubbard U, V etc.
    """
