# generated by datamodel-codegen:
#   filename:  core/reusable/environment.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class Units(Enum):
    K = "K"
    degC = "degC"


class TemperatureQuantitySchema(BaseModel):
    units: Optional[Units] = "K"
    value: float


class Units223(Enum):
    kbar = "kbar"
    pa = "pa"
    Torr = "Torr"
    mTorr = "mTorr"
    mbar = "mbar"
    bar = "bar"
    atm = "atm"


class PressureQuantitySchema(BaseModel):
    units: Units223
    value: float


class Atmosphere(Enum):
    ambient = "ambient"
    vacuum = "vacuum"
    high_vacuum = "high_vacuum"
    ultra_high_vacuum = "ultra_high_vacuum"
    nitrogen = "nitrogen"
    argon = "argon"
    oxygen = "oxygen"
    forming_gas = "forming_gas"
    liquid = "liquid"
    other = "other"


class Units224(Enum):
    unitless = "unitless"
    percent = "percent"
    ppm = "ppm"
    fraction = "fraction"


class Humidity(BaseModel):
    value: Optional[float] = None
    units: Optional[Units224] = None


class EnvironmentSchema(BaseModel):
    temperature: Optional[TemperatureQuantitySchema] = Field(None, title="temperature quantity schema")
    """
    A scalar with temperature units. Follows the core/reusable/energy pattern (a scalar plus a units enum) without requiring a property name, so it can be embedded as a field of any schema.
    """
    pressure: Optional[PressureQuantitySchema] = Field(None, title="pressure quantity schema")
    """
    A scalar with pressure units, e.g. a chamber base or working pressure. Follows the core/reusable/energy pattern (a scalar plus a units enum) without requiring a property name, so it can be embedded as a field of any schema.
    """
    atmosphere: Optional[Atmosphere] = None
    """
    Gas or vacuum the sample sits in.
    """
    humidity: Optional[Humidity] = None
    """
    Relative humidity, as a percentage.
    """
