# generated by datamodel-codegen:
#   filename:  core/reusable/hysteresis_loop_parameters.json
#   version:   0.28.5

from __future__ import annotations

from pydantic import BaseModel, Field


class CombinedValueSchema(BaseModel):
    uncertainty: float
    """
    spread of the repeated measurements about the mean
    """
    count: int
    """
    number of measurements the value is combined over
    """
    value: float


class CoerciveVoltage(BaseModel):
    rising: CombinedValueSchema = Field(..., title="Combined value schema")
    """
    A value combined over repeated measurements: mean, spread, count. Units come from the context the value appears in
    """
    falling: CombinedValueSchema = Field(..., title="Combined value schema")
    """
    A value combined over repeated measurements: mean, spread, count. Units come from the context the value appears in
    """


class RemanentResponse(BaseModel):
    rising: CombinedValueSchema = Field(..., title="Combined value schema")
    """
    A value combined over repeated measurements: mean, spread, count. Units come from the context the value appears in
    """
    falling: CombinedValueSchema = Field(..., title="Combined value schema")
    """
    A value combined over repeated measurements: mean, spread, count. Units come from the context the value appears in
    """


class HysteresisLoopParametersSchema(BaseModel):
    imprint: CombinedValueSchema = Field(..., title="Combined value schema")
    """
    A value combined over repeated measurements: mean, spread, count. Units come from the context the value appears in
    """
    coerciveVoltage: CoerciveVoltage
    """
    bias at which the response crosses the loop's offset, on the rising and the falling branch
    """
    loopWidth: CombinedValueSchema = Field(..., title="Combined value schema")
    """
    A value combined over repeated measurements: mean, spread, count. Units come from the context the value appears in
    """
    loopHeight: CombinedValueSchema = Field(..., title="Combined value schema")
    """
    A value combined over repeated measurements: mean, spread, count. Units come from the context the value appears in
    """
    remanentResponse: RemanentResponse
    """
    response at zero bias, on the rising and the falling branch
    """
