# generated by datamodel-codegen:
#   filename:  core/reusable/identifier.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel


class Scheme(Enum):
    internal = "internal"
    htem = "htem"
    lmc = "lmc"
    igsn = "igsn"
    doi = "doi"
    barcode = "barcode"
    vendor = "vendor"
    other = "other"


class IdentifierSchema(BaseModel):
    scheme: Scheme
    """
    Namespace the value is unique within.
    """
    value: str
    """
    The identifier itself.
    """
