# generated by datamodel-codegen:
#   filename:  core/reusable/object_storage_container_data.json
#   version:   0.28.5

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


class ObjectStorageContainerData(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    container: Optional[str] = Field(None, alias="CONTAINER")
    """
    Object storage container for the file
    """
    name: Optional[str] = Field(None, alias="NAME")
    """
    Name of the file inside the object storage bucket
    """
    provider: Optional[str] = Field(None, alias="PROVIDER")
    """
    Object storage provider
    """
    region: Optional[str] = Field(None, alias="REGION")
    """
    Region for the object container specified in Container
    """
    size: Optional[int] = Field(None, alias="SIZE")
    """
    Size of the file in bytes
    """
    timestamp: Optional[str] = Field(None, alias="TIMESTAMP")
    """
    Unix timestamp showing when the file was last modified
    """
