# generated by datamodel-codegen:
#   filename:  software/application_properties.json
#   version:   0.28.5

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class ApplicationPropertiesSchema(BaseModel):
    shortName: str
    """
    The short name of the application. e.g. qe
    """
    summary: str
    """
    Application's short description.
    """
    version: str
    """
    Application version. e.g. 5.3.5
    """
    build: str
    """
    Application build. e.g. VTST
    """
    isDefault: Optional[bool] = None
    """
    Whether the build is the default build
    """
    hasAdvancedComputeOptions: Optional[bool] = None
    """
    Whether advanced compute options are present
    """
    isLicensed: Optional[bool] = None
    """
    Whether licensing is present
    """
    isUsingMaterial: Optional[bool] = None
    """
    Whether the application is using (being passed during a downstream processing routine) a material structure.
    """
