# generated by datamodel-codegen:
#   filename:  software/flavor.json
#   version:   0.28.5

from __future__ import annotations

from typing import List, Optional, Union

from pydantic import BaseModel, ConfigDict, Field


class ExecutionUnitInputIdItemSchemaForPhysicsBasedSimulationEngines(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    template_id: Optional[str] = Field(None, alias="templateId")
    template_name: Optional[str] = Field(None, alias="templateName")
    name: Optional[str] = None
    """
    name of the resulting input file, if different than template name
    """


class NameResultSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: str
    """
    The name of this item. e.g. scf_accuracy
    """


class FlavorSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    executable_id: Optional[str] = Field(None, alias="executableId")
    """
    _id of the executable this flavor belongs to
    """
    executable_name: Optional[str] = Field(None, alias="executableName")
    """
    name of the executable this flavor belongs to
    """
    application_name: Optional[str] = Field(None, alias="applicationName")
    """
    name of the application this flavor belongs to
    """
    input: Optional[List[ExecutionUnitInputIdItemSchemaForPhysicsBasedSimulationEngines]] = Field(
        None, title="execution unit input schema"
    )
    supported_application_versions: Optional[List[str]] = Field(None, alias="supportedApplicationVersions")
    """
    list of application versions this flavor supports
    """
    field_id: Optional[str] = Field(None, alias="_id")
    """
    entity identity
    """
    slug: Optional[str] = None
    """
    entity slug
    """
    system_name: Optional[str] = Field(None, alias="systemName")
    schema_version: Optional[str] = Field("2022.8.16", alias="schemaVersion")
    """
    entity's schema version. Used to distinct between different schemas.
    """
    name: Optional[str] = None
    """
    entity name
    """
    is_default: Optional[bool] = Field(False, alias="isDefault")
    """
    Identifies that entity is defaultable
    """
    pre_processors: Optional[List[Union[NameResultSchema, str]]] = Field(None, alias="preProcessors")
    """
    names of the pre-processors for this calculation
    """
    post_processors: Optional[List[Union[NameResultSchema, str]]] = Field(None, alias="postProcessors")
    """
    names of the post-processors for this calculation
    """
    monitors: Optional[List[Union[NameResultSchema, str]]] = None
    """
    names of the monitors for this calculation
    """
    results: Optional[List[Union[NameResultSchema, str]]] = None
    """
    names of the results for this calculation
    """
