# generated by datamodel-codegen:
#   filename:  software/template_properties.json
#   version:   0.28.5

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class RuntimeItemNameObjectSchema(BaseModel):
    name: str
    """
    The name of this item. e.g. scf_accuracy
    """


class TemplatePropertiesSchema(BaseModel):
    applicationName: str
    applicationVersion: Optional[str] = None
    executableName: str
    contextProviders: List[RuntimeItemNameObjectSchema]
    content: str
    """
    Content of the template. e.g. &CONTROL    calculation='scf' ...
    """
