# generated by datamodel-codegen:
#   filename:  properties_directory/scalar/coercive_voltage.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel


class Name(Enum):
    coercive_voltage = "coercive_voltage"


class Units(Enum):
    V = "V"
    mV = "mV"


class Field(Enum):
    on = "on"
    off = "off"


class Branch(Enum):
    rising = "rising"
    falling = "falling"


class CoerciveVoltagePropertySchema(BaseModel):
    name: Name
    units: Units
    field: Field
    """
    whether the loop was read with the bias applied (on, in-field) or after each pulse (off, out-of-field)
    """
    branch: Branch
    """
    the branch of the loop the value is read from
    """
    value: float
