# generated by datamodel-codegen:
#   filename:  properties_directory/scalar/formation_energy.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import Union

from pydantic import BaseModel, ConfigDict


class Name(Enum):
    formation_energy = "formation_energy"


class Units(Enum):
    k_j_mol = "kJ/mol"
    e_v = "eV"
    j_mol = "J/mol"
    hartree = "hartree"
    cm_1 = "cm-1"
    ry = "Ry"
    e_v_atom = "eV/atom"


class Units190(Enum):
    e_v_a_2 = "eV/A^2"


class FormationEnergyPropertySchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: Name
    units: Union[Units, Units190]
    value: float
