# generated by datamodel-codegen:
#   filename:  properties_directory/scalar/total_entropy.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel


class Name(Enum):
    total_entropy = "total_entropy"


class Units(Enum):
    cal_mol_K = "cal/mol-K"


class TotalEntropyPropertySchema(BaseModel):
    name: Name
    units: Units
    value: float
