# generated by datamodel-codegen:
#   filename:  properties_directory/scalar/total_force.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict


class Name(Enum):
    total_force = "total_force"


class Units(Enum):
    e_v_bohr = "eV/bohr"
    e_v_angstrom = "eV/angstrom"
    ry_a_u_ = "Ry/a.u."
    newton = "newton"
    kg_m_s_2 = "kg*m/s^2"
    e_v_a_u_ = "eV/a.u."


class TotalForcesPropertySchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: Name
    units: Units
    value: float
