# generated by datamodel-codegen:
#   filename:  process/source/base.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class Units(Enum):
    unitless = "unitless"
    percent = "percent"
    ppm = "ppm"
    fraction = "fraction"


class Purity(BaseModel):
    value: Optional[float] = None
    units: Optional[Units] = None


class Cls(Enum):
    Material = "Material"


class MaterialEntityReferenceSchema(BaseModel):
    cls: Optional[Cls] = None
    """
    Material class
    """
    id: str = Field(..., alias="_id")
    """
    entity identity
    """
    slug: Optional[str] = None
    """
    entity slug
    """


class ProcessSourceBaseSchema(BaseModel):
    id: str
    """
    Identifier for this source within the stage, referenced from a step's setpoints.
    """
    name: Optional[str] = None
    formula: Optional[str] = None
    """
    Chemical formula of the source material, e.g. Al(CH3)3
    """
    purity: Optional[Purity] = None
    """
    Purity of the source material.
    """
    vendor: Optional[str] = None
    material: Optional[MaterialEntityReferenceSchema] = Field(
        None, alias="_material", title="Material entity reference schema"
    )
