# generated by datamodel-codegen:
#   filename:  properties_directory/elemental/ionization_potential.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict


class Name(Enum):
    ionization_potential = "ionization_potential"


class Units(Enum):
    k_j_mol = "kJ/mol"
    e_v = "eV"
    j_mol = "J/mol"
    hartree = "hartree"
    cm_1 = "cm-1"
    ry = "Ry"
    e_v_atom = "eV/atom"


class IonizationPotentialElementalPropertySchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: Name
    units: Units
    value: float
