# generated by datamodel-codegen:
#   filename:  workflow/unit/input/_input.json
#   version:   0.28.5

from __future__ import annotations

from typing import List, Optional, Union

from pydantic import BaseModel, ConfigDict, Field


class ExecutionUnitInputItemSchemaForPhysicsBasedSimulationEngines(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: str
    """
    Input file name. e.g. pw_scf.in
    """
    content: str
    """
    Content of the input file. e.g. &CONTROL    calculation='scf' ...
    """
    rendered: Optional[str] = None
    """
    Rendered content of the input file. e.g. &CONTROL    calculation='scf' ...
    """


class ExecutionUnitInputIdItemSchemaForPhysicsBasedSimulationEngines(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    template_id: Optional[str] = Field(None, alias="templateId")
    template_name: Optional[str] = Field(None, alias="templateName")
    name: Optional[str] = None
    """
    name of the resulting input file, if different than template name
    """


class ExecutionUnitInputSchemaForPhysicsBasedSimulationEngines(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    input: Optional[
        List[
            Union[
                ExecutionUnitInputItemSchemaForPhysicsBasedSimulationEngines,
                ExecutionUnitInputIdItemSchemaForPhysicsBasedSimulationEngines,
            ]
        ]
    ] = Field(None, title="execution unit input schema")
