# generated by datamodel-codegen:
#   filename:  apse/db/materials_project/2025.9.25/summary.json
#   version:   0.28.5

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, ConfigDict, Field, RootModel


class BuilderMeta(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    emmet_version: str
    """
    Version of emmet library used
    """
    pymatgen_version: str
    """
    Version of pymatgen library used
    """
    run_id: str
    """
    Unique identifier for the calculation run
    """
    batch_id: Optional[str] = None
    """
    Batch identifier for grouped calculations
    """
    database_version: str
    """
    Version of the Materials Project database
    """
    build_date: datetime
    """
    Date when the calculation was performed
    """
    license: str
    """
    License information for the data
    """


class Symmetry(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    crystal_system: str
    """
    Crystal system classification
    """
    symbol: str
    """
    Space group symbol
    """
    hall: Optional[str] = None
    """
    Hall symbol
    """
    number: int
    """
    Space group number
    """
    point_group: str
    """
    Point group symbol
    """
    symprec: float
    """
    Symmetry precision tolerance
    """
    angle_tolerance: float
    """
    Angle tolerance for symmetry analysis
    """
    version: str
    """
    Version of symmetry analysis software
    """


class Origin(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: str
    """
    Origin name (e.g., structure, energy, magnetism)
    """
    task_id: str
    """
    Task identifier for this origin
    """
    last_updated: datetime
    """
    Last update for this origin
    """


class MatrixItem(RootModel[List[float]]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: List[float]


class Lattice(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    matrix: List[MatrixItem] = Field(..., max_length=3, min_length=3)
    """
    Lattice matrix
    """
    pbc: List[bool] = Field(..., max_length=3, min_length=3)
    """
    Periodic boundary conditions
    """
    a: float
    """
    Lattice parameter a
    """
    b: float
    """
    Lattice parameter b
    """
    c: float
    """
    Lattice parameter c
    """
    alpha: float
    """
    Lattice angle alpha
    """
    beta: float
    """
    Lattice angle beta
    """
    gamma: float
    """
    Lattice angle gamma
    """
    volume: float
    """
    Unit cell volume
    """


class Species(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    element: str
    """
    Chemical element
    """
    occu: float
    """
    Occupancy
    """


class Properties(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    magmom: Optional[float] = None
    """
    Magnetic moment
    """


class Site(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    species: List[Species]
    abc: List[float] = Field(..., max_length=3, min_length=3)
    """
    Fractional coordinates
    """
    properties: Optional[Properties] = None
    label: str
    """
    Site label
    """
    xyz: List[float] = Field(..., max_length=3, min_length=3)
    """
    Cartesian coordinates
    """


class Structure(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    field_module: str = Field(..., alias="@module")
    """
    Python module name
    """
    field_class: str = Field(..., alias="@class")
    """
    Python class name
    """
    charge: float
    """
    Total charge of the structure
    """
    lattice: Lattice
    properties: Dict[str, Any]
    """
    Additional structure properties
    """
    sites: List[Site]


class DecomposesToItem(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    material_id: str
    """
    Material ID of decomposition product
    """
    formula: str
    """
    Formula of decomposition product
    """
    amount: float
    """
    Amount of decomposition product
    """


class Xa(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    edge: str
    """
    XAS edge type (K, L, M, etc.)
    """
    absorbing_element: str
    """
    Element for XAS absorption
    """
    spectrum_type: str
    """
    Type of XAS spectrum (XANES, EXAFS, XAFS)
    """


class Lattice1(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    field_module: str = Field(..., alias="@module")
    field_class: str = Field(..., alias="@class")
    matrix: List[MatrixItem] = Field(..., max_length=3, min_length=3)
    pbc: List[bool] = Field(..., max_length=3, min_length=3)


class Kpoint(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    lattice: Lattice1
    fcoords: List[float] = Field(..., max_length=3, min_length=3)
    ccoords: List[float] = Field(..., max_length=3, min_length=3)
    label: Optional[str] = None
    field_module: str = Field(..., alias="@module")
    field_class: str = Field(..., alias="@class")


class Cbm(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    band_index: Dict[str, List[float]]
    kpoint_index: List[float]
    kpoint: Kpoint
    energy: float
    projections: Dict[str, List[List[float]]]


class Lattice2(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    field_module: str = Field(..., alias="@module")
    field_class: str = Field(..., alias="@class")
    matrix: List[MatrixItem] = Field(..., max_length=3, min_length=3)
    pbc: List[bool] = Field(..., max_length=3, min_length=3)


class Kpoint1(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    lattice: Lattice2
    fcoords: List[float] = Field(..., max_length=3, min_length=3)
    ccoords: List[float] = Field(..., max_length=3, min_length=3)
    label: Optional[str] = None
    field_module: str = Field(..., alias="@module")
    field_class: str = Field(..., alias="@class")


class Vbm(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    band_index: Dict[str, List[float]]
    kpoint_index: List[float]
    kpoint: Kpoint1
    energy: float
    projections: Dict[str, List[List[float]]]


class SetyawanCurtarolo(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    task_id: str
    band_gap: float
    cbm: Optional[Cbm] = None
    vbm: Optional[Vbm] = None
    efermi: Optional[float] = None
    is_gap_direct: bool
    is_metal: bool
    magnetic_ordering: str
    equivalent_labels: Dict[str, Dict[str, Dict[str, str]]]
    nbands: float
    direct_gap: float


class Lattice3(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    field_module: str = Field(..., alias="@module")
    field_class: str = Field(..., alias="@class")
    matrix: List[MatrixItem] = Field(..., max_length=3, min_length=3)
    pbc: List[bool] = Field(..., max_length=3, min_length=3)


class Kpoint2(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    lattice: Lattice3
    fcoords: List[float] = Field(..., max_length=3, min_length=3)
    ccoords: List[float] = Field(..., max_length=3, min_length=3)
    label: Optional[str] = None
    field_module: str = Field(..., alias="@module")
    field_class: str = Field(..., alias="@class")


class Cbm1(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    band_index: Dict[str, List[float]]
    kpoint_index: List[float]
    kpoint: Kpoint2
    energy: float
    projections: Dict[str, List[List[float]]]


class Lattice4(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    field_module: str = Field(..., alias="@module")
    field_class: str = Field(..., alias="@class")
    matrix: List[MatrixItem] = Field(..., max_length=3, min_length=3)
    pbc: List[bool] = Field(..., max_length=3, min_length=3)


class Kpoint3(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    lattice: Lattice4
    fcoords: List[float] = Field(..., max_length=3, min_length=3)
    ccoords: List[float] = Field(..., max_length=3, min_length=3)
    label: Optional[str] = None
    field_module: str = Field(..., alias="@module")
    field_class: str = Field(..., alias="@class")


class Vbm1(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    band_index: Dict[str, List[float]]
    kpoint_index: List[float]
    kpoint: Kpoint3
    energy: float
    projections: Dict[str, List[List[float]]]


class Hinuma(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    task_id: str
    band_gap: float
    cbm: Optional[Cbm1] = None
    vbm: Optional[Vbm1] = None
    efermi: Optional[float] = None
    is_gap_direct: bool
    is_metal: bool
    magnetic_ordering: str
    equivalent_labels: Dict[str, Dict[str, Dict[str, str]]]
    nbands: float
    direct_gap: float


class Lattice5(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    field_module: str = Field(..., alias="@module")
    field_class: str = Field(..., alias="@class")
    matrix: List[MatrixItem] = Field(..., max_length=3, min_length=3)
    pbc: List[bool] = Field(..., max_length=3, min_length=3)


class Kpoint4(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    lattice: Lattice5
    fcoords: List[float] = Field(..., max_length=3, min_length=3)
    ccoords: List[float] = Field(..., max_length=3, min_length=3)
    label: Optional[str] = None
    field_module: str = Field(..., alias="@module")
    field_class: str = Field(..., alias="@class")


class Cbm2(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    band_index: Dict[str, List[float]]
    kpoint_index: List[float]
    kpoint: Kpoint4
    energy: float
    projections: Dict[str, List[List[float]]]


class Lattice6(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    field_module: str = Field(..., alias="@module")
    field_class: str = Field(..., alias="@class")
    matrix: List[MatrixItem] = Field(..., max_length=3, min_length=3)
    pbc: List[bool] = Field(..., max_length=3, min_length=3)


class Kpoint5(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    lattice: Lattice6
    fcoords: List[float] = Field(..., max_length=3, min_length=3)
    ccoords: List[float] = Field(..., max_length=3, min_length=3)
    label: Optional[str] = None
    field_module: str = Field(..., alias="@module")
    field_class: str = Field(..., alias="@class")


class Vbm2(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    band_index: Dict[str, List[float]]
    kpoint_index: List[float]
    kpoint: Kpoint5
    energy: float
    projections: Dict[str, List[List[float]]]


class LatimerMunro(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    task_id: str
    band_gap: float
    cbm: Optional[Cbm2] = None
    vbm: Optional[Vbm2] = None
    efermi: Optional[float] = None
    is_gap_direct: bool
    is_metal: bool
    magnetic_ordering: str
    equivalent_labels: Dict[str, Dict[str, Dict[str, str]]]
    nbands: float
    direct_gap: float


class Bandstructure(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    setyawan_curtarolo: Optional[SetyawanCurtarolo] = None
    hinuma: Optional[Hinuma] = None
    latimer_munro: Optional[LatimerMunro] = None


class Total(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    task_id: str
    band_gap: float
    cbm: Optional[float] = None
    vbm: Optional[float] = None
    efermi: float
    spin_polarization: Optional[float] = None


class S(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    task_id: str
    band_gap: float
    cbm: Optional[float] = None
    vbm: Optional[float] = None
    efermi: float
    spin_polarization: Optional[float] = None


class P(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    task_id: str
    band_gap: float
    cbm: Optional[float] = None
    vbm: Optional[float] = None
    efermi: float
    spin_polarization: Optional[float] = None


class D(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    task_id: str
    band_gap: float
    cbm: Optional[float] = None
    vbm: Optional[float] = None
    efermi: float
    spin_polarization: Optional[float] = None


class Elemental(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    total: Optional[Dict[str, Total]] = None
    s: Optional[Dict[str, S]] = None
    p: Optional[Dict[str, P]] = None
    d: Optional[Dict[str, D]] = None


class Orbital(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    s: Optional[Dict[str, S]] = None
    p: Optional[Dict[str, P]] = None
    d: Optional[Dict[str, D]] = None


class Dos(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    total: Optional[Dict[str, Total]] = None
    elemental: Optional[Dict[str, Elemental]] = None
    orbital: Optional[Orbital] = None
    magnetic_ordering: Optional[str] = None
    """
    Magnetic ordering type
    """


class BulkModulus(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    voigt: float
    """
    Voigt bulk modulus in GPa
    """
    reuss: float
    """
    Reuss bulk modulus in GPa
    """
    vrh: float
    """
    Voigt-Reuss-Hill bulk modulus in GPa
    """


class ShearModulus(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    voigt: float
    """
    Voigt shear modulus in GPa
    """
    reuss: float
    """
    Reuss shear modulus in GPa
    """
    vrh: float
    """
    Voigt-Reuss-Hill shear modulus in GPa
    """


class HasProps(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    materials: bool
    thermo: bool
    xas: bool
    grain_boundaries: bool
    chemenv: bool
    electronic_structure: bool
    absorption: bool
    bandstructure: bool
    dos: bool
    magnetism: bool
    elasticity: bool
    dielectric: bool
    piezoelectric: bool
    surface_properties: bool
    oxi_states: bool
    provenance: bool
    charge_density: bool
    eos: bool
    phonon: bool
    insertion_electrodes: bool
    substrates: bool


class DatabaseIDs(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    icsd: Optional[List[str]] = None
    """
    ICSD database identifiers
    """


class MaterialsProjectSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    builder_meta: BuilderMeta
    nsites: int
    """
    Number of sites in the structure
    """
    elements: List[str]
    """
    List of chemical elements in the material
    """
    nelements: int
    """
    Number of unique elements
    """
    composition: Dict[str, float]
    """
    Chemical composition as element: count mapping
    """
    composition_reduced: Dict[str, float]
    """
    Reduced chemical composition
    """
    formula_pretty: str
    """
    Human-readable chemical formula
    """
    formula_anonymous: str
    """
    Anonymous chemical formula
    """
    chemsys: str
    """
    Chemical system identifier
    """
    volume: float
    """
    Unit cell volume in cubic Angstroms
    """
    density: float
    """
    Material density in g/cm³
    """
    density_atomic: float
    """
    Atomic density
    """
    symmetry: Symmetry
    material_id: str
    """
    Unique Materials Project identifier
    """
    deprecated: bool
    """
    Whether this material entry is deprecated
    """
    deprecation_reasons: Optional[List[str]] = None
    """
    Reasons for deprecation if applicable
    """
    last_updated: datetime
    """
    Last update timestamp
    """
    origins: List[Origin]
    warnings: List[str]
    """
    Warning messages
    """
    structure: Structure
    property_name: str
    """
    Name of the property endpoint
    """
    task_ids: List[str]
    """
    List of task identifiers
    """
    uncorrected_energy_per_atom: float
    """
    Uncorrected energy per atom in eV
    """
    energy_per_atom: float
    """
    Energy per atom in eV
    """
    formation_energy_per_atom: float
    """
    Formation energy per atom in eV
    """
    energy_above_hull: float
    """
    Energy above convex hull in eV
    """
    is_stable: bool
    """
    Whether the material is thermodynamically stable
    """
    equilibrium_reaction_energy_per_atom: Optional[float] = None
    """
    Equilibrium reaction energy per atom in eV
    """
    decomposes_to: Optional[List[DecomposesToItem]] = None
    xas: Optional[List[Xa]] = None
    grain_boundaries: Optional[Dict[str, Any]] = None
    """
    Grain boundary information
    """
    band_gap: float
    """
    Band gap in eV
    """
    cbm: Optional[float] = None
    """
    Conduction band minimum in eV
    """
    vbm: Optional[float] = None
    """
    Valence band maximum in eV
    """
    efermi: Optional[float] = None
    """
    Fermi energy in eV
    """
    is_gap_direct: bool
    """
    Whether the band gap is direct
    """
    is_metal: bool
    """
    Whether the material is metallic
    """
    es_source_calc_id: Optional[str] = None
    """
    Source calculation ID for electronic structure
    """
    bandstructure: Optional[Bandstructure] = None
    dos: Optional[Dos] = None
    dos_energy_up: Optional[Dict[str, Any]] = None
    """
    Density of states for spin up
    """
    dos_energy_down: Optional[Dict[str, Any]] = None
    """
    Density of states for spin down
    """
    is_magnetic: bool
    """
    Whether the material is magnetic
    """
    ordering: str
    """
    Magnetic ordering
    """
    total_magnetization: float
    """
    Total magnetization
    """
    total_magnetization_normalized_vol: float
    """
    Volume-normalized magnetization
    """
    total_magnetization_normalized_formula_units: float
    """
    Formula unit normalized magnetization
    """
    num_magnetic_sites: float
    """
    Number of magnetic sites
    """
    num_unique_magnetic_sites: float
    """
    Number of unique magnetic sites
    """
    types_of_magnetic_species: List[str]
    """
    Types of magnetic species
    """
    bulk_modulus: Optional[BulkModulus] = None
    shear_modulus: Optional[ShearModulus] = None
    universal_anisotropy: Optional[float] = None
    """
    Universal anisotropy index
    """
    homogeneous_poisson: Optional[float] = None
    """
    Homogeneous Poisson ratio
    """
    e_total: Optional[float] = None
    """
    Total energy
    """
    e_ionic: Optional[float] = None
    """
    Ionic energy
    """
    e_electronic: Optional[float] = None
    """
    Electronic energy
    """
    n: Optional[float] = None
    """
    Refractive index
    """
    e_ij_max: Optional[float] = None
    """
    Maximum elastic constant
    """
    weighted_surface_energy_ev_per_ang2: Optional[float] = Field(None, alias="weighted_surface_energy_EV_PER_ANG2")
    """
    Weighted surface energy in eV/Å²
    """
    weighted_surface_energy: Optional[float] = None
    """
    Weighted surface energy
    """
    weighted_work_function: Optional[float] = None
    """
    Weighted work function
    """
    surface_anisotropy: Optional[float] = None
    """
    Surface anisotropy
    """
    shape_factor: Optional[float] = None
    """
    Shape factor
    """
    has_reconstructed: Optional[bool] = None
    """
    Whether surface has reconstruction
    """
    possible_species: Optional[List[str]] = None
    """
    Possible ionic species
    """
    has_props: HasProps
    theoretical: bool
    """
    Whether this is a theoretical material
    """
    database_i_ds: DatabaseIDs = Field(..., alias="database_IDs")


class Lattice7(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    field_module: str = Field(..., alias="@module")
    field_class: str = Field(..., alias="@class")
    matrix: List[MatrixItem] = Field(..., max_length=3, min_length=3)
    pbc: List[bool] = Field(..., max_length=3, min_length=3)


class Kpoint6(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    lattice: Lattice7
    fcoords: List[float] = Field(..., max_length=3, min_length=3)
    ccoords: List[float] = Field(..., max_length=3, min_length=3)
    label: Optional[str] = None
    field_module: str = Field(..., alias="@module")
    field_class: str = Field(..., alias="@class")


class Cbm3(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    band_index: Dict[str, List[float]]
    kpoint_index: List[float]
    kpoint: Kpoint6
    energy: float
    projections: Dict[str, List[List[float]]]


class Lattice8(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    field_module: str = Field(..., alias="@module")
    field_class: str = Field(..., alias="@class")
    matrix: List[MatrixItem] = Field(..., max_length=3, min_length=3)
    pbc: List[bool] = Field(..., max_length=3, min_length=3)


class Kpoint7(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    lattice: Lattice8
    fcoords: List[float] = Field(..., max_length=3, min_length=3)
    ccoords: List[float] = Field(..., max_length=3, min_length=3)
    label: Optional[str] = None
    field_module: str = Field(..., alias="@module")
    field_class: str = Field(..., alias="@class")


class Vbm3(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    band_index: Dict[str, List[float]]
    kpoint_index: List[float]
    kpoint: Kpoint7
    energy: float
    projections: Dict[str, List[List[float]]]


class BandstructureData(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    task_id: str
    band_gap: float
    cbm: Optional[Cbm3] = None
    vbm: Optional[Vbm3] = None
    efermi: Optional[float] = None
    is_gap_direct: bool
    is_metal: bool
    magnetic_ordering: str
    equivalent_labels: Dict[str, Dict[str, Dict[str, str]]]
    nbands: float
    direct_gap: float


class Lattice9(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    field_module: str = Field(..., alias="@module")
    field_class: str = Field(..., alias="@class")
    matrix: List[MatrixItem] = Field(..., max_length=3, min_length=3)
    pbc: List[bool] = Field(..., max_length=3, min_length=3)


class Kpoint8(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    lattice: Lattice9
    fcoords: List[float] = Field(..., max_length=3, min_length=3)
    ccoords: List[float] = Field(..., max_length=3, min_length=3)
    label: Optional[str] = None
    field_module: str = Field(..., alias="@module")
    field_class: str = Field(..., alias="@class")


class BandExtrema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    band_index: Dict[str, List[float]]
    kpoint_index: List[float]
    kpoint: Kpoint8
    energy: float
    projections: Dict[str, List[List[float]]]


class Lattice10(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    field_module: str = Field(..., alias="@module")
    field_class: str = Field(..., alias="@class")
    matrix: List[MatrixItem] = Field(..., max_length=3, min_length=3)
    pbc: List[bool] = Field(..., max_length=3, min_length=3)


class Kpoint9(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    lattice: Lattice10
    fcoords: List[float] = Field(..., max_length=3, min_length=3)
    ccoords: List[float] = Field(..., max_length=3, min_length=3)
    label: Optional[str] = None
    field_module: str = Field(..., alias="@module")
    field_class: str = Field(..., alias="@class")


class DosData(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    task_id: str
    band_gap: float
    cbm: Optional[float] = None
    vbm: Optional[float] = None
    efermi: float
    spin_polarization: Optional[float] = None
