# generated by datamodel-codegen:
#   filename:  core/reusable/material/slab/miller_indices.json
#   version:   0.28.5

from __future__ import annotations

from typing import List, Optional

from pydantic import Field, RootModel


class MillerIndicesSchema(RootModel[Optional[List[float]]]):
    root: Optional[List[float]] = Field([0, 0, 1], max_length=3, min_length=3, title="Miller Indices Schema")
    """
    Miller indices for crystallographic plane designation
    """
