# generated by datamodel-codegen:
#   filename:  software/application.json
#   version:   0.28.5

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


<<<<<<< HEAD
class ApplicationSchema(BaseModel):
=======
class ApplicationSchemaBase(BaseModel):
    shortName: Optional[str] = None
    """
    The short name of the application. e.g. qe
    """
    summary: Optional[str] = None
    """
    Application's short description.
    """
    version: Optional[str] = None
    """
    Application version. e.g. 5.3.5
    """
    build: Optional[str] = None
    """
    Application build. e.g. VTST
    """
    isDefault: Optional[bool] = False
    """
    Whether the build is the default build
    """
    hasAdvancedComputeOptions: Optional[bool] = None
    """
    Whether advanced compute options are present
    """
    isLicensed: Optional[bool] = None
    """
    Whether licensing is present
    """
    isUsingMaterial: Optional[bool] = None
    """
    Whether the application is using (being passed during a downstream processing routine) a material structure.
    """
>>>>>>> 2b0a111c7c55c4da1c23d8089d1c18db24a26ce3
    id: Optional[str] = Field(None, alias="_id")
    """
    entity identity
    """
    slug: Optional[str] = None
    """
    entity slug
    """
    systemName: Optional[str] = None
    schemaVersion: Optional[str] = "2022.8.16"
    """
    entity's schema version. Used to distinct between different schemas.
    """
    name: str
    """
    entity name
    """
    isDefault: Optional[bool] = False
    """
    Identifies that entity is defaultable
    """
    shortName: str
    """
    The short name of the application. e.g. qe
    """
    summary: str
    """
    Application's short description.
    """
    version: str
    """
    Application version. e.g. 5.3.5
    """
    build: str
    """
    Application build. e.g. VTST
    """
    hasAdvancedComputeOptions: Optional[bool] = None
    """
    Whether advanced compute options are present
    """
    isLicensed: Optional[bool] = None
    """
    Whether licensing is present
    """
