# generated by datamodel-codegen:
#   filename:  software/application/build_config.json
#   version:   0.28.5

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel


class ApplicationVersionsWithBuildConfigSchema(BaseModel):
    bio: Optional[str] = None
    """
    The bio description used for the module files.
    """
    module_name: Optional[str] = None
    """
    Modulefile name specific to application version and build type.
    """
    image_name: Optional[str] = None
    """
    Apptainer image name.
    """
    image_tag: Optional[str] = None
    """
    Apptainer image tag.
    """
    dependencies: Optional[List[str]] = None
    """
    List of modulefile dependencies.
    """
    environment_variables: Optional[Dict[str, Any]] = None
    """
    Environment variables to be exported before running the application, containing the key and value pairs.
    """
