# generated by datamodel-codegen:
#   filename:  reusable/material/supercell_matrix_3d.json
#   version:   0.25.5

from __future__ import annotations

from typing import Any, List

from pydantic import Field, RootModel


class SupercellMatrix3DSchemaItem(RootModel[List[Any]]):
    root: List[Any]


class SupercellMatrix3DSchema(RootModel[List[SupercellMatrix3DSchemaItem]]):
    root: List[SupercellMatrix3DSchemaItem] = Field(..., max_length=3, min_length=3, title="Supercell Matrix 3D Schema")
    """
    3x3 matrix of integers for transforming a unit cell into a supercell
    """
