# generated by datamodel-codegen:
#   filename:  materials_category_components/operations/core/combinations/stack.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field, confloat


class AxisEnum(Enum):
    x = "x"
    y = "y"
    z = "z"


class ArrayWithIds(BaseModel):
    values: List[confloat(ge=0.0)]
    """
    Array of values corresponding to the ids
    """
    ids: List[int]
    """
    Array of integer ids
    """


class StackSchema(BaseModel):
    stack_components: List
    direction: AxisEnum = Field(..., title="Axis Enum")
    """
    Enum for axis types
    """
    gaps: Optional[ArrayWithIds] = Field(None, title="array with ids")
    """
    Gap distances between stack components with separate ids and values arrays
    """
