# generated by datamodel-codegen:
#   filename:  system/activity.json
#   version:   0.28.5

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class Status(Enum):
    draft = "draft"
    planned = "planned"
    active = "active"
    finished = "finished"
    error = "error"
    cancelled = "cancelled"


class EntityReferenceSchema(BaseModel):
    id: str = Field(..., alias="_id")
    """
    entity identity
    """
    cls: Optional[str] = None
    """
    entity class
    """
    slug: Optional[str] = None
    """
    entity slug
    """


class Operator(BaseModel):
    name: str
    """
    Operator's name as recorded, e.g. a username.
    """
    affiliation: Optional[str] = None
    """
    Institution the operator belongs to.
    """
    account: Optional[EntityReferenceSchema] = Field(None, alias="_account", title="entity reference schema")


class ActivitySchema(BaseModel):
    status: Optional[Status] = None
    """
    Lifecycle state. 'draft' marks a recipe or protocol that has not been executed.
    """
    startTime: Optional[datetime] = None
    """
    When the activity started, as an ISO 8601 timestamp. A string rather than an epoch number so it stays readable without a converter, matching job.startTime.
    """
    endTime: Optional[datetime] = None
    """
    When the activity finished, as an ISO 8601 timestamp.
    """
    operators: Optional[List[Operator]] = None
    """
    People who ran the activity. A name and an optional affiliation rather than the bibliographic author shape used for citations: a laboratory record identifies an operator by whatever the instrument logged, often a single username, and a citation's requirement of a surname does not hold there.
    """
    project: Optional[EntityReferenceSchema] = Field(None, alias="_project", title="entity reference schema")
