# generated by datamodel-codegen:
#   filename:  system/bankable.json
#   version:   0.28.5

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


class BankableSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    exabyte_id: Optional[str] = Field(None, alias="exabyteId")
    """
    Identity of the corresponding bank entity
    """
    hash: Optional[str] = None
    """
    Hash string which is calculated based on the meaningful fields of the entity. Used to identify equal entities.
    """
