# generated by datamodel-codegen:
#   filename:  system/entity_graph.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import Dict, List, Optional

from pydantic import BaseModel


class EdgeCountsByKind(BaseModel):
    extends: int
    contains: int
    variant: int


class Meta(BaseModel):
    nodeCount: int
    edgeCount: int
    edgeCountsByKind: EdgeCountsByKind
    """
    Number of edges of each relationship kind
    """
    layerCounts: Dict[str, int]
    """
    Number of schemas assigned to each layer
    """
    sameDocumentRefCount: int
    """
    Number of $ref statements pointing inside their own document, which are not edges
    """
    schemasWithExample: int
    isolatedNodeCount: int
    """
    Number of schemas with no incoming or outgoing references
    """


class Layer(Enum):
    primitive = "primitive"
    abstract = "abstract"
    reusable = "reusable"
    reference = "reference"
    definition = "definition"
    in_memory_entity = "in-memory-entity"
    system = "system"
    entity = "entity"
    entity_component = "entity-component"
    category = "category"
    directory = "directory"
    application_parsing = "application-parsing"


class Manifest(BaseModel):
    name: str
    isResult: Optional[bool] = None
    isMonitor: Optional[bool] = None
    defaultUnits: Optional[str] = None


class Node(BaseModel):
    id: str
    """
    Schema $id, dash-separated
    """
    path: str
    """
    Source path relative to the repository root
    """
    publishedPath: str
    """
    Path of the resolved copy on the published site, derived from $id
    """
    title: str
    description: str
    domain: str
    """
    Top-level source directory, or (root) for schemas at the top of schema/
    """
    layer: Layer
    """
    Architectural layer the schema belongs to
    """
    ownerEntity: Optional[str] = None
    """
    For entity-component nodes, the root entity the component belongs to
    """
    inDegree: int
    outDegree: int
    propertyCount: int
    hasExample: bool
    """
    Whether a mirror file exists under example/
    """
    manifest: Optional[Manifest] = None
    """
    Entry from manifest/properties.yaml when this schema is a registered property
    """


class Kind(Enum):
    extends = "extends"
    contains = "contains"
    variant = "variant"


class Edge(BaseModel):
    source: str
    """
    $id of the referencing schema
    """
    target: str
    """
    $id of the referenced schema
    """
    kind: Kind
    """
    Relationship expressed by the reference: allOf extends, properties/items contains, oneOf/anyOf is a variant
    """
    label: Optional[str] = None
    """
    Property name for contains edges, with a [] suffix when reached through items
    """
    pointer: Optional[str] = None
    """
    JSON pointer when the $ref carried a fragment
    """


class EntityGraphSchema(BaseModel):
    meta: Meta
    """
    Summary counts for the graph, used by the site and by the schema lint
    """
    nodes: List[Node]
    """
    One entry per schema in the corpus
    """
    edges: List[Edge]
    """
    One entry per cross-schema $ref
    """
