# generated by datamodel-codegen:
#   filename:  system/job_extended.json
#   version:   0.28.5

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, ConfigDict, Field


class EntityReferenceSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    field_id: str = Field(..., alias="_id")
    """
    entity identity
    """
    cls: Optional[str] = None
    """
    entity class
    """
    slug: Optional[str] = None
    """
    entity slug
    """


class ExtendedJobSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    mode: Optional[str] = None
    is_external: Optional[bool] = Field(None, alias="isExternal")
    field_materials: Optional[List[EntityReferenceSchema]] = Field(None, alias="_materials")
    field_materials_set: Optional[EntityReferenceSchema] = Field(
        None, alias="_materialsSet", title="entity reference schema"
    )
    purged: Optional[bool] = None
    purged_at: Optional[float] = Field(None, alias="purgedAt")
    dataset: Optional[Dict[str, Any]] = None
