# generated by datamodel-codegen:
#   filename:  core/primitive/1d_data_series.json
#   version:   0.28.5

from __future__ import annotations

from typing import List

from pydantic import ConfigDict, Field, RootModel


class Field1DimensionDataSeriesSchema(RootModel[List[List[float]]]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: List[List[float]] = Field(..., title="1 dimension data series schema")
