# generated by datamodel-codegen:
#   filename:  core/primitive/array_of_2_numbers.json
#   version:   0.28.5

from __future__ import annotations

from typing import List

from pydantic import ConfigDict, Field, RootModel


class ArrayOf2NumberElementsSchema(RootModel[List[float]]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: List[float] = Field(..., max_length=2, min_length=2, title="array of 2 number elements schema")
