# generated by datamodel-codegen:
#   filename:  core/primitive/array_of_3_booleans.json
#   version:   0.28.5

from __future__ import annotations

from typing import List

from pydantic import ConfigDict, Field, RootModel


class ArrayOf3BooleanElementsSchema(RootModel[List[bool]]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: List[bool] = Field(..., max_length=3, min_length=3, title="array of 3 boolean elements schema")
