# generated by datamodel-codegen:
#   filename:  properties_directory/structural/lattice/type_enum.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum


class LatticeTypeEnum(Enum):
    cub = "CUB"
    bcc = "BCC"
    fcc = "FCC"
    tet = "TET"
    mcl = "MCL"
    orc = "ORC"
    orcc = "ORCC"
    orcf = "ORCF"
    orci = "ORCI"
    hex = "HEX"
    bct = "BCT"
    tri = "TRI"
    mclc = "MCLC"
    rhl = "RHL"
