# generated by datamodel-codegen:
#   filename:  material/builders/multi_material/interfaces/strain_matching/zsl_strain_matching_interface_builder_parameters.json
#   version:   0.25.5

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class ZSLStrainMatchingParametersSchema(BaseModel):
    max_area: Optional[float] = 50
    """
    Maximum area for strain matching
    """
    max_area_ratio_tol: Optional[float] = 0.09
    """
    Maximum area ratio tolerance
    """
    max_length_tol: Optional[float] = 0.03
    """
    Maximum length tolerance
    """
    max_angle_tol: Optional[float] = 0.01
    """
    Maximum angle tolerance
    """


class ZSLStrainMatchingInterfaceBuilderParametersSchema(BaseModel):
    strain_matching_parameters: Optional[ZSLStrainMatchingParametersSchema] = Field(
        None, title="ZSL Strain Matching Parameters Schema"
    )
    """
    Parameters for ZSL strain matching
    """
