# generated by datamodel-codegen:
#   filename:  methods_directory/physical/psp/file_data_item.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, ConfigDict, Field, confloat, conint, constr

from .Reusable_schema_for_energy_value_with_unit_corresponding_to_a_specific_accuracy_level__e import (
    g,
)


class Type(Enum):
    us = "us"
    nc = "nc"
    nc_fr = "nc-fr"
    paw = "paw"
    coulomb = "coulomb"


class ExchangeCorrelation(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    approximation: Optional[str] = None
    """
    DFT approximation
    """
    functional: Optional[str] = None
    """
    Exchange correlation functional
    """
    path: Optional[str] = Field(None, title="category path schema")
    """
    TODO: Use regex once schema draft version has been updated
    """


class AtomicOrbitalSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    orbital_name: Optional[constr(pattern=r"^[1-7][sSpPdDfF]$")] = Field(None, alias="orbitalName")
    orbital_index: Optional[conint(ge=1)] = Field(None, alias="orbitalIndex")
    principal_number: Optional[conint(ge=1, le=7)] = Field(None, alias="principalNumber")
    angular_momentum: Optional[conint(ge=0, le=3)] = Field(None, alias="angularMomentum")
    occupation: Optional[confloat(ge=0.0, le=14.0)] = None
    """
    Shell occupation
    """


class Name(Enum):
    pseudopotential = "pseudopotential"


class Cutoffs(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    wavefunction: Optional[List[g.FieldUsedForSuggestedWavefunctionAndChargeDensityCutoffs]] = None
    """
    Energy cutoff values for wavefunction plane wave expansion.
    """
    density: Optional[List[g.FieldUsedForSuggestedWavefunctionAndChargeDensityCutoffs]] = None
    """
    Energy cutoff values for charge density plane wave expansion.
    """


class FileDataItem(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    element: str
    """
    chemical element
    """
    hash: str
    """
    MD5 hash of the pseudopotential file
    """
    type: Type
    source: str
    """
    explains where this came from
    """
    version: Optional[str] = None
    """
    explains the version of where this came from
    """
    exchange_correlation: ExchangeCorrelation = Field(..., alias="exchangeCorrelation")
    valence_configuration: Optional[List[AtomicOrbitalSchema]] = Field(None, alias="valenceConfiguration")
    """
    contains pseudo orbital information, including orbital names and occupations
    """
    path: str
    """
    location of the pseudopotential file on filesystem
    """
    apps: List[str]
    """
    The names of the simulation engines that can use this pseudopotential, e.g. espresso
    """
    filename: Optional[str] = None
    """
    filename of pseudopotential file on filesystem
    """
    name: Name
    """
    name of the data category
    """
    cutoffs: Optional[Cutoffs] = None
    """
    Suggested cutoff values for wave function and charge density.
    """
