# generated by datamodel-codegen:
#   filename:  software_directory/scripting/jupyter_lab.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, ConfigDict


class Summary(Enum):
    Jupyter_Lab = "Jupyter Lab"


class Version(Enum):
    field_0_33_12 = "0.33.12"


class JupyterLabApplicationSchema(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    summary: Optional[Summary] = None
    """
    Application's short description.
    """
    version: Optional[Version] = None
    """
    Application version. e.g. 5.3.5
    """
    shortName: Optional[str] = None
    """
    The short name of the application. e.g. qe
    """
    build: Optional[str] = None
    """
    Application build. e.g. VTST
    """
    hasAdvancedComputeOptions: Optional[bool] = None
    """
    Whether advanced compute options are present
    """
    isLicensed: Optional[bool] = None
    """
    Whether licensing is present
    """
