# generated by datamodel-codegen:
#   filename:  materials_category/defects/two_dimensional/island/configuration.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import List, Literal, Optional, Union

from pydantic import BaseModel, Field


class CoordinateShapeEnum(Enum):
    cylinder = "cylinder"
    sphere = "sphere"
    box = "box"
    triangular_prism = "triangular_prism"
    plane = "plane"


class CylinderCoordinateConditionSchema(BaseModel):
    shape: Literal["cylinder"] = Field(..., title="Coordinate Shape Enum")
    center_position: Optional[List[float]] = Field([0.5, 0.5], max_length=2, min_length=2)
    radius: Optional[float] = 0.25
    min_z: Optional[float] = 0
    max_z: Optional[float] = 1


class SphereCoordinateConditionSchema(BaseModel):
    shape: Literal["sphere"] = Field(..., title="Coordinate Shape Enum")
    center_position: Optional[List[float]] = Field([0.5, 0.5], max_length=2, min_length=2)
    radius: Optional[float] = 0.25


class PlaneCoordinateConditionSchema(BaseModel):
    shape: Literal["plane"] = Field(..., title="Coordinate Shape Enum")
    plane_normal: List[float] = Field(..., max_length=3, min_length=3)
    plane_point_coordinate: List[float] = Field(..., max_length=3, min_length=3)


class BoxCoordinateConditionSchema(BaseModel):
    shape: Literal["box"] = Field(..., title="Coordinate Shape Enum")
    min_coordinate: List[float] = Field(..., max_length=3, min_length=3)
    max_coordinate: List[float] = Field(..., max_length=3, min_length=3)


class TriangularPrismCoordinateConditionSchema(BaseModel):
    shape: Literal["triangular_prism"] = Field(..., title="Coordinate Shape Enum")
    position_on_surface_1: List[float] = Field(..., max_length=2, min_length=2)
    position_on_surface_2: List[float] = Field(..., max_length=2, min_length=2)
    position_on_surface_3: List[float] = Field(..., max_length=2, min_length=2)
    min_z: float
    max_z: float


class IslandSlabDefectConfigurationSchema(BaseModel):
    condition: Optional[
        Union[
            CylinderCoordinateConditionSchema,
            SphereCoordinateConditionSchema,
            PlaneCoordinateConditionSchema,
            BoxCoordinateConditionSchema,
            TriangularPrismCoordinateConditionSchema,
        ]
    ] = None
    center_position: Optional[List[float]] = None
    """
    Center position for symmetric shapes
    """
