# generated by datamodel-codegen:
#   filename:  materials_category/defects/zero_dimensional/defect_pair_configuration.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Literal, Optional, Union

from pydantic import BaseModel, Field, RootModel, confloat, conint


class DefectType(Enum):
    pair = "pair"


class DefectType1(Enum):
    vacancy = "vacancy"
    substitution = "substitution"
    interstitial = "interstitial"
    adatom = "adatom"


class PlacementMethod(Enum):
    coordinate = "coordinate"
    closest_site = "closest_site"
    equidistant = "equidistant"
    crystal_site = "crystal_site"
    voronoi_site = "voronoi_site"


class AtomicElements(BaseModel):
    id: float
    value: str
    occurrence: Optional[float] = None
    """
    Occurrence is for fractional occupations
    """
    oxidationState: Optional[float] = None


class AtomicCoordinate(BaseModel):
    id: Optional[float] = None
    value: Optional[Union[List[float], List[bool]]] = Field(None, title="vector schema")


class Units(Enum):
    crystal = "crystal"
    cartesian = "cartesian"


class AtomicLabel(BaseModel):
    id: Optional[float] = None
    value: Optional[conint(ge=1, le=9)] = Field(None, title="integer positive single digit")


class BasisSchema(BaseModel):
    elements: List[AtomicElements]
    coordinates: List[AtomicCoordinate]
    units: Optional[Units] = "crystal"
    labels: Optional[List[AtomicLabel]] = []


class Units87(Enum):
    km = "km"
    m = "m"
    cm = "cm"
    mm = "mm"
    um = "um"
    nm = "nm"
    angstrom = "angstrom"
    a_u_ = "a.u."
    bohr = "bohr"
    pm = "pm"


class LatticeExplicitUnit(BaseModel):
    alat: Optional[float] = 1
    """
    lattice parameter for fractional coordinates
    """
    units: Optional[Units87] = None
    a: List[float] = Field(..., max_length=3, min_length=3, title="array of 3 number elements schema")
    b: List[float] = Field(..., max_length=3, min_length=3, title="array of 3 number elements schema")
    c: List[float] = Field(..., max_length=3, min_length=3, title="array of 3 number elements schema")


class LatticeTypeEnum(Enum):
    CUB = "CUB"
    BCC = "BCC"
    FCC = "FCC"
    TET = "TET"
    MCL = "MCL"
    ORC = "ORC"
    ORCC = "ORCC"
    ORCF = "ORCF"
    ORCI = "ORCI"
    HEX = "HEX"
    BCT = "BCT"
    TRI = "TRI"
    MCLC = "MCLC"
    RHL = "RHL"


class Length(Enum):
    angstrom = "angstrom"
    bohr = "bohr"


class Angle(Enum):
    degree = "degree"
    radian = "radian"


class LatticeUnitsSchema(BaseModel):
    length: Optional[Length] = "angstrom"
    angle: Optional[Angle] = "degree"


class LatticeSchema(BaseModel):
    vectors: Optional[LatticeExplicitUnit] = Field(None, title="lattice explicit unit")
    type: Optional[LatticeTypeEnum] = Field("TRI", title="lattice type enum")
    units: Optional[LatticeUnitsSchema] = Field(
        default_factory=lambda: LatticeUnitsSchema.model_validate({"length": "angstrom", "angle": "degree"}),
        title="Lattice units schema",
    )
    a: float
    """
    length of the first lattice vector
    """
    b: float
    """
    length of the second lattice vector
    """
    c: float
    """
    length of the third lattice vector
    """
    alpha: float
    """
    angle between first and second lattice vector
    """
    beta: float
    """
    angle between second and third lattice vector
    """
    gamma: float
    """
    angle between first and third lattice vector
    """


class Name(Enum):
    volume = "volume"


class Units88(Enum):
    angstrom_3 = "angstrom^3"


class VolumeSchema(BaseModel):
    name: Literal["0#-datamodel-code-generator-#-object-#-special-#"]
    units: Optional[Units88] = None
    value: float


class Name131(Enum):
    density = "density"


class Units89(Enum):
    g_cm_3 = "g/cm^3"


class DensitySchema(BaseModel):
    name: Literal["1#-datamodel-code-generator-#-object-#-special-#"]
    units: Optional[Units89] = None
    value: float


class Units90(Enum):
    angstrom = "angstrom"


class ScalarSchema(BaseModel):
    units: Optional[Units90] = None
    value: float


class Name132(Enum):
    symmetry = "symmetry"


class SymmetrySchema(BaseModel):
    pointGroupSymbol: Optional[str] = None
    """
    point group symbol in Schoenflies notation
    """
    spaceGroupSymbol: Optional[str] = None
    """
    space group symbol in Hermann–Mauguin notation
    """
    tolerance: Optional[ScalarSchema] = Field(None, title="scalar schema")
    """
    tolerance used for symmetry calculation
    """
    name: Literal["2#-datamodel-code-generator-#-object-#-special-#"]


class Name133(Enum):
    elemental_ratio = "elemental_ratio"


class ElementalRatio(BaseModel):
    name: Literal["3#-datamodel-code-generator-#-object-#-special-#"]
    value: confloat(ge=0.0, le=1.0)
    element: Optional[str] = None
    """
    the element this ratio is for
    """


class Name134(Enum):
    p_norm = "p-norm"


class PNorm(BaseModel):
    name: Literal["4#-datamodel-code-generator-#-object-#-special-#"]
    degree: Optional[int] = None
    """
    degree of the dimensionality of the norm
    """
    value: float


class Name135(Enum):
    inchi = "inchi"


class InChIRepresentationSchema(BaseModel):
    name: Literal["5#-datamodel-code-generator-#-object-#-special-#"]
    value: str


class Name136(Enum):
    inchi_key = "inchi_key"


class InChIKeyRepresentationSchema(BaseModel):
    name: Literal["6#-datamodel-code-generator-#-object-#-special-#"]
    value: str


class DerivedPropertiesSchema(
    RootModel[
        Union[
            VolumeSchema,
            DensitySchema,
            SymmetrySchema,
            ElementalRatio,
            PNorm,
            InChIRepresentationSchema,
            InChIKeyRepresentationSchema,
        ]
    ]
):
    root: Union[
        VolumeSchema,
        DensitySchema,
        SymmetrySchema,
        ElementalRatio,
        PNorm,
        InChIRepresentationSchema,
        InChIKeyRepresentationSchema,
    ] = Field(..., discriminator="name")


class DatabaseSourceSchema(BaseModel):
    id: Union[str, float]
    """
    ID string for the materials uploaded from a third party source inside the third party source. For materialsproject.org an example ID is mp-32
    """
    source: str
    """
    Third party source name, e.g. materials project, 2dmatpedia, ICSD, etc.
    """
    origin: bool
    """
    Deprecated. To be removed. A flag that is true when material is initially imported from a third party * (as opposed to being independently designed from scratch).
    """
    data: Optional[Dict[str, Any]] = None
    """
    Original response from external source.
    """
    doi: Optional[str] = None
    """
    Digital Object Identifier, e.g. 10.1088/0953-8984/25/10/105506
    """
    url: Optional[str] = None
    """
    The URL of the original record, e.g. https://next-gen.materialsproject.org/materials/mp-48; ToDo: update to use URI type per https://json-schema.org/understanding-json-schema/reference/string#resource-identifiers
    """


class FileSourceSchema(BaseModel):
    extension: Optional[str] = None
    """
    file extension
    """
    filename: str
    """
    file name without extension
    """
    text: str
    """
    file content as raw text
    """
    hash: str
    """
    MD5 hash based on file content
    """


class Name137(Enum):
    default = "default"
    atomsTooClose = "atomsTooClose"
    atomsOverlap = "atomsOverlap"


class Severity(Enum):
    info = "info"
    warning = "warning"
    error = "error"


class MaterialConsistencyCheckSchema(BaseModel):
    name: Name137
    """
    Name of the consistency check that is performed, which is listed in an enum.
    """
    key: str
    """
    Key of the property of the entity on which the consistency check is performed in Mongo dot notation, e.g. 'basis.coordinates.1'
    """
    severity: Severity
    """
    Severity level of the problem, which is used in UI to differentiate.
    """
    message: str
    """
    Message generated by the consistency check describing the problem.
    """


class MaterialSchema(BaseModel):
    formula: Optional[str] = None
    """
    reduced chemical formula
    """
    unitCellFormula: Optional[str] = None
    """
    chemical formula based on the number of atoms of each element in the supercell
    """
    basis: BasisSchema = Field(..., title="basis schema")
    lattice: LatticeSchema = Field(..., title="lattice schema")
    derivedProperties: Optional[List[DerivedPropertiesSchema]] = Field(None, title="derived properties schema")
    external: Optional[DatabaseSourceSchema] = Field(None, title="database source schema")
    """
    information about a database source
    """
    src: Optional[FileSourceSchema] = Field(None, title="file source schema")
    """
    file source with the information inside
    """
    scaledHash: Optional[str] = None
    """
    Hash string for a scaled structure with lattice vector a set to 1 (eg. for materials under pressure).
    """
    icsdId: Optional[int] = None
    """
    Corresponding ICSD id of the material
    """
    isNonPeriodic: Optional[bool] = None
    """
    Whether to work in the finite molecular picture (usually with atomic orbital basis)
    """
    consistencyChecks: Optional[List[MaterialConsistencyCheckSchema]] = None
    field_id: Optional[str] = Field(None, alias="_id")
    """
    entity identity
    """
    slug: Optional[str] = None
    """
    entity slug
    """
    systemName: Optional[str] = None
    schemaVersion: Optional[str] = "2022.8.16"
    """
    entity's schema version. Used to distinct between different schemas.
    """
    name: Optional[str] = None
    """
    entity name
    """
    isDefault: Optional[bool] = False
    """
    Identifies that entity is defaultable
    """
    metadata: Optional[Dict[str, Any]] = None


class PointDefectConfigurationSchema(BaseModel):
    defect_type: DefectType1
    coordinate: Optional[List[float]] = Field([0, 0, 0], max_length=3, min_length=3)
    """
    The crystal coordinate of the defect
    """
    chemical_element: Optional[str] = None
    """
    The chemical element for substitution or interstitial defects
    """
    use_cartesian_coordinates: Optional[bool] = False
    """
    Whether coordinates are in cartesian rather than fractional coordinates
    """
    placement_method: Optional[PlacementMethod] = None
    crystal: MaterialSchema = Field(..., title="material schema")


class Units91(Enum):
    crystal = "crystal"
    cartesian = "cartesian"


class BasisSchema17(BaseModel):
    elements: List[AtomicElements]
    coordinates: List[AtomicCoordinate]
    units: Optional[Units91] = "crystal"
    labels: Optional[List[AtomicLabel]] = []


class Units92(Enum):
    km = "km"
    m = "m"
    cm = "cm"
    mm = "mm"
    um = "um"
    nm = "nm"
    angstrom = "angstrom"
    a_u_ = "a.u."
    bohr = "bohr"
    pm = "pm"


class LatticeExplicitUnit16(BaseModel):
    alat: Optional[float] = 1
    """
    lattice parameter for fractional coordinates
    """
    units: Optional[Units92] = None
    a: List[float] = Field(..., max_length=3, min_length=3, title="array of 3 number elements schema")
    b: List[float] = Field(..., max_length=3, min_length=3, title="array of 3 number elements schema")
    c: List[float] = Field(..., max_length=3, min_length=3, title="array of 3 number elements schema")


class LatticeUnitsSchema16(BaseModel):
    length: Optional[Length] = "angstrom"
    angle: Optional[Angle] = "degree"


class LatticeSchema16(BaseModel):
    vectors: Optional[LatticeExplicitUnit16] = Field(None, title="lattice explicit unit")
    type: Optional[LatticeTypeEnum] = Field("TRI", title="lattice type enum")
    units: Optional[LatticeUnitsSchema16] = Field(
        default_factory=lambda: LatticeUnitsSchema16.model_validate({"length": "angstrom", "angle": "degree"}),
        title="Lattice units schema",
    )
    a: float
    """
    length of the first lattice vector
    """
    b: float
    """
    length of the second lattice vector
    """
    c: float
    """
    length of the third lattice vector
    """
    alpha: float
    """
    angle between first and second lattice vector
    """
    beta: float
    """
    angle between second and third lattice vector
    """
    gamma: float
    """
    angle between first and third lattice vector
    """


class Name138(Enum):
    volume = "volume"


class Units93(Enum):
    angstrom_3 = "angstrom^3"


class VolumeSchema16(BaseModel):
    name: Literal["0#-datamodel-code-generator-#-object-#-special-#"]
    units: Optional[Units93] = None
    value: float


class Name139(Enum):
    density = "density"


class Units94(Enum):
    g_cm_3 = "g/cm^3"


class DensitySchema16(BaseModel):
    name: Literal["1#-datamodel-code-generator-#-object-#-special-#"]
    units: Optional[Units94] = None
    value: float


class Units95(Enum):
    angstrom = "angstrom"


class ScalarSchema17(BaseModel):
    units: Optional[Units95] = None
    value: float


class Name140(Enum):
    symmetry = "symmetry"


class SymmetrySchema16(BaseModel):
    pointGroupSymbol: Optional[str] = None
    """
    point group symbol in Schoenflies notation
    """
    spaceGroupSymbol: Optional[str] = None
    """
    space group symbol in Hermann–Mauguin notation
    """
    tolerance: Optional[ScalarSchema17] = Field(None, title="scalar schema")
    """
    tolerance used for symmetry calculation
    """
    name: Literal["2#-datamodel-code-generator-#-object-#-special-#"]


class Name141(Enum):
    elemental_ratio = "elemental_ratio"


class ElementalRatio16(BaseModel):
    name: Literal["3#-datamodel-code-generator-#-object-#-special-#"]
    value: confloat(ge=0.0, le=1.0)
    element: Optional[str] = None
    """
    the element this ratio is for
    """


class Name142(Enum):
    p_norm = "p-norm"


class PNorm16(BaseModel):
    name: Literal["4#-datamodel-code-generator-#-object-#-special-#"]
    degree: Optional[int] = None
    """
    degree of the dimensionality of the norm
    """
    value: float


class Name143(Enum):
    inchi = "inchi"


class InChIRepresentationSchema16(BaseModel):
    name: Literal["5#-datamodel-code-generator-#-object-#-special-#"]
    value: str


class Name144(Enum):
    inchi_key = "inchi_key"


class InChIKeyRepresentationSchema16(BaseModel):
    name: Literal["6#-datamodel-code-generator-#-object-#-special-#"]
    value: str


class DerivedPropertiesSchema16(
    RootModel[
        Union[
            VolumeSchema16,
            DensitySchema16,
            SymmetrySchema16,
            ElementalRatio16,
            PNorm16,
            InChIRepresentationSchema16,
            InChIKeyRepresentationSchema16,
        ]
    ]
):
    root: Union[
        VolumeSchema16,
        DensitySchema16,
        SymmetrySchema16,
        ElementalRatio16,
        PNorm16,
        InChIRepresentationSchema16,
        InChIKeyRepresentationSchema16,
    ] = Field(..., discriminator="name")


class Name145(Enum):
    default = "default"
    atomsTooClose = "atomsTooClose"
    atomsOverlap = "atomsOverlap"


class MaterialConsistencyCheckSchema17(BaseModel):
    name: Name145
    """
    Name of the consistency check that is performed, which is listed in an enum.
    """
    key: str
    """
    Key of the property of the entity on which the consistency check is performed in Mongo dot notation, e.g. 'basis.coordinates.1'
    """
    severity: Severity
    """
    Severity level of the problem, which is used in UI to differentiate.
    """
    message: str
    """
    Message generated by the consistency check describing the problem.
    """


class MaterialSchema16(BaseModel):
    formula: Optional[str] = None
    """
    reduced chemical formula
    """
    unitCellFormula: Optional[str] = None
    """
    chemical formula based on the number of atoms of each element in the supercell
    """
    basis: BasisSchema17 = Field(..., title="basis schema")
    lattice: LatticeSchema16 = Field(..., title="lattice schema")
    derivedProperties: Optional[List[DerivedPropertiesSchema16]] = Field(None, title="derived properties schema")
    external: Optional[DatabaseSourceSchema] = Field(None, title="database source schema")
    """
    information about a database source
    """
    src: Optional[FileSourceSchema] = Field(None, title="file source schema")
    """
    file source with the information inside
    """
    scaledHash: Optional[str] = None
    """
    Hash string for a scaled structure with lattice vector a set to 1 (eg. for materials under pressure).
    """
    icsdId: Optional[int] = None
    """
    Corresponding ICSD id of the material
    """
    isNonPeriodic: Optional[bool] = None
    """
    Whether to work in the finite molecular picture (usually with atomic orbital basis)
    """
    consistencyChecks: Optional[List[MaterialConsistencyCheckSchema17]] = None
    field_id: Optional[str] = Field(None, alias="_id")
    """
    entity identity
    """
    slug: Optional[str] = None
    """
    entity slug
    """
    systemName: Optional[str] = None
    schemaVersion: Optional[str] = "2022.8.16"
    """
    entity's schema version. Used to distinct between different schemas.
    """
    name: Optional[str] = None
    """
    entity name
    """
    isDefault: Optional[bool] = False
    """
    Identifies that entity is defaultable
    """
    metadata: Optional[Dict[str, Any]] = None


class AdatomConfigurationSchema(BaseModel):
    defect_type: Literal["adatom"] = "adatom"
    position_on_surface: List[float] = Field(..., max_length=2, min_length=2)
    """
    Position on the surface in 2D crystal coordinates
    """
    distance_z: confloat(ge=0.0)
    """
    Distance from the surface in Angstroms
    """
    chemical_element: str
    """
    Chemical element of the adatom
    """
    crystal: MaterialSchema16 = Field(..., title="material schema")


class Units96(Enum):
    crystal = "crystal"
    cartesian = "cartesian"


class BasisSchema18(BaseModel):
    elements: List[AtomicElements]
    coordinates: List[AtomicCoordinate]
    units: Optional[Units96] = "crystal"
    labels: Optional[List[AtomicLabel]] = []


class Units97(Enum):
    km = "km"
    m = "m"
    cm = "cm"
    mm = "mm"
    um = "um"
    nm = "nm"
    angstrom = "angstrom"
    a_u_ = "a.u."
    bohr = "bohr"
    pm = "pm"


class LatticeExplicitUnit17(BaseModel):
    alat: Optional[float] = 1
    """
    lattice parameter for fractional coordinates
    """
    units: Optional[Units97] = None
    a: List[float] = Field(..., max_length=3, min_length=3, title="array of 3 number elements schema")
    b: List[float] = Field(..., max_length=3, min_length=3, title="array of 3 number elements schema")
    c: List[float] = Field(..., max_length=3, min_length=3, title="array of 3 number elements schema")


class LatticeUnitsSchema17(BaseModel):
    length: Optional[Length] = "angstrom"
    angle: Optional[Angle] = "degree"


class LatticeSchema17(BaseModel):
    vectors: Optional[LatticeExplicitUnit17] = Field(None, title="lattice explicit unit")
    type: Optional[LatticeTypeEnum] = Field("TRI", title="lattice type enum")
    units: Optional[LatticeUnitsSchema17] = Field(
        default_factory=lambda: LatticeUnitsSchema17.model_validate({"length": "angstrom", "angle": "degree"}),
        title="Lattice units schema",
    )
    a: float
    """
    length of the first lattice vector
    """
    b: float
    """
    length of the second lattice vector
    """
    c: float
    """
    length of the third lattice vector
    """
    alpha: float
    """
    angle between first and second lattice vector
    """
    beta: float
    """
    angle between second and third lattice vector
    """
    gamma: float
    """
    angle between first and third lattice vector
    """


class Name146(Enum):
    volume = "volume"


class Units98(Enum):
    angstrom_3 = "angstrom^3"


class VolumeSchema17(BaseModel):
    name: Literal["0#-datamodel-code-generator-#-object-#-special-#"]
    units: Optional[Units98] = None
    value: float


class Name147(Enum):
    density = "density"


class Units99(Enum):
    g_cm_3 = "g/cm^3"


class DensitySchema17(BaseModel):
    name: Literal["1#-datamodel-code-generator-#-object-#-special-#"]
    units: Optional[Units99] = None
    value: float


class Units100(Enum):
    angstrom = "angstrom"


class ScalarSchema18(BaseModel):
    units: Optional[Units100] = None
    value: float


class Name148(Enum):
    symmetry = "symmetry"


class SymmetrySchema17(BaseModel):
    pointGroupSymbol: Optional[str] = None
    """
    point group symbol in Schoenflies notation
    """
    spaceGroupSymbol: Optional[str] = None
    """
    space group symbol in Hermann–Mauguin notation
    """
    tolerance: Optional[ScalarSchema18] = Field(None, title="scalar schema")
    """
    tolerance used for symmetry calculation
    """
    name: Literal["2#-datamodel-code-generator-#-object-#-special-#"]


class Name149(Enum):
    elemental_ratio = "elemental_ratio"


class ElementalRatio17(BaseModel):
    name: Literal["3#-datamodel-code-generator-#-object-#-special-#"]
    value: confloat(ge=0.0, le=1.0)
    element: Optional[str] = None
    """
    the element this ratio is for
    """


class Name150(Enum):
    p_norm = "p-norm"


class PNorm17(BaseModel):
    name: Literal["4#-datamodel-code-generator-#-object-#-special-#"]
    degree: Optional[int] = None
    """
    degree of the dimensionality of the norm
    """
    value: float


class Name151(Enum):
    inchi = "inchi"


class InChIRepresentationSchema17(BaseModel):
    name: Literal["5#-datamodel-code-generator-#-object-#-special-#"]
    value: str


class Name152(Enum):
    inchi_key = "inchi_key"


class InChIKeyRepresentationSchema17(BaseModel):
    name: Literal["6#-datamodel-code-generator-#-object-#-special-#"]
    value: str


class DerivedPropertiesSchema17(
    RootModel[
        Union[
            VolumeSchema17,
            DensitySchema17,
            SymmetrySchema17,
            ElementalRatio17,
            PNorm17,
            InChIRepresentationSchema17,
            InChIKeyRepresentationSchema17,
        ]
    ]
):
    root: Union[
        VolumeSchema17,
        DensitySchema17,
        SymmetrySchema17,
        ElementalRatio17,
        PNorm17,
        InChIRepresentationSchema17,
        InChIKeyRepresentationSchema17,
    ] = Field(..., discriminator="name")


class Name153(Enum):
    default = "default"
    atomsTooClose = "atomsTooClose"
    atomsOverlap = "atomsOverlap"


class MaterialConsistencyCheckSchema18(BaseModel):
    name: Name153
    """
    Name of the consistency check that is performed, which is listed in an enum.
    """
    key: str
    """
    Key of the property of the entity on which the consistency check is performed in Mongo dot notation, e.g. 'basis.coordinates.1'
    """
    severity: Severity
    """
    Severity level of the problem, which is used in UI to differentiate.
    """
    message: str
    """
    Message generated by the consistency check describing the problem.
    """


class MaterialSchema17(BaseModel):
    formula: Optional[str] = None
    """
    reduced chemical formula
    """
    unitCellFormula: Optional[str] = None
    """
    chemical formula based on the number of atoms of each element in the supercell
    """
    basis: BasisSchema18 = Field(..., title="basis schema")
    lattice: LatticeSchema17 = Field(..., title="lattice schema")
    derivedProperties: Optional[List[DerivedPropertiesSchema17]] = Field(None, title="derived properties schema")
    external: Optional[DatabaseSourceSchema] = Field(None, title="database source schema")
    """
    information about a database source
    """
    src: Optional[FileSourceSchema] = Field(None, title="file source schema")
    """
    file source with the information inside
    """
    scaledHash: Optional[str] = None
    """
    Hash string for a scaled structure with lattice vector a set to 1 (eg. for materials under pressure).
    """
    icsdId: Optional[int] = None
    """
    Corresponding ICSD id of the material
    """
    isNonPeriodic: Optional[bool] = None
    """
    Whether to work in the finite molecular picture (usually with atomic orbital basis)
    """
    consistencyChecks: Optional[List[MaterialConsistencyCheckSchema18]] = None
    field_id: Optional[str] = Field(None, alias="_id")
    """
    entity identity
    """
    slug: Optional[str] = None
    """
    entity slug
    """
    systemName: Optional[str] = None
    schemaVersion: Optional[str] = "2022.8.16"
    """
    entity's schema version. Used to distinct between different schemas.
    """
    name: Optional[str] = None
    """
    entity name
    """
    isDefault: Optional[bool] = False
    """
    Identifies that entity is defaultable
    """
    metadata: Optional[Dict[str, Any]] = None


class PointDefectConfigurationSchema1(BaseModel):
    defect_type: DefectType1
    coordinate: Optional[List[float]] = Field([0, 0, 0], max_length=3, min_length=3)
    """
    The crystal coordinate of the defect
    """
    chemical_element: Optional[str] = None
    """
    The chemical element for substitution or interstitial defects
    """
    use_cartesian_coordinates: Optional[bool] = False
    """
    Whether coordinates are in cartesian rather than fractional coordinates
    """
    placement_method: Optional[PlacementMethod] = None
    crystal: MaterialSchema17 = Field(..., title="material schema")


class Units101(Enum):
    crystal = "crystal"
    cartesian = "cartesian"


class BasisSchema19(BaseModel):
    elements: List[AtomicElements]
    coordinates: List[AtomicCoordinate]
    units: Optional[Units101] = "crystal"
    labels: Optional[List[AtomicLabel]] = []


class Units102(Enum):
    km = "km"
    m = "m"
    cm = "cm"
    mm = "mm"
    um = "um"
    nm = "nm"
    angstrom = "angstrom"
    a_u_ = "a.u."
    bohr = "bohr"
    pm = "pm"


class LatticeExplicitUnit18(BaseModel):
    alat: Optional[float] = 1
    """
    lattice parameter for fractional coordinates
    """
    units: Optional[Units102] = None
    a: List[float] = Field(..., max_length=3, min_length=3, title="array of 3 number elements schema")
    b: List[float] = Field(..., max_length=3, min_length=3, title="array of 3 number elements schema")
    c: List[float] = Field(..., max_length=3, min_length=3, title="array of 3 number elements schema")


class LatticeUnitsSchema18(BaseModel):
    length: Optional[Length] = "angstrom"
    angle: Optional[Angle] = "degree"


class LatticeSchema18(BaseModel):
    vectors: Optional[LatticeExplicitUnit18] = Field(None, title="lattice explicit unit")
    type: Optional[LatticeTypeEnum] = Field("TRI", title="lattice type enum")
    units: Optional[LatticeUnitsSchema18] = Field(
        default_factory=lambda: LatticeUnitsSchema18.model_validate({"length": "angstrom", "angle": "degree"}),
        title="Lattice units schema",
    )
    a: float
    """
    length of the first lattice vector
    """
    b: float
    """
    length of the second lattice vector
    """
    c: float
    """
    length of the third lattice vector
    """
    alpha: float
    """
    angle between first and second lattice vector
    """
    beta: float
    """
    angle between second and third lattice vector
    """
    gamma: float
    """
    angle between first and third lattice vector
    """


class Name154(Enum):
    volume = "volume"


class Units103(Enum):
    angstrom_3 = "angstrom^3"


class VolumeSchema18(BaseModel):
    name: Literal["0#-datamodel-code-generator-#-object-#-special-#"]
    units: Optional[Units103] = None
    value: float


class Name155(Enum):
    density = "density"


class Units104(Enum):
    g_cm_3 = "g/cm^3"


class DensitySchema18(BaseModel):
    name: Literal["1#-datamodel-code-generator-#-object-#-special-#"]
    units: Optional[Units104] = None
    value: float


class Units105(Enum):
    angstrom = "angstrom"


class ScalarSchema19(BaseModel):
    units: Optional[Units105] = None
    value: float


class Name156(Enum):
    symmetry = "symmetry"


class SymmetrySchema18(BaseModel):
    pointGroupSymbol: Optional[str] = None
    """
    point group symbol in Schoenflies notation
    """
    spaceGroupSymbol: Optional[str] = None
    """
    space group symbol in Hermann–Mauguin notation
    """
    tolerance: Optional[ScalarSchema19] = Field(None, title="scalar schema")
    """
    tolerance used for symmetry calculation
    """
    name: Literal["2#-datamodel-code-generator-#-object-#-special-#"]


class Name157(Enum):
    elemental_ratio = "elemental_ratio"


class ElementalRatio18(BaseModel):
    name: Literal["3#-datamodel-code-generator-#-object-#-special-#"]
    value: confloat(ge=0.0, le=1.0)
    element: Optional[str] = None
    """
    the element this ratio is for
    """


class Name158(Enum):
    p_norm = "p-norm"


class PNorm18(BaseModel):
    name: Literal["4#-datamodel-code-generator-#-object-#-special-#"]
    degree: Optional[int] = None
    """
    degree of the dimensionality of the norm
    """
    value: float


class Name159(Enum):
    inchi = "inchi"


class InChIRepresentationSchema18(BaseModel):
    name: Literal["5#-datamodel-code-generator-#-object-#-special-#"]
    value: str


class Name160(Enum):
    inchi_key = "inchi_key"


class InChIKeyRepresentationSchema18(BaseModel):
    name: Literal["6#-datamodel-code-generator-#-object-#-special-#"]
    value: str


class DerivedPropertiesSchema18(
    RootModel[
        Union[
            VolumeSchema18,
            DensitySchema18,
            SymmetrySchema18,
            ElementalRatio18,
            PNorm18,
            InChIRepresentationSchema18,
            InChIKeyRepresentationSchema18,
        ]
    ]
):
    root: Union[
        VolumeSchema18,
        DensitySchema18,
        SymmetrySchema18,
        ElementalRatio18,
        PNorm18,
        InChIRepresentationSchema18,
        InChIKeyRepresentationSchema18,
    ] = Field(..., discriminator="name")


class Name161(Enum):
    default = "default"
    atomsTooClose = "atomsTooClose"
    atomsOverlap = "atomsOverlap"


class MaterialConsistencyCheckSchema19(BaseModel):
    name: Name161
    """
    Name of the consistency check that is performed, which is listed in an enum.
    """
    key: str
    """
    Key of the property of the entity on which the consistency check is performed in Mongo dot notation, e.g. 'basis.coordinates.1'
    """
    severity: Severity
    """
    Severity level of the problem, which is used in UI to differentiate.
    """
    message: str
    """
    Message generated by the consistency check describing the problem.
    """


class MaterialSchema18(BaseModel):
    formula: Optional[str] = None
    """
    reduced chemical formula
    """
    unitCellFormula: Optional[str] = None
    """
    chemical formula based on the number of atoms of each element in the supercell
    """
    basis: BasisSchema19 = Field(..., title="basis schema")
    lattice: LatticeSchema18 = Field(..., title="lattice schema")
    derivedProperties: Optional[List[DerivedPropertiesSchema18]] = Field(None, title="derived properties schema")
    external: Optional[DatabaseSourceSchema] = Field(None, title="database source schema")
    """
    information about a database source
    """
    src: Optional[FileSourceSchema] = Field(None, title="file source schema")
    """
    file source with the information inside
    """
    scaledHash: Optional[str] = None
    """
    Hash string for a scaled structure with lattice vector a set to 1 (eg. for materials under pressure).
    """
    icsdId: Optional[int] = None
    """
    Corresponding ICSD id of the material
    """
    isNonPeriodic: Optional[bool] = None
    """
    Whether to work in the finite molecular picture (usually with atomic orbital basis)
    """
    consistencyChecks: Optional[List[MaterialConsistencyCheckSchema19]] = None
    field_id: Optional[str] = Field(None, alias="_id")
    """
    entity identity
    """
    slug: Optional[str] = None
    """
    entity slug
    """
    systemName: Optional[str] = None
    schemaVersion: Optional[str] = "2022.8.16"
    """
    entity's schema version. Used to distinct between different schemas.
    """
    name: Optional[str] = None
    """
    entity name
    """
    isDefault: Optional[bool] = False
    """
    Identifies that entity is defaultable
    """
    metadata: Optional[Dict[str, Any]] = None


class AdatomConfigurationSchema2(BaseModel):
    defect_type: Literal["adatom"] = "adatom"
    position_on_surface: List[float] = Field(..., max_length=2, min_length=2)
    """
    Position on the surface in 2D crystal coordinates
    """
    distance_z: confloat(ge=0.0)
    """
    Distance from the surface in Angstroms
    """
    chemical_element: str
    """
    Chemical element of the adatom
    """
    crystal: MaterialSchema18 = Field(..., title="material schema")


class Units106(Enum):
    crystal = "crystal"
    cartesian = "cartesian"


class BasisSchema20(BaseModel):
    elements: List[AtomicElements]
    coordinates: List[AtomicCoordinate]
    units: Optional[Units106] = "crystal"
    labels: Optional[List[AtomicLabel]] = []


class Units107(Enum):
    km = "km"
    m = "m"
    cm = "cm"
    mm = "mm"
    um = "um"
    nm = "nm"
    angstrom = "angstrom"
    a_u_ = "a.u."
    bohr = "bohr"
    pm = "pm"


class LatticeExplicitUnit19(BaseModel):
    alat: Optional[float] = 1
    """
    lattice parameter for fractional coordinates
    """
    units: Optional[Units107] = None
    a: List[float] = Field(..., max_length=3, min_length=3, title="array of 3 number elements schema")
    b: List[float] = Field(..., max_length=3, min_length=3, title="array of 3 number elements schema")
    c: List[float] = Field(..., max_length=3, min_length=3, title="array of 3 number elements schema")


class LatticeUnitsSchema19(BaseModel):
    length: Optional[Length] = "angstrom"
    angle: Optional[Angle] = "degree"


class LatticeSchema19(BaseModel):
    vectors: Optional[LatticeExplicitUnit19] = Field(None, title="lattice explicit unit")
    type: Optional[LatticeTypeEnum] = Field("TRI", title="lattice type enum")
    units: Optional[LatticeUnitsSchema19] = Field(
        default_factory=lambda: LatticeUnitsSchema19.model_validate({"length": "angstrom", "angle": "degree"}),
        title="Lattice units schema",
    )
    a: float
    """
    length of the first lattice vector
    """
    b: float
    """
    length of the second lattice vector
    """
    c: float
    """
    length of the third lattice vector
    """
    alpha: float
    """
    angle between first and second lattice vector
    """
    beta: float
    """
    angle between second and third lattice vector
    """
    gamma: float
    """
    angle between first and third lattice vector
    """


class Name162(Enum):
    volume = "volume"


class Units108(Enum):
    angstrom_3 = "angstrom^3"


class VolumeSchema19(BaseModel):
    name: Literal["0#-datamodel-code-generator-#-object-#-special-#"]
    units: Optional[Units108] = None
    value: float


class Name163(Enum):
    density = "density"


class Units109(Enum):
    g_cm_3 = "g/cm^3"


class DensitySchema19(BaseModel):
    name: Literal["1#-datamodel-code-generator-#-object-#-special-#"]
    units: Optional[Units109] = None
    value: float


class Units110(Enum):
    angstrom = "angstrom"


class ScalarSchema20(BaseModel):
    units: Optional[Units110] = None
    value: float


class Name164(Enum):
    symmetry = "symmetry"


class SymmetrySchema19(BaseModel):
    pointGroupSymbol: Optional[str] = None
    """
    point group symbol in Schoenflies notation
    """
    spaceGroupSymbol: Optional[str] = None
    """
    space group symbol in Hermann–Mauguin notation
    """
    tolerance: Optional[ScalarSchema20] = Field(None, title="scalar schema")
    """
    tolerance used for symmetry calculation
    """
    name: Literal["2#-datamodel-code-generator-#-object-#-special-#"]


class Name165(Enum):
    elemental_ratio = "elemental_ratio"


class ElementalRatio19(BaseModel):
    name: Literal["3#-datamodel-code-generator-#-object-#-special-#"]
    value: confloat(ge=0.0, le=1.0)
    element: Optional[str] = None
    """
    the element this ratio is for
    """


class Name166(Enum):
    p_norm = "p-norm"


class PNorm19(BaseModel):
    name: Literal["4#-datamodel-code-generator-#-object-#-special-#"]
    degree: Optional[int] = None
    """
    degree of the dimensionality of the norm
    """
    value: float


class Name167(Enum):
    inchi = "inchi"


class InChIRepresentationSchema19(BaseModel):
    name: Literal["5#-datamodel-code-generator-#-object-#-special-#"]
    value: str


class Name168(Enum):
    inchi_key = "inchi_key"


class InChIKeyRepresentationSchema19(BaseModel):
    name: Literal["6#-datamodel-code-generator-#-object-#-special-#"]
    value: str


class DerivedPropertiesSchema19(
    RootModel[
        Union[
            VolumeSchema19,
            DensitySchema19,
            SymmetrySchema19,
            ElementalRatio19,
            PNorm19,
            InChIRepresentationSchema19,
            InChIKeyRepresentationSchema19,
        ]
    ]
):
    root: Union[
        VolumeSchema19,
        DensitySchema19,
        SymmetrySchema19,
        ElementalRatio19,
        PNorm19,
        InChIRepresentationSchema19,
        InChIKeyRepresentationSchema19,
    ] = Field(..., discriminator="name")


class Name169(Enum):
    default = "default"
    atomsTooClose = "atomsTooClose"
    atomsOverlap = "atomsOverlap"


class MaterialConsistencyCheckSchema20(BaseModel):
    name: Name169
    """
    Name of the consistency check that is performed, which is listed in an enum.
    """
    key: str
    """
    Key of the property of the entity on which the consistency check is performed in Mongo dot notation, e.g. 'basis.coordinates.1'
    """
    severity: Severity
    """
    Severity level of the problem, which is used in UI to differentiate.
    """
    message: str
    """
    Message generated by the consistency check describing the problem.
    """


class MaterialSchema19(BaseModel):
    formula: Optional[str] = None
    """
    reduced chemical formula
    """
    unitCellFormula: Optional[str] = None
    """
    chemical formula based on the number of atoms of each element in the supercell
    """
    basis: BasisSchema20 = Field(..., title="basis schema")
    lattice: LatticeSchema19 = Field(..., title="lattice schema")
    derivedProperties: Optional[List[DerivedPropertiesSchema19]] = Field(None, title="derived properties schema")
    external: Optional[DatabaseSourceSchema] = Field(None, title="database source schema")
    """
    information about a database source
    """
    src: Optional[FileSourceSchema] = Field(None, title="file source schema")
    """
    file source with the information inside
    """
    scaledHash: Optional[str] = None
    """
    Hash string for a scaled structure with lattice vector a set to 1 (eg. for materials under pressure).
    """
    icsdId: Optional[int] = None
    """
    Corresponding ICSD id of the material
    """
    isNonPeriodic: Optional[bool] = None
    """
    Whether to work in the finite molecular picture (usually with atomic orbital basis)
    """
    consistencyChecks: Optional[List[MaterialConsistencyCheckSchema20]] = None
    field_id: Optional[str] = Field(None, alias="_id")
    """
    entity identity
    """
    slug: Optional[str] = None
    """
    entity slug
    """
    systemName: Optional[str] = None
    schemaVersion: Optional[str] = "2022.8.16"
    """
    entity's schema version. Used to distinct between different schemas.
    """
    name: Optional[str] = None
    """
    entity name
    """
    isDefault: Optional[bool] = False
    """
    Identifies that entity is defaultable
    """
    metadata: Optional[Dict[str, Any]] = None


class PointDefectPairConfigurationSchema(BaseModel):
    defect_type: Optional[DefectType] = None
    primary_defect_configuration: Union[PointDefectConfigurationSchema, AdatomConfigurationSchema]
    """
    Configuration for the first defect
    """
    secondary_defect_configuration: Union[PointDefectConfigurationSchema1, AdatomConfigurationSchema2]
    """
    Configuration for the second defect
    """
    crystal: MaterialSchema19 = Field(..., title="material schema")
