# generated by datamodel-codegen:
#   filename:  software_directory/modeling/lammps.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class Name(Enum):
    lammps = "lammps"


class Summary(Enum):
    LAMMPS = "LAMMPS"


class Version(Enum):
    field_2025_07_22_2 = "2025.07.22.2"


class Build(Enum):
    GNU = "GNU"
    Intel = "Intel"
    CUDA = "CUDA"


class Exec(Enum):
    lmp = "lmp"


class LAMMPS(BaseModel):
    name: Name
    """
    entity name
    """
    summary: Summary
    """
    Application's short description.
    """
    version: Version
    """
    Application version. e.g. 5.3.5
    """
    build: Build
    """
    Application build. e.g. VTST
    """
    exec: Optional[Exec] = None
<<<<<<< HEAD
=======
    shortName: Optional[str] = None
    """
    The short name of the application. e.g. qe
    """
    isDefault: Optional[bool] = False
    """
    Whether the build is the default build
    """
    hasAdvancedComputeOptions: Optional[bool] = None
    """
    Whether advanced compute options are present
    """
    isLicensed: Optional[bool] = None
    """
    Whether licensing is present
    """
    isUsingMaterial: Optional[bool] = None
    """
    Whether the application is using (being passed during a downstream processing routine) a material structure.
    """
>>>>>>> 2b0a111c7c55c4da1c23d8089d1c18db24a26ce3
    id: Optional[str] = Field(None, alias="_id")
    """
    entity identity
    """
    slug: Optional[str] = None
    """
    entity slug
    """
    systemName: Optional[str] = None
    schemaVersion: Optional[str] = "2022.8.16"
    """
    entity's schema version. Used to distinct between different schemas.
    """
    isDefault: Optional[bool] = False
    """
    Identifies that entity is defaultable
    """
    shortName: str
    """
    The short name of the application. e.g. qe
    """
    hasAdvancedComputeOptions: Optional[bool] = None
    """
    Whether advanced compute options are present
    """
    isLicensed: Optional[bool] = None
    """
    Whether licensing is present
    """
