# generated by datamodel-codegen:
#   filename:  software_directory/modeling/nwchem.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, ConfigDict


class Name(Enum):
    NWChem = "NWChem"


class Summary(Enum):
    NWChem__a_comprehensive_and_scalable_open_source_solution_for_large_scale_molecular_simulations = (
        "NWChem: a comprehensive and scalable open-source solution for large scale molecular simulations"
    )


class Version(Enum):
    field_6_6 = "6.6"
    field_7_0_2 = "7.0.2"


class NWChem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Optional[Name] = None
    """
    name of the application
    """
    summary: Optional[Summary] = None
    """
    Application's short description.
    """
    version: Optional[Version] = None
    """
    Application version. e.g. 5.3.5
    """
    shortName: Optional[str] = None
    """
    The short name of the application. e.g. qe
    """
    build: Optional[str] = None
    """
    Application build. e.g. VTST
    """
    isDefault: Optional[bool] = False
    """
    Whether the build is the default build
    """
    hasAdvancedComputeOptions: Optional[bool] = None
    """
    Whether advanced compute options are present
    """
    isLicensed: Optional[bool] = None
    """
    Whether licensing is present
    """
