# generated by datamodel-codegen:
#   filename:  software_directory/modeling/vasp.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class Name(Enum):
    vasp = "vasp"


class Summary(Enum):
    vienna_ab_initio_simulation_package = "vienna ab-initio simulation package"


class Flavor(Enum):
    vasp = "vasp"
    vasp_nscf = "vasp_nscf"
    vasp_bands = "vasp_bands"


class Version(Enum):
    field_5_3_5 = "5.3.5"


class Exec(Enum):
    vasp = "vasp"


class ViennaAbInitoSimulationPackage(BaseModel):
    name: Name
    """
    entity name
    """
    summary: Summary
    """
    Application's short description.
    """
    flavor: Optional[Flavor] = None
    version: Version
    """
    Application version. e.g. 5.3.5
    """
    exec: Optional[Exec] = None
    id: Optional[str] = Field(None, alias="_id")
    """
    entity identity
    """
    slug: Optional[str] = None
    """
    entity slug
    """
    systemName: Optional[str] = None
    schemaVersion: Optional[str] = "2022.8.16"
    """
    entity's schema version. Used to distinct between different schemas.
    """
    isDefault: Optional[bool] = False
    """
    Identifies that entity is defaultable
    """
    shortName: str
    """
    The short name of the application. e.g. qe
    """
    build: str
    """
    Application build. e.g. VTST
    """
    isDefaultVersion: Optional[bool] = None
    """
    Whether the version is the default version
    """
    hasAdvancedComputeOptions: Optional[bool] = None
    """
    Whether advanced compute options are present
    """
    isLicensed: Optional[bool] = None
    """
    Whether licensing is present
    """
    isUsingMaterial: Optional[bool] = None
    """
    Whether the application is using (being passed during a downstream processing routine) a material structure.
    """
