# generated by datamodel-codegen:
#   filename:  software_directory/modeling/vasp.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, ConfigDict


class Name(Enum):
    vasp = "vasp"


class Summary(Enum):
    vienna_ab_initio_simulation_package = "vienna ab-initio simulation package"


class Version(Enum):
    field_5_3_5 = "5.3.5"


class ViennaAbInitoSimulationPackage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Optional[Name] = None
    """
    name of the application
    """
    summary: Optional[Summary] = None
    """
    Application's short description.
    """
    version: Optional[Version] = None
    """
    Application version. e.g. 5.3.5
    """
    shortName: Optional[str] = None
    """
    The short name of the application. e.g. qe
    """
    build: Optional[str] = None
    """
    Application build. e.g. VTST
    """
    isDefault: Optional[bool] = False
    """
    Whether the build is the default build
    """
    hasAdvancedComputeOptions: Optional[bool] = None
    """
    Whether advanced compute options are present
    """
    isLicensed: Optional[bool] = None
    """
    Whether licensing is present
    """
