# generated by datamodel-codegen:
#   filename:  method/method_parameters.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import Optional, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel


class BasisSlug(Enum):
    cc_pvdz = "cc-pvdz"
    cc_pvtz = "cc-pvtz"
    cc_pvqz = "cc-pvqz"


class MethodParameters(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    basis_slug: Optional[BasisSlug] = Field(None, alias="basisSlug")


class BasisSlug3(Enum):
    field_3_21_g = "3-21G"
    field_6_31_g = "6-31G"
    field_6_311_g = "6-311G"


class MethodParameters1(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    basis_slug: Optional[BasisSlug3] = Field(None, alias="basisSlug")


class BasisSlug4(Enum):
    sto_3g = "sto-3g"
    sto_4g = "sto-4g"
    sto_6g = "sto-6g"
    def2_svp = "def2-svp"
    def2_tzvp = "def2-tzvp"
    def2_qzvp = "def2-qzvp"
    cbs_qb3 = "cbs-qb3"


class MethodParameters2(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    basis_slug: Optional[BasisSlug4] = Field(None, alias="basisSlug")


class ESSE(RootModel[Union[MethodParameters, MethodParameters1, MethodParameters2]]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: Union[MethodParameters, MethodParameters1, MethodParameters2] = Field(..., title="MethodParameters")
