# generated by datamodel-codegen:
#   filename:  properties_directory/structural/basis/atomic_constraint.json
#   version:   0.28.5

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class AtomicConstraintSchema(BaseModel):
    value: Optional[List[bool]] = Field(None, title="vector boolean 3d schema")
    id: int
    """
    integer id of this entry
    """
