# generated by datamodel-codegen:
#   filename:  reusable/material/slab/repetitions.json
#   version:   0.25.5

from __future__ import annotations

from typing import List

from pydantic import Field, RootModel, conint


class CrystalRepetitionsSchemaItem(RootModel[conint(ge=1)]):
    root: conint(ge=1)


class CrystalRepetitionsSchema(RootModel[List[CrystalRepetitionsSchemaItem]]):
    root: List[CrystalRepetitionsSchemaItem] = Field(
        ..., max_length=3, min_length=3, title="Crystal Repetitions Schema"
    )
    """
    Number of unit cells to repeat in each direction for a crystal structure
    """
