# generated by datamodel-codegen:
#   filename:  reusable/material/slab/vacuum.json
#   version:   0.25.5

from __future__ import annotations

from pydantic import Field, RootModel, confloat


class Vacuum(RootModel[confloat(ge=0.0)]):
    root: confloat(ge=0.0) = Field(..., title="Vacuum")
    """
    Vacuum thickness in Angstroms
    """
