# generated by datamodel-codegen:
#   filename:  core/primitive/linked_list/node_with_type.json
#   version:   0.28.5

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


class TypedNodeSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: Optional[str] = None
    next: Optional[str] = None
    """
    Flowchart ID of next node
    """
    head: Optional[bool] = None
    """
    Whether node is head node or not
    """
    flowchart_id: str = Field(..., alias="flowchartId")
    """
    Unique flowchart ID of node
    """


class FlowchartId(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    flowchart_id: str = Field(..., alias="flowchartId")
    """
    Unique flowchart ID of node
    """
