# generated by datamodel-codegen:
#   filename:  material/builders/multi_material/interfaces/simple/builder_parameters.json
#   version:   0.28.5

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class SimpleInterfaceBuilderParametersSchema(BaseModel):
    scale_film: Optional[bool] = True
    """
    Whether to scale the film to match the substrate
    """
    create_slabs: Optional[bool] = True
    """
    Whether to create slabs from the configurations or use the bulk
    """
