# generated by datamodel-codegen:
#   filename:  materials_category/pristine_structures/two_dimensional/nanotape.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Literal, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel, confloat, conint, constr


class ChemicalElements(Enum):
    h = "H"
    he = "He"
    li = "Li"
    be = "Be"
    b = "B"
    c = "C"
    n = "N"
    o = "O"
    f = "F"
    ne = "Ne"
    na = "Na"
    mg = "Mg"
    al = "Al"
    si = "Si"
    p = "P"
    s = "S"
    cl = "Cl"
    ar = "Ar"
    k = "K"
    ca = "Ca"
    sc = "Sc"
    ti = "Ti"
    v = "V"
    cr = "Cr"
    mn = "Mn"
    fe = "Fe"
    co = "Co"
    ni = "Ni"
    cu = "Cu"
    zn = "Zn"
    ga = "Ga"
    ge = "Ge"
    as_ = "As"
    se = "Se"
    br = "Br"
    kr = "Kr"
    rb = "Rb"
    sr = "Sr"
    y = "Y"
    zr = "Zr"
    nb = "Nb"
    mo = "Mo"
    tc = "Tc"
    ru = "Ru"
    rh = "Rh"
    pd = "Pd"
    ag = "Ag"
    cd = "Cd"
    in_ = "In"
    sn = "Sn"
    sb = "Sb"
    te = "Te"
    i = "I"
    xe = "Xe"
    cs = "Cs"
    ba = "Ba"
    la = "La"
    ce = "Ce"
    pr = "Pr"
    nd = "Nd"
    pm = "Pm"
    sm = "Sm"
    eu = "Eu"
    gd = "Gd"
    tb = "Tb"
    dy = "Dy"
    ho = "Ho"
    er = "Er"
    tm = "Tm"
    yb = "Yb"
    lu = "Lu"
    hf = "Hf"
    ta = "Ta"
    w = "W"
    re = "Re"
    os = "Os"
    ir = "Ir"
    pt = "Pt"
    au = "Au"
    hg = "Hg"
    tl = "Tl"
    pb = "Pb"
    bi = "Bi"
    po = "Po"
    at = "At"
    rn = "Rn"
    fr = "Fr"
    ra = "Ra"
    ac = "Ac"
    th = "Th"
    pa = "Pa"
    u = "U"
    np = "Np"
    pu = "Pu"
    am = "Am"
    cm = "Cm"
    bk = "Bk"
    cf = "Cf"
    es = "Es"
    fm = "Fm"
    md = "Md"
    no = "No"
    lr = "Lr"
    rf = "Rf"
    db = "Db"
    sg = "Sg"
    bh = "Bh"
    hs = "Hs"
    mt = "Mt"
    ds = "Ds"
    rg = "Rg"
    cn = "Cn"
    nh = "Nh"
    fl = "Fl"
    mc = "Mc"
    lv = "Lv"
    ts = "Ts"
    og = "Og"


class TerminationSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    chemical_elements: Union[ChemicalElements, constr(pattern=r"^([A-Z][a-z]?[0-9]*)+$")] = Field(
        ..., title="Chemical Elements"
    )
    """
    Chemical elements at the termination. Can be a single element (e.g. 'Si') or a compound (e.g. 'SiO')
    """
    space_group_symmetry_label: str = Field(..., title="Space Group Symmetry Label")
    """
    Space group symmetry designation for the termination
    """


class TerminationSchema25(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    chemical_elements: Union[ChemicalElements, constr(pattern=r"^([A-Z][a-z]?[0-9]*)+$")] = Field(
        ..., title="Chemical Elements"
    )
    """
    Chemical elements at the termination. Can be a single element (e.g. 'Si') or a compound (e.g. 'SiO')
    """
    space_group_symmetry_label: str = Field(..., title="Space Group Symmetry Label")
    """
    Space group symmetry designation for the termination
    """


class Value(Enum):
    h = "H"
    he = "He"
    li = "Li"
    be = "Be"
    b = "B"
    c = "C"
    n = "N"
    o = "O"
    f = "F"
    ne = "Ne"
    na = "Na"
    mg = "Mg"
    al = "Al"
    si = "Si"
    p = "P"
    s = "S"
    cl = "Cl"
    ar = "Ar"
    k = "K"
    ca = "Ca"
    sc = "Sc"
    ti = "Ti"
    v = "V"
    cr = "Cr"
    mn = "Mn"
    fe = "Fe"
    co = "Co"
    ni = "Ni"
    cu = "Cu"
    zn = "Zn"
    ga = "Ga"
    ge = "Ge"
    as_ = "As"
    se = "Se"
    br = "Br"
    kr = "Kr"
    rb = "Rb"
    sr = "Sr"
    y = "Y"
    zr = "Zr"
    nb = "Nb"
    mo = "Mo"
    tc = "Tc"
    ru = "Ru"
    rh = "Rh"
    pd = "Pd"
    ag = "Ag"
    cd = "Cd"
    in_ = "In"
    sn = "Sn"
    sb = "Sb"
    te = "Te"
    i = "I"
    xe = "Xe"
    cs = "Cs"
    ba = "Ba"
    la = "La"
    ce = "Ce"
    pr = "Pr"
    nd = "Nd"
    pm = "Pm"
    sm = "Sm"
    eu = "Eu"
    gd = "Gd"
    tb = "Tb"
    dy = "Dy"
    ho = "Ho"
    er = "Er"
    tm = "Tm"
    yb = "Yb"
    lu = "Lu"
    hf = "Hf"
    ta = "Ta"
    w = "W"
    re = "Re"
    os = "Os"
    ir = "Ir"
    pt = "Pt"
    au = "Au"
    hg = "Hg"
    tl = "Tl"
    pb = "Pb"
    bi = "Bi"
    po = "Po"
    at = "At"
    rn = "Rn"
    fr = "Fr"
    ra = "Ra"
    ac = "Ac"
    th = "Th"
    pa = "Pa"
    u = "U"
    np = "Np"
    pu = "Pu"
    am = "Am"
    cm = "Cm"
    bk = "Bk"
    cf = "Cf"
    es = "Es"
    fm = "Fm"
    md = "Md"
    no = "No"
    lr = "Lr"
    rf = "Rf"
    db = "Db"
    sg = "Sg"
    bh = "Bh"
    hs = "Hs"
    mt = "Mt"
    ds = "Ds"
    rg = "Rg"
    cn = "Cn"
    nh = "Nh"
    fl = "Fl"
    mc = "Mc"
    lv = "Lv"
    ts = "Ts"
    og = "Og"


class Value135(Enum):
    x = "X"
    vac = "Vac"


class AtomicElementSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: Union[Value, Value135]
    """
    All elements, including extra elements
    """
    id: int
    """
    integer id of this entry
    """


class AtomicCoordinateSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: List[float] = Field(..., max_length=3, min_length=3, title="coordinate 3d schema")
    """
    value of this entry
    """
    id: int
    """
    integer id of this entry
    """


class BasisUnitsEnum(Enum):
    crystal = "crystal"
    cartesian = "cartesian"


class AtomicLabelSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: Union[Union[int, str, float], conint(ge=1, le=9)]
    """
    value of this entry
    """
    id: int
    """
    integer id of this entry
    """


class BasisSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    elements: List[AtomicElementSchema] = Field(..., title="atomic elements schema")
    """
    atomic elements schema
    """
    coordinates: List[AtomicCoordinateSchema] = Field(..., title="atomic coordinates schema")
    """
    atomic coordinates schema
    """
    units: Optional[BasisUnitsEnum] = Field("crystal", title="basis units enum")
    labels: Optional[List[AtomicLabelSchema]] = Field(None, title="atomic labels schema")
    """
    atomic labels schema
    """


class LatticeVectorsUnitsEnum(Enum):
    angstrom = "angstrom"
    bohr = "bohr"


class LatticeVectorsSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    a: List[float] = Field(..., max_length=3, min_length=3, title="vector 3d schema")
    b: List[float] = Field(..., max_length=3, min_length=3, title="vector 3d schema")
    c: List[float] = Field(..., max_length=3, min_length=3, title="vector 3d schema")
    alat: Optional[float] = 1
    """
    lattice parameter for fractional coordinates
    """
    units: Optional[LatticeVectorsUnitsEnum] = Field("angstrom", title="lattice vectors units enum")


class LatticeTypeEnum(Enum):
    cub = "CUB"
    bcc = "BCC"
    fcc = "FCC"
    tet = "TET"
    mcl = "MCL"
    orc = "ORC"
    orcc = "ORCC"
    orcf = "ORCF"
    orci = "ORCI"
    hex = "HEX"
    bct = "BCT"
    tri = "TRI"
    mclc = "MCLC"
    rhl = "RHL"


class LatticeUnitsLengthEnum(Enum):
    angstrom = "angstrom"
    bohr = "bohr"


class LatticeUnitsAngleEnum(Enum):
    degree = "degree"
    radian = "radian"


class LatticeUnitsSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    length: Optional[LatticeUnitsLengthEnum] = Field("angstrom", title="lattice units length enum")
    angle: Optional[LatticeUnitsAngleEnum] = Field("degree", title="lattice units angle enum")


class LatticeSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    a: float
    """
    length of the first lattice vector
    """
    b: float
    """
    length of the second lattice vector
    """
    c: float
    """
    length of the third lattice vector
    """
    alpha: float
    """
    angle between first and second lattice vector
    """
    beta: float
    """
    angle between second and third lattice vector
    """
    gamma: float
    """
    angle between first and third lattice vector
    """
    vectors: Optional[LatticeVectorsSchema] = Field(None, title="lattice vectors schema")
    type: Optional[LatticeTypeEnum] = Field("TRI", title="lattice type enum")
    units: Optional[LatticeUnitsSchema] = Field(
        default_factory=lambda: LatticeUnitsSchema.model_validate({"length": "angstrom", "angle": "degree"}),
        title="Lattice units schema",
    )


class Name(Enum):
    volume = "volume"


class Units(Enum):
    angstrom_3 = "angstrom^3"


class VolumeSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: Literal["0#-datamodel-code-generator-#-object-#-special-#"]
    units: Optional[Units] = None
    value: float


class Name597(Enum):
    density = "density"


class Units263(Enum):
    g_cm_3 = "g/cm^3"


class DensitySchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: Literal["1#-datamodel-code-generator-#-object-#-special-#"]
    units: Optional[Units263] = None
    value: float


class Units264(Enum):
    angstrom = "angstrom"


class ScalarSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    units: Optional[Units264] = None
    value: float


class Name598(Enum):
    symmetry = "symmetry"


class SymmetrySchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    point_group_symbol: Optional[str] = Field(None, alias="pointGroupSymbol")
    """
    point group symbol in Schoenflies notation
    """
    space_group_symbol: Optional[str] = Field(None, alias="spaceGroupSymbol")
    """
    space group symbol in Hermann–Mauguin notation
    """
    tolerance: Optional[ScalarSchema] = Field(None, title="scalar schema")
    """
    tolerance used for symmetry calculation
    """
    name: Literal["2#-datamodel-code-generator-#-object-#-special-#"]


class Name599(Enum):
    elemental_ratio = "elemental_ratio"


class ElementalRatio(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: Literal["3#-datamodel-code-generator-#-object-#-special-#"]
    value: confloat(ge=0.0, le=1.0)
    element: Optional[str] = None
    """
    the element this ratio is for
    """


class Name600(Enum):
    p_norm = "p-norm"


class PNorm(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: Literal["4#-datamodel-code-generator-#-object-#-special-#"]
    degree: Optional[int] = None
    """
    degree of the dimensionality of the norm
    """
    value: float


class Name601(Enum):
    inchi = "inchi"


class InChIRepresentationSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: Literal["5#-datamodel-code-generator-#-object-#-special-#"]
    value: str


class Name602(Enum):
    inchi_key = "inchi_key"


class InChIKeyRepresentationSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: Literal["6#-datamodel-code-generator-#-object-#-special-#"]
    value: str


class DerivedPropertiesSchema(
    RootModel[
        Union[
            VolumeSchema,
            DensitySchema,
            SymmetrySchema,
            ElementalRatio,
            PNorm,
            InChIRepresentationSchema,
            InChIKeyRepresentationSchema,
        ]
    ]
):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: Union[
        VolumeSchema,
        DensitySchema,
        SymmetrySchema,
        ElementalRatio,
        PNorm,
        InChIRepresentationSchema,
        InChIKeyRepresentationSchema,
    ] = Field(..., discriminator="name")


class Source(Enum):
    materials_project = "MaterialsProject"
    materials_project_legacy = "MaterialsProjectLegacy"
    icsd = "ICSD"
    field_2dmatpedia = "2dmatpedia"


class DatabaseSourceSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Union[str, float]
    """
    ID string for the materials uploaded from a third party source inside the third party source. For materialsproject.org an example ID is mp-32
    """
    source: Source
    """
    Third party source name, e.g. materials project, 2dmatpedia, ICSD, etc.
    """
    origin: bool
    """
    Deprecated. To be removed. A flag that is true when material is initially imported from a third party * (as opposed to being independently designed from scratch).
    """
    data: Optional[Dict[str, Any]] = None
    """
    Original response from external source.
    """
    doi: Optional[str] = None
    """
    Digital Object Identifier, e.g. 10.1088/0953-8984/25/10/105506
    """
    url: Optional[str] = None
    """
    The URL of the original record, e.g. https://next-gen.materialsproject.org/materials/mp-48; ToDo: update to use URI type per https://json-schema.org/understanding-json-schema/reference/string#resource-identifiers
    """


class FileSourceSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    extension: Optional[str] = None
    """
    file extension
    """
    filename: str
    """
    file name without extension
    """
    text: str
    """
    file content as raw text
    """
    hash: str
    """
    MD5 hash based on file content
    """


class Name603(Enum):
    default = "default"
    atoms_too_close = "atomsTooClose"
    atoms_overlap = "atomsOverlap"


class Severity(Enum):
    info = "info"
    warning = "warning"
    error = "error"


class MaterialConsistencyCheckSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: Name603
    """
    Name of the consistency check that is performed, which is listed in an enum.
    """
    key: str
    """
    Key of the property of the entity on which the consistency check is performed in Mongo dot notation, e.g. 'basis.coordinates.1'
    """
    severity: Severity
    """
    Severity level of the problem, which is used in UI to differentiate.
    """
    message: str
    """
    Message generated by the consistency check describing the problem.
    """


class CrystalSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    formula: Optional[str] = None
    """
    reduced chemical formula
    """
    unit_cell_formula: Optional[str] = Field(None, alias="unitCellFormula")
    """
    chemical formula based on the number of atoms of each element in the supercell
    """
    basis: BasisSchema = Field(..., title="basis schema")
    lattice: LatticeSchema = Field(..., title="lattice schema")
    derived_properties: Optional[List[DerivedPropertiesSchema]] = Field(
        None, alias="derivedProperties", title="derived properties schema"
    )
    external: Optional[DatabaseSourceSchema] = Field(None, title="database source schema")
    """
    information about a database source
    """
    src: Optional[FileSourceSchema] = Field(None, title="file source schema")
    """
    file source with the information inside
    """
    scaled_hash: Optional[str] = Field(None, alias="scaledHash")
    """
    Hash string for a scaled structure with lattice vector a set to 1 (eg. for materials under pressure).
    """
    icsd_id: Optional[int] = Field(None, alias="icsdId")
    """
    Corresponding ICSD id of the material
    """
    is_non_periodic: Optional[bool] = Field(None, alias="isNonPeriodic")
    """
    Whether to work in the finite molecular picture (usually with atomic orbital basis)
    """
    consistency_checks: Optional[List[MaterialConsistencyCheckSchema]] = Field(None, alias="consistencyChecks")
    field_id: Optional[str] = Field(None, alias="_id")
    """
    entity identity
    """
    slug: Optional[str] = None
    """
    entity slug
    """
    system_name: Optional[str] = Field(None, alias="systemName")
    schema_version: Optional[str] = Field("2022.8.16", alias="schemaVersion")
    """
    entity's schema version. Used to distinct between different schemas.
    """
    name: Optional[str] = None
    """
    entity name
    """
    is_default: Optional[bool] = Field(False, alias="isDefault")
    """
    Identifies that entity is defaultable
    """
    metadata: Optional[Dict[str, Any]] = None


class CrystalLatticeLinesUniqueRepeatedSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    termination_top: TerminationSchema = Field(..., title="Termination Schema")
    """
    Defines a specific termination of a slab
    """
    termination_bottom: Optional[TerminationSchema25] = Field(None, title="Termination Schema")
    """
    Defines a specific termination of a slab
    """
    number_of_repetitions_width: Optional[conint(ge=1)] = 1
    """
    Number of repetitions in width direction
    """
    number_of_repetitions_length: Optional[conint(ge=1)] = 1
    """
    Number of repetitions in length direction
    """
    miller_indices_2d: List[int] = Field(..., max_length=2, min_length=2, title="2D Miller Indices Schema")
    """
    The (u,v) Miller indices for the line direction
    """
    crystal: CrystalSchema = Field(..., title="Crystal Schema")
    """
    A crystal structure, referencing the base material schema
    """
    use_conventional_cell: Optional[bool] = True
    """
    Use the conventional cell for the crystal structure
    """


class AxisEnum(Enum):
    x = "x"
    y = "y"
    z = "z"


class Value136(Enum):
    h = "H"
    he = "He"
    li = "Li"
    be = "Be"
    b = "B"
    c = "C"
    n = "N"
    o = "O"
    f = "F"
    ne = "Ne"
    na = "Na"
    mg = "Mg"
    al = "Al"
    si = "Si"
    p = "P"
    s = "S"
    cl = "Cl"
    ar = "Ar"
    k = "K"
    ca = "Ca"
    sc = "Sc"
    ti = "Ti"
    v = "V"
    cr = "Cr"
    mn = "Mn"
    fe = "Fe"
    co = "Co"
    ni = "Ni"
    cu = "Cu"
    zn = "Zn"
    ga = "Ga"
    ge = "Ge"
    as_ = "As"
    se = "Se"
    br = "Br"
    kr = "Kr"
    rb = "Rb"
    sr = "Sr"
    y = "Y"
    zr = "Zr"
    nb = "Nb"
    mo = "Mo"
    tc = "Tc"
    ru = "Ru"
    rh = "Rh"
    pd = "Pd"
    ag = "Ag"
    cd = "Cd"
    in_ = "In"
    sn = "Sn"
    sb = "Sb"
    te = "Te"
    i = "I"
    xe = "Xe"
    cs = "Cs"
    ba = "Ba"
    la = "La"
    ce = "Ce"
    pr = "Pr"
    nd = "Nd"
    pm = "Pm"
    sm = "Sm"
    eu = "Eu"
    gd = "Gd"
    tb = "Tb"
    dy = "Dy"
    ho = "Ho"
    er = "Er"
    tm = "Tm"
    yb = "Yb"
    lu = "Lu"
    hf = "Hf"
    ta = "Ta"
    w = "W"
    re = "Re"
    os = "Os"
    ir = "Ir"
    pt = "Pt"
    au = "Au"
    hg = "Hg"
    tl = "Tl"
    pb = "Pb"
    bi = "Bi"
    po = "Po"
    at = "At"
    rn = "Rn"
    fr = "Fr"
    ra = "Ra"
    ac = "Ac"
    th = "Th"
    pa = "Pa"
    u = "U"
    np = "Np"
    pu = "Pu"
    am = "Am"
    cm = "Cm"
    bk = "Bk"
    cf = "Cf"
    es = "Es"
    fm = "Fm"
    md = "Md"
    no = "No"
    lr = "Lr"
    rf = "Rf"
    db = "Db"
    sg = "Sg"
    bh = "Bh"
    hs = "Hs"
    mt = "Mt"
    ds = "Ds"
    rg = "Rg"
    cn = "Cn"
    nh = "Nh"
    fl = "Fl"
    mc = "Mc"
    lv = "Lv"
    ts = "Ts"
    og = "Og"


class Value137(Enum):
    x = "X"
    vac = "Vac"


class AtomicElementSchema66(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: Union[Value136, Value137]
    """
    All elements, including extra elements
    """
    id: int
    """
    integer id of this entry
    """


class BasisSchema64(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    elements: List[AtomicElementSchema66] = Field(..., title="atomic elements schema")
    """
    atomic elements schema
    """
    coordinates: List[AtomicCoordinateSchema] = Field(..., title="atomic coordinates schema")
    """
    atomic coordinates schema
    """
    units: Optional[BasisUnitsEnum] = Field("crystal", title="basis units enum")
    labels: Optional[List[AtomicLabelSchema]] = Field(None, title="atomic labels schema")
    """
    atomic labels schema
    """


class LatticeVectorsSchema64(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    a: List[float] = Field(..., max_length=3, min_length=3, title="vector 3d schema")
    b: List[float] = Field(..., max_length=3, min_length=3, title="vector 3d schema")
    c: List[float] = Field(..., max_length=3, min_length=3, title="vector 3d schema")
    alat: Optional[float] = 1
    """
    lattice parameter for fractional coordinates
    """
    units: Optional[LatticeVectorsUnitsEnum] = Field("angstrom", title="lattice vectors units enum")


class LatticeUnitsSchema64(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    length: Optional[LatticeUnitsLengthEnum] = Field("angstrom", title="lattice units length enum")
    angle: Optional[LatticeUnitsAngleEnum] = Field("degree", title="lattice units angle enum")


class LatticeSchema64(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    a: float
    """
    length of the first lattice vector
    """
    b: float
    """
    length of the second lattice vector
    """
    c: float
    """
    length of the third lattice vector
    """
    alpha: float
    """
    angle between first and second lattice vector
    """
    beta: float
    """
    angle between second and third lattice vector
    """
    gamma: float
    """
    angle between first and third lattice vector
    """
    vectors: Optional[LatticeVectorsSchema64] = Field(None, title="lattice vectors schema")
    type: Optional[LatticeTypeEnum] = Field("TRI", title="lattice type enum")
    units: Optional[LatticeUnitsSchema64] = Field(
        default_factory=lambda: LatticeUnitsSchema64.model_validate({"length": "angstrom", "angle": "degree"}),
        title="Lattice units schema",
    )


class Name604(Enum):
    volume = "volume"


class Units265(Enum):
    angstrom_3 = "angstrom^3"


class VolumeSchema64(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: Literal["0#-datamodel-code-generator-#-object-#-special-#"]
    units: Optional[Units265] = None
    value: float


class Name605(Enum):
    density = "density"


class Units266(Enum):
    g_cm_3 = "g/cm^3"


class DensitySchema65(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: Literal["1#-datamodel-code-generator-#-object-#-special-#"]
    units: Optional[Units266] = None
    value: float


class Units267(Enum):
    angstrom = "angstrom"


class ScalarSchema79(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    units: Optional[Units267] = None
    value: float


class Name606(Enum):
    symmetry = "symmetry"


class SymmetrySchema64(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    point_group_symbol: Optional[str] = Field(None, alias="pointGroupSymbol")
    """
    point group symbol in Schoenflies notation
    """
    space_group_symbol: Optional[str] = Field(None, alias="spaceGroupSymbol")
    """
    space group symbol in Hermann–Mauguin notation
    """
    tolerance: Optional[ScalarSchema79] = Field(None, title="scalar schema")
    """
    tolerance used for symmetry calculation
    """
    name: Literal["2#-datamodel-code-generator-#-object-#-special-#"]


class Name607(Enum):
    elemental_ratio = "elemental_ratio"


class ElementalRatio65(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: Literal["3#-datamodel-code-generator-#-object-#-special-#"]
    value: confloat(ge=0.0, le=1.0)
    element: Optional[str] = None
    """
    the element this ratio is for
    """


class Name608(Enum):
    p_norm = "p-norm"


class PNorm64(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: Literal["4#-datamodel-code-generator-#-object-#-special-#"]
    degree: Optional[int] = None
    """
    degree of the dimensionality of the norm
    """
    value: float


class Name609(Enum):
    inchi = "inchi"


class InChIRepresentationSchema65(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: Literal["5#-datamodel-code-generator-#-object-#-special-#"]
    value: str


class Name610(Enum):
    inchi_key = "inchi_key"


class InChIKeyRepresentationSchema65(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: Literal["6#-datamodel-code-generator-#-object-#-special-#"]
    value: str


class DerivedPropertiesSchema65(
    RootModel[
        Union[
            VolumeSchema64,
            DensitySchema65,
            SymmetrySchema64,
            ElementalRatio65,
            PNorm64,
            InChIRepresentationSchema65,
            InChIKeyRepresentationSchema65,
        ]
    ]
):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: Union[
        VolumeSchema64,
        DensitySchema65,
        SymmetrySchema64,
        ElementalRatio65,
        PNorm64,
        InChIRepresentationSchema65,
        InChIKeyRepresentationSchema65,
    ] = Field(..., discriminator="name")


class DatabaseSourceSchema64(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: Union[str, float]
    """
    ID string for the materials uploaded from a third party source inside the third party source. For materialsproject.org an example ID is mp-32
    """
    source: Source
    """
    Third party source name, e.g. materials project, 2dmatpedia, ICSD, etc.
    """
    origin: bool
    """
    Deprecated. To be removed. A flag that is true when material is initially imported from a third party * (as opposed to being independently designed from scratch).
    """
    data: Optional[Dict[str, Any]] = None
    """
    Original response from external source.
    """
    doi: Optional[str] = None
    """
    Digital Object Identifier, e.g. 10.1088/0953-8984/25/10/105506
    """
    url: Optional[str] = None
    """
    The URL of the original record, e.g. https://next-gen.materialsproject.org/materials/mp-48; ToDo: update to use URI type per https://json-schema.org/understanding-json-schema/reference/string#resource-identifiers
    """


class Name611(Enum):
    default = "default"
    atoms_too_close = "atomsTooClose"
    atoms_overlap = "atomsOverlap"


class MaterialConsistencyCheckSchema64(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: Name611
    """
    Name of the consistency check that is performed, which is listed in an enum.
    """
    key: str
    """
    Key of the property of the entity on which the consistency check is performed in Mongo dot notation, e.g. 'basis.coordinates.1'
    """
    severity: Severity
    """
    Severity level of the problem, which is used in UI to differentiate.
    """
    message: str
    """
    Message generated by the consistency check describing the problem.
    """


class CrystalSchema60(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    formula: Optional[str] = None
    """
    reduced chemical formula
    """
    unit_cell_formula: Optional[str] = Field(None, alias="unitCellFormula")
    """
    chemical formula based on the number of atoms of each element in the supercell
    """
    basis: BasisSchema64 = Field(..., title="basis schema")
    lattice: LatticeSchema64 = Field(..., title="lattice schema")
    derived_properties: Optional[List[DerivedPropertiesSchema65]] = Field(
        None, alias="derivedProperties", title="derived properties schema"
    )
    external: Optional[DatabaseSourceSchema64] = Field(None, title="database source schema")
    """
    information about a database source
    """
    src: Optional[FileSourceSchema] = Field(None, title="file source schema")
    """
    file source with the information inside
    """
    scaled_hash: Optional[str] = Field(None, alias="scaledHash")
    """
    Hash string for a scaled structure with lattice vector a set to 1 (eg. for materials under pressure).
    """
    icsd_id: Optional[int] = Field(None, alias="icsdId")
    """
    Corresponding ICSD id of the material
    """
    is_non_periodic: Optional[bool] = Field(None, alias="isNonPeriodic")
    """
    Whether to work in the finite molecular picture (usually with atomic orbital basis)
    """
    consistency_checks: Optional[List[MaterialConsistencyCheckSchema64]] = Field(None, alias="consistencyChecks")
    field_id: Optional[str] = Field(None, alias="_id")
    """
    entity identity
    """
    slug: Optional[str] = None
    """
    entity slug
    """
    system_name: Optional[str] = Field(None, alias="systemName")
    schema_version: Optional[str] = Field("2022.8.16", alias="schemaVersion")
    """
    entity's schema version. Used to distinct between different schemas.
    """
    name: Optional[str] = None
    """
    entity name
    """
    is_default: Optional[bool] = Field(False, alias="isDefault")
    """
    Identifies that entity is defaultable
    """
    metadata: Optional[Dict[str, Any]] = None


class VacuumConfigurationSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    direction: AxisEnum = Field(..., title="Axis Enum")
    """
    Enum for axis types
    """
    size: Optional[confloat(ge=0.0)] = 10
    """
    Size of the vacuum slab in angstroms
    """
    crystal: CrystalSchema60 = Field(..., title="Crystal Schema")
    """
    A crystal structure, referencing the base material schema
    """


class ObjectWithIdAndValueSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    value: float
    """
    value of this entry
    """
    id: int
    """
    integer id of this entry
    """


class NanoTapeConfigurationSchema(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    stack_components: List[Union[CrystalLatticeLinesUniqueRepeatedSchema, VacuumConfigurationSchema]] = Field(
        ..., max_length=2, min_length=2
    )
    direction: Optional[AxisEnum] = Field("y", title="Axis Enum")
    """
    Enum for axis types
    """
    gaps: Optional[List[ObjectWithIdAndValueSchema]] = None
    """
    Gap distances between stack components as array of objects with id and value
    """
