# generated by datamodel-codegen:
#   filename:  workflow/unit/context/boundary_conditions.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import Literal, Optional

from pydantic import BaseModel, Field


class Type(Enum):
    pbc = "pbc"
    bc1 = "bc1"
    bc2 = "bc2"
    bc3 = "bc3"


class BoundaryConditionsDataProviderSchema(BaseModel):
    type: Optional[Type] = "pbc"
    """
    If assume_isolated = 'esm', determines the boundary conditions used for either side of the slab.
    """
    offset: Optional[float] = None
    electricField: Optional[float] = Field(None, title="Electric Field (eV/A)")
    targetFermiEnergy: Optional[float] = Field(None, title="Target Fermi Energy (eV)")


class ExtraDataWithMaterialHashSchema(BaseModel):
    materialHash: Optional[str] = None


class BoundaryConditionsContextItemSchema(BaseModel):
    name: Literal["boundaryConditions"]
    data: BoundaryConditionsDataProviderSchema = Field(..., title="Boundary Conditions Data Provider Schema")
    extraData: ExtraDataWithMaterialHashSchema = Field(..., title="extraData with materialHash schema")
    isEdited: bool
