# generated by datamodel-codegen:
#   filename:  workflow/unit/context/neb.json
#   version:   0.28.5

from __future__ import annotations

from typing import Literal, Optional

from pydantic import BaseModel, Field


class NEBDataProviderSchema(BaseModel):
    nImages: Optional[float] = None


class NebContextItemSchema(BaseModel):
    name: Literal["neb"]
    data: NEBDataProviderSchema = Field(..., title="NEB Data Provider Schema")
    """
    Number of intermediate NEB images.
    """
    isEdited: bool
