# generated by datamodel-codegen:
#   filename:  material/primitive/modifications/repeat.json
#   version:   0.28.5

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field, RootModel


class SupercellMatrix3DSchemaItem(RootModel[List[int]]):
    root: List[int]


class RepeatSchema(BaseModel):
    matrix: Optional[List[SupercellMatrix3DSchemaItem]] = Field(
        default_factory=lambda: [
            SupercellMatrix3DSchemaItem.model_validate(v) for v in [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
        ],
        max_length=3,
        min_length=3,
        title="Supercell Matrix 3D Schema",
    )
    """
    3x3 matrix of integers for transforming a unit cell into a supercell
    """
