# generated by datamodel-codegen:
#   filename:  core/reference/external.json
#   version:   0.28.5

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class EntityReferenceSchema(BaseModel):
    id: str = Field(..., alias="_id")
    """
    entity identity
    """
    cls: Optional[str] = None
    """
    entity class
    """
    slug: Optional[str] = None
    """
    entity slug
    """


class ExternalReferenceSchema(BaseModel):
    origin: EntityReferenceSchema = Field(..., title="entity reference schema")
    subject: Optional[EntityReferenceSchema] = Field(None, title="entity reference schema")
    unitId: str
    """
    Id of the unit that extracted the result
    """
