---

name: Publish WIP release tarball

on: push

jobs:
  release-wip:
    # TODO: switch to @main once mat3ra/actions#43 merges
    uses: mat3ra/actions/.github/workflows/release-wip.yml@chore/SOF-7942-1
    with:
      package-name: esse
      build-script: transpile-and-build-assets
    secrets:
      github-token: ${{ secrets.BOT_GITHUB_TOKEN }}
